/**
 * @license
 * Copyright 2026 Greenhaven contributors
 * SPDX-License-Identifier: Apache-2.0
 */

// FEAT-CART-LIB-1 — read-only cartridge library service.
//
// Backs the `Worlds & Heroes` GUI by surfacing installed cartridges,
// created heroes, and per-hero per-cartridge playthrough state in
// UI-friendly DTOs. This slice never writes; later slices own
// import preview/apply, reimport, and hero+cartridge launch.
//
// Privacy / boundary rules pinned here:
//
//   * `recovery_code_hash` and `recovery_code_prefix` never leave
//     the service. Hero summaries carry the player's public id +
//     display name + level/xp only.
//   * `entities.profile` is read for `created`/`summary` only.
//     Hidden runtime overlays, private NPC memory, and actor
//     statuses are out of scope here — the player is the
//     authoritative scope for this surface.
//   * Counts in `CartridgeSummary` come from explicit kind filters
//     against `entities` joined with `cartridge_records`; debug
//     dumps / raw payloads stay server-internal.

import {activeCartridgeId} from '../cartridgeScope.js';
import {clearMetaCache} from '../cartridge.js';
import {query, withTransaction, type TxClient} from '../db.js';
import {readInstallCache} from './CartridgeImportPreviewService.js';
import {telemetry} from '../telemetry/index.js';
import {resolveDefaultForgeProject} from './DefaultCartridgeBootstrapService.js';
import {
  ASSET_MANIFEST_META_KEY,
  parseScopedManifestPayload,
  type CartridgeAssetManifest,
} from './CartridgeAssetManifestService.js';

export interface CartridgeCounts {
  locations: number;
  people: number;
  quests: number;
  scenes: number;
  items: number;
}

export interface CartridgeSourceSummary {
  kind: string;
  path: string | null;
  generatedFrom: string | null;
}

export interface CartridgeInstallCacheSummary {
  ready: boolean;
  state: 'ready' | 'active_db' | 'stale' | 'invalid' | 'missing' | 'rebuild_required';
  contentHash: string;
  recordCount: number;
  lastVerifiedAt: string;
  /** True when the GUI should prompt the player to (re)import. */
  importRequired: boolean;
}

export interface CartridgeSummary {
  id: string;
  title: string;
  version: string;
  schemaVersion: string;
  status: 'installed' | 'invalid' | 'needs_review' | 'deprecated';
  contentHash: string;
  counts: CartridgeCounts;
  installedAt: string;
  updatedAt: string;
  lastImportAt: string | null;
  validation: {errors: number; warnings: number};
  startingLocationName: string | null;
  source: CartridgeSourceSummary;
  isDefault: boolean;
  installCache: CartridgeInstallCacheSummary | null;
}

export interface CartridgeDetails extends CartridgeSummary {
  manifest: Record<string, unknown>;
  validationReport: Record<string, unknown>;
  scopedMeta: Array<{key: string; description: string | null}>;
  recentImports: Array<{
    id: number;
    mode: 'install' | 'reimport' | 'repair' | 'dry_run';
    status: 'previewed' | 'applied' | 'rejected' | 'failed';
    createdAt: string;
    appliedAt: string | null;
  }>;
}

export interface HeroCartridgeStateSummary {
  cartridgeId: string;
  status: 'available' | 'active' | 'incompatible' | 'archived';
  lastLocationName: string | null;
  lastSessionId: string | null;
  updatedAt: string;
}

export interface HeroSummary {
  playerId: number;
  publicId: string;
  name: string;
  level: number;
  xp: number;
  profileCreated: boolean;
  lastSeenAt: string | null;
  currentCartridgeId: string | null;
  states: HeroCartridgeStateSummary[];
}

/** FEAT-ENGINE-BASELINE-6 — first-run / boot-time library status.
 *
 *  Lets the GUI decide between launching gameplay and routing the
 *  operator into Worlds & Heroes without first calling the player /
 *  session bootstrap. None of the fields here require an
 *  authenticated player; they describe the engine + library state.
 */
export interface LibraryStatus {
  /** Total installed cartridges (any status). */
  cartridgeCount: number;
  /** Cartridges with a ready / active install cache and zero
   *  validation errors — i.e. launchable today. */
  readyCartridgeCount: number;
  /** Created heroes (players rows tied to a `kind = 'player'`
   *  entity). Boot can use this to skip Create Hero on a returning
   *  install. */
  heroCount: number;
  /** Heroes that have explicitly launched a cartridge. Boot uses
   *  this as the real "Continue" gate; a hero plus an installed
   *  world is not enough until Worlds & Heroes activates a concrete
   *  (hero, cartridge) playthrough. */
  activePlaythroughCount: number;
  /** Default Greenhaven Forge project on disk, generated by
   *  `cartridge:default:build`. The GUI surfaces this as a one-click
   *  Import in Worlds & Heroes when no cartridge is installed yet. */
  defaultForgeProject: {
    path: string;
    available: boolean;
  };
  /** Cartridge-owned title/menu atmosphere. Null means the UI should
   *  keep using its built-in fallback boot bundle. */
  bootMedia: CartridgeBootMedia | null;
}

export interface CartridgeBootMediaBundle {
  id: string;
  posterUrl: string | null;
  videoUrl: string | null;
  musicUrl: string | null;
}

export interface CartridgeBootMedia {
  cartridgeId: string;
  bundles: CartridgeBootMediaBundle[];
}

export interface PlaythroughSummary {
  playerId: number;
  publicId: string;
  heroName: string;
  cartridgeId: string;
  cartridgeTitle: string;
  status: 'available' | 'active' | 'incompatible' | 'archived';
  lastLocationName: string | null;
  lastSessionId: string | null;
  updatedAt: string;
}

export interface DeleteHeroResult {
  deleted: true;
  playerId: number;
  sessionsDeleted: number;
}

export interface DeleteCartridgeResult {
  deleted: true;
  cartridgeId: string;
  entitiesDeleted: number;
  sessionsDeleted: number;
  playthroughStatesDeleted: number;
  nextDefaultCartridgeId: string | null;
}

export interface ResetCartridgeResult {
  reset: true;
  cartridgeId: string;
  sessionsDeleted: number;
  playthroughStatesDeleted: number;
}

interface CartridgeRow {
  id: string;
  title: string;
  version: string;
  schema_version: string;
  status: string;
  content_hash: string;
  source_kind: string;
  source_path: string | null;
  manifest: Record<string, unknown> | null;
  validation_report: Record<string, unknown> | null;
  installed_at: string;
  updated_at: string;
}

const KIND_TO_COUNT: ReadonlyArray<{kind: string; bucket: keyof CartridgeCounts}> = [
  {kind: 'location', bucket: 'locations'},
  {kind: 'person', bucket: 'people'},
  {kind: 'quest', bucket: 'quests'},
  {kind: 'scene', bucket: 'scenes'},
  {kind: 'item', bucket: 'items'},
];

function emptyCounts(): CartridgeCounts {
  return {locations: 0, people: 0, quests: 0, scenes: 0, items: 0};
}

function validationCountsFromReport(report: Record<string, unknown> | null): {
  errors: number;
  warnings: number;
} {
  if (!report || typeof report !== 'object') return {errors: 0, warnings: 0};
  const e = (report as Record<string, unknown>)['errors'];
  const w = (report as Record<string, unknown>)['warnings'];
  return {
    errors: typeof e === 'number' && Number.isFinite(e) ? Math.max(0, Math.floor(e)) : 0,
    warnings:
      typeof w === 'number' && Number.isFinite(w) ? Math.max(0, Math.floor(w)) : 0,
  };
}

function assetRouteFor(
  cartridgeId: string,
  role: string,
): string {
  return `/api/assets/cartridges/${encodeURIComponent(
    cartridgeId,
  )}/world/cartridge/boot/${encodeURIComponent(role)}`;
}

function bootMediaFromManifest(
  cartridgeId: string,
  manifest: CartridgeAssetManifest | null,
): CartridgeBootMedia | null {
  if (!manifest) return null;
  const bundles = new Map<
    string,
    {posterUrl: string | null; videoUrl: string | null; musicUrl: string | null}
  >();
  for (const row of manifest.rows) {
    if (
      row.kind !== 'cartridge' ||
      row.slug !== 'boot' ||
      row.status !== 'available'
    ) {
      continue;
    }
    const match = /^boot_(poster|video|music)_(.+)$/.exec(row.role);
    if (!match) continue;
    const slot = match[1];
    const id = match[2];
    if (
      (slot !== 'poster' && slot !== 'video' && slot !== 'music') ||
      !id
    ) {
      continue;
    }
    const existing =
      bundles.get(id) ?? {posterUrl: null, videoUrl: null, musicUrl: null};
    const url = assetRouteFor(cartridgeId, row.role);
    if (slot === 'poster') existing.posterUrl = url;
    if (slot === 'video') existing.videoUrl = url;
    if (slot === 'music') existing.musicUrl = url;
    bundles.set(id, existing);
  }
  const out = Array.from(bundles.entries())
    .sort(([a], [b]) => a.localeCompare(b, undefined, {numeric: true}))
    .map(([id, bundle]) => ({id, ...bundle}))
    .filter(
      (bundle) => bundle.posterUrl || bundle.videoUrl || bundle.musicUrl,
    );
  return out.length > 0 ? {cartridgeId, bundles: out} : null;
}

async function loadBootMediaForCartridge(
  cartridgeId: string,
): Promise<CartridgeBootMedia | null> {
  const row = await query<{value: unknown}>(
    `SELECT value FROM cartridge_meta_scoped
      WHERE cartridge_id = $1 AND key = $2`,
    [cartridgeId, ASSET_MANIFEST_META_KEY],
  );
  return bootMediaFromManifest(
    cartridgeId,
    parseScopedManifestPayload(row.rows[0]?.value),
  );
}

async function loadBootMedia(
  readyCartridgeIds: string[],
  installedCartridgeIds: string[],
): Promise<CartridgeBootMedia | null> {
  const candidates: string[] = [];
  const defaultId = await activeCartridgeId().catch(() => '');
  if (defaultId) candidates.push(defaultId);
  candidates.push(...readyCartridgeIds, ...installedCartridgeIds);
  const seen = new Set<string>();
  for (const cartridgeId of candidates) {
    const normalized = cartridgeId.trim();
    if (!normalized || seen.has(normalized)) continue;
    seen.add(normalized);
    try {
      const media = await loadBootMediaForCartridge(normalized);
      if (media) return media;
    } catch (err) {
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.status.boot_media_read_failed',
        error: err,
        data: {
          cartridge_id: normalized,
          message: err instanceof Error ? err.message : String(err),
        },
      });
    }
  }
  return null;
}

function sourceSummary(row: CartridgeRow): CartridgeSourceSummary {
  const manifest = row.manifest ?? {};
  const generated = manifest['generatedFrom'];
  return {
    kind: row.source_kind,
    path: row.source_path,
    generatedFrom: typeof generated === 'string' ? generated : null,
  };
}

async function loadCounts(cartridgeId: string): Promise<CartridgeCounts> {
  const counts = emptyCounts();
  const r = await query<{kind: string; count: string}>(
    `SELECT e.kind, COUNT(*)::text AS count
       FROM entities e
       JOIN cartridge_records cr
         ON cr.imported_entity_id = e.id
        AND cr.cartridge_id = $1
        AND cr.status = 'active'
      WHERE e.kind = ANY($2::text[])
      GROUP BY e.kind`,
    [cartridgeId, KIND_TO_COUNT.map((row) => row.kind)],
  );
  for (const row of r.rows) {
    const bucket = KIND_TO_COUNT.find((m) => m.kind === row.kind)?.bucket;
    if (bucket) counts[bucket] = Number(row.count) || 0;
  }
  // FEAT-CART-LIB-1 backfill leaves `cartridge_records` empty for
  // the default cartridge until the import pipeline is wired in
  // FEAT-CART-LIB-2/3. Fall back to a direct `entities` count
  // scoped by `cartridge_id` so the GUI sees real values on the
  // default cartridge today.
  const hasAny = Object.values(counts).some((n) => n > 0);
  if (hasAny) return counts;
  const r2 = await query<{kind: string; count: string}>(
    `SELECT kind, COUNT(*)::text AS count
       FROM entities
      WHERE cartridge_id = $1
        AND kind = ANY($2::text[])
      GROUP BY kind`,
    [cartridgeId, KIND_TO_COUNT.map((row) => row.kind)],
  );
  for (const row of r2.rows) {
    const bucket = KIND_TO_COUNT.find((m) => m.kind === row.kind)?.bucket;
    if (bucket) counts[bucket] = Number(row.count) || 0;
  }
  return counts;
}

async function loadStartingLocationName(
  cartridgeId: string,
): Promise<string | null> {
  // Prefer scoped, fall back to legacy global so the migration
  // backfill works even if a future cartridge overrides it later.
  const r = await query<{display_name: string}>(
    `SELECT e.display_name
       FROM cartridge_meta_scoped m
       JOIN entities e ON e.id = ((m.value #>> '{}')::bigint)
      WHERE m.cartridge_id = $1
        AND m.key = 'starting_location_id'
      LIMIT 1`,
    [cartridgeId],
  );
  if (r.rows[0]?.display_name) return r.rows[0].display_name;
  const r2 = await query<{display_name: string}>(
    `SELECT e.display_name
       FROM cartridge_meta m
       JOIN entities e ON e.id = ((m.value #>> '{}')::bigint)
      WHERE m.key = 'starting_location_id'
      LIMIT 1`,
  );
  return r2.rows[0]?.display_name ?? null;
}

async function loadLastImportAt(cartridgeId: string): Promise<string | null> {
  const r = await query<{applied_at: string | null}>(
    `SELECT COALESCE(applied_at, created_at) AS applied_at
       FROM cartridge_import_runs
      WHERE cartridge_id = $1
      ORDER BY id DESC
      LIMIT 1`,
    [cartridgeId],
  );
  return r.rows[0]?.applied_at ?? null;
}

function toInstallCacheSummary(
  row: {
    cartridge_id: string;
    state: string;
    content_hash: string;
    record_count: number;
    last_verified_at: string;
  } | null,
  cartridgeContentHash: string,
): CartridgeInstallCacheSummary | null {
  if (!row) return null;
  const state =
    (row.state as CartridgeInstallCacheSummary['state']) ?? 'rebuild_required';
  const ready = state === 'ready' || state === 'active_db';
  // Import is required when the cache is not ready (any non-
  // `ready`/`active_db` state) or when the content hash diverged
  // from the cartridge row (i.e. an out-of-band update happened).
  // Once `ready === true` TypeScript narrows `state` to
  // `ready | active_db`, so the only remaining trigger is a hash
  // mismatch.
  const importRequired = !ready || row.content_hash !== cartridgeContentHash;
  return {
    ready,
    state,
    contentHash: row.content_hash,
    recordCount: Number(row.record_count) || 0,
    lastVerifiedAt: row.last_verified_at,
    importRequired,
  };
}

function toCartridgeSummary(
  row: CartridgeRow,
  defaultCartridgeId: string,
  counts: CartridgeCounts,
  startingLocationName: string | null,
  lastImportAt: string | null,
  installCache: CartridgeInstallCacheSummary | null,
): CartridgeSummary {
  return {
    id: row.id,
    title: row.title,
    version: row.version,
    schemaVersion: row.schema_version,
    status: row.status as CartridgeSummary['status'],
    contentHash: row.content_hash,
    counts,
    installedAt: row.installed_at,
    updatedAt: row.updated_at,
    lastImportAt,
    validation: validationCountsFromReport(row.validation_report),
    startingLocationName,
    source: sourceSummary(row),
    isDefault: row.id === defaultCartridgeId,
    installCache,
  };
}

async function deleteSessions(
  client: TxClient,
  sessionIds: string[],
): Promise<number> {
  if (sessionIds.length === 0) return 0;
  const r = await client.query(
    `DELETE FROM sessions
      WHERE id = ANY($1::text[])`,
    [sessionIds],
  );
  return r.rowCount ?? 0;
}

async function clearPlayerEntityReferences(
  client: TxClient,
  entityIds: number[],
): Promise<void> {
  if (entityIds.length === 0) return;
  await client.query(
    `UPDATE players
        SET class_id = CASE WHEN class_id = ANY($1::bigint[]) THEN NULL ELSE class_id END,
            current_location_id = CASE WHEN current_location_id = ANY($1::bigint[]) THEN NULL ELSE current_location_id END,
            current_scene_id = CASE WHEN current_scene_id = ANY($1::bigint[]) THEN NULL ELSE current_scene_id END,
            dialogue_partner_id = CASE WHEN dialogue_partner_id = ANY($1::bigint[]) THEN NULL ELSE dialogue_partner_id END
      WHERE class_id = ANY($1::bigint[])
         OR current_location_id = ANY($1::bigint[])
         OR current_scene_id = ANY($1::bigint[])
         OR dialogue_partner_id = ANY($1::bigint[])`,
    [entityIds],
  );
}

export class CartridgeLibraryService {
  /**
   * List every installed cartridge in `installed_at` order with
   * counts, validation summary, source, and the default flag.
   *
   * Hardened (2026-05-18 corrective): degraded local DB state (PGlite
   * WASM abort, missing table, dropped column, stale install-cache
   * row) MUST NOT escape to `app.onError` as a 500 — the Worlds &
   * Heroes screen reads this surface on boot and expects either a
   * cartridge list or `[]`. Each independent section is wrapped so
   * one bad cartridge or one missing helper table cannot fail the
   * whole list. Telemetry surfaces the failure under
   * `cartridge_library.list.*_failed` so operators can still see the
   * underlying cause in the gameplay log.
   */
  static async listCartridges(): Promise<CartridgeSummary[]> {
    let rows: {rows: CartridgeRow[]};
    try {
      rows = await query<CartridgeRow>(
        `SELECT id, title, version, schema_version, status, content_hash,
                source_kind, source_path, manifest, validation_report,
                installed_at::text AS installed_at,
                updated_at::text AS updated_at
           FROM cartridges
           ORDER BY installed_at ASC, id ASC`,
      );
    } catch (err) {
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.list.cartridges_read_failed',
        error: err,
        data: {message: err instanceof Error ? err.message : String(err)},
      });
      return [];
    }
    const defaultId = await activeCartridgeId().catch(() => '');
    const out: CartridgeSummary[] = [];
    for (const row of rows.rows) {
      let counts: CartridgeCounts = emptyCounts();
      try {
        counts = await loadCounts(row.id);
      } catch (err) {
        telemetry.record({
          channel: 'gameplay',
          name: 'cartridge_library.list.counts_failed',
          error: err,
          data: {
            cartridge_id: row.id,
            message: err instanceof Error ? err.message : String(err),
          },
        });
      }
      let startingLocationName: string | null = null;
      try {
        startingLocationName = await loadStartingLocationName(row.id);
      } catch (err) {
        telemetry.record({
          channel: 'gameplay',
          name: 'cartridge_library.list.starting_location_failed',
          error: err,
          data: {
            cartridge_id: row.id,
            message: err instanceof Error ? err.message : String(err),
          },
        });
      }
      let lastImportAt: string | null = null;
      try {
        lastImportAt = await loadLastImportAt(row.id);
      } catch (err) {
        telemetry.record({
          channel: 'gameplay',
          name: 'cartridge_library.list.last_import_failed',
          error: err,
          data: {
            cartridge_id: row.id,
            message: err instanceof Error ? err.message : String(err),
          },
        });
      }
      let installCacheSummary: CartridgeInstallCacheSummary | null = null;
      try {
        const installCacheRow = await readInstallCache(row.id);
        installCacheSummary = toInstallCacheSummary(
          installCacheRow,
          row.content_hash,
        );
      } catch (err) {
        telemetry.record({
          channel: 'gameplay',
          name: 'cartridge_library.list.install_cache_failed',
          error: err,
          data: {
            cartridge_id: row.id,
            message: err instanceof Error ? err.message : String(err),
          },
        });
      }
      out.push(
        toCartridgeSummary(
          row,
          defaultId,
          counts,
          startingLocationName,
          lastImportAt,
          installCacheSummary,
        ),
      );
    }
    return out;
  }

  /**
   * Single-cartridge detail view. Adds the manifest, validation
   * report, the scoped-meta key list (without values), and the
   * recent import-run audit trail.
   *
   * Hardened (2026-05-18 corrective): degraded auxiliary reads
   * (counts, scoped meta key list, recent imports) degrade to safe
   * defaults rather than escape to a 500. A failing base lookup
   * also degrades to `null` (which the route maps to `404
   * unknown_cartridge`), matching the existing not-found shape.
   */
  static async getCartridge(id: string): Promise<CartridgeDetails | null> {
    let row: CartridgeRow | undefined;
    try {
      const rows = await query<CartridgeRow>(
        `SELECT id, title, version, schema_version, status, content_hash,
                source_kind, source_path, manifest, validation_report,
                installed_at::text AS installed_at,
                updated_at::text AS updated_at
           FROM cartridges
           WHERE id = $1`,
        [id],
      );
      row = rows.rows[0];
    } catch (err) {
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.detail.cartridges_read_failed',
        error: err,
        data: {
          cartridge_id: id,
          message: err instanceof Error ? err.message : String(err),
        },
      });
      return null;
    }
    if (!row) return null;
    const defaultId = await activeCartridgeId().catch(() => '');
    let counts: CartridgeCounts = emptyCounts();
    try {
      counts = await loadCounts(row.id);
    } catch (err) {
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.detail.counts_failed',
        error: err,
        data: {
          cartridge_id: row.id,
          message: err instanceof Error ? err.message : String(err),
        },
      });
    }
    let startingLocationName: string | null = null;
    try {
      startingLocationName = await loadStartingLocationName(row.id);
    } catch (err) {
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.detail.starting_location_failed',
        error: err,
        data: {
          cartridge_id: row.id,
          message: err instanceof Error ? err.message : String(err),
        },
      });
    }
    let lastImportAt: string | null = null;
    try {
      lastImportAt = await loadLastImportAt(row.id);
    } catch (err) {
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.detail.last_import_failed',
        error: err,
        data: {
          cartridge_id: row.id,
          message: err instanceof Error ? err.message : String(err),
        },
      });
    }
    let installCacheSummary: CartridgeInstallCacheSummary | null = null;
    try {
      const installCacheRow = await readInstallCache(row.id);
      installCacheSummary = toInstallCacheSummary(
        installCacheRow,
        row.content_hash,
      );
    } catch (err) {
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.detail.install_cache_failed',
        error: err,
        data: {
          cartridge_id: row.id,
          message: err instanceof Error ? err.message : String(err),
        },
      });
    }
    const base = toCartridgeSummary(
      row,
      defaultId,
      counts,
      startingLocationName,
      lastImportAt,
      installCacheSummary,
    );
    let scopedMeta: Array<{key: string; description: string | null}> = [];
    try {
      const scopedRows = await query<{key: string; description: string | null}>(
        `SELECT key, description
           FROM cartridge_meta_scoped
          WHERE cartridge_id = $1
          ORDER BY key ASC`,
        [row.id],
      );
      scopedMeta = scopedRows.rows.map((r) => ({
        key: r.key,
        description: r.description,
      }));
    } catch (err) {
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.detail.scoped_meta_failed',
        error: err,
        data: {
          cartridge_id: row.id,
          message: err instanceof Error ? err.message : String(err),
        },
      });
    }
    let recentImports: CartridgeDetails['recentImports'] = [];
    try {
      const importsRows = await query<{
        id: number;
        mode: string;
        status: string;
        created_at: string;
        applied_at: string | null;
      }>(
        `SELECT id, mode, status,
                created_at::text AS created_at,
                applied_at::text AS applied_at
           FROM cartridge_import_runs
          WHERE cartridge_id = $1
          ORDER BY id DESC
          LIMIT 20`,
        [row.id],
      );
      recentImports = importsRows.rows.map((r) => ({
        id: Number(r.id),
        mode: r.mode as 'install' | 'reimport' | 'repair' | 'dry_run',
        status: r.status as 'previewed' | 'applied' | 'rejected' | 'failed',
        createdAt: r.created_at,
        appliedAt: r.applied_at,
      }));
    } catch (err) {
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.detail.recent_imports_failed',
        error: err,
        data: {
          cartridge_id: row.id,
          message: err instanceof Error ? err.message : String(err),
        },
      });
    }
    return {
      ...base,
      manifest: row.manifest ?? {},
      validationReport: row.validation_report ?? {},
      scopedMeta,
      recentImports,
    };
  }

  /**
   * List every created hero (`players` row) with their cross-
   * cartridge playthrough states. Sorted by `last_seen DESC` so
   * the GUI shows the most-recent hero first.
   *
   * Hardened (2026-05-18 corrective): base `players JOIN entities`
   * failure degrades to `[]` so BootGate / Worlds & Heroes can still
   * route the operator into Create Hero. A failing
   * `hero_cartridge_states` JOIN degrades each hero's `states` to
   * `[]` and `currentCartridgeId` to `null` — the hero list itself
   * still renders.
   */
  static async listHeroes(): Promise<HeroSummary[]> {
    let playerRows: {
      rows: Array<{
        entity_id: number;
        public_id: string;
        display_name: string;
        profile_created: boolean;
        current_xp: number;
        current_level: number;
        current_location_id: number | null;
        last_seen: string | null;
      }>;
    };
    try {
      playerRows = await query<{
        entity_id: number;
        public_id: string;
        display_name: string;
        profile_created: boolean;
        current_xp: number;
        current_level: number;
        current_location_id: number | null;
        last_seen: string | null;
      }>(
        `SELECT p.entity_id,
                p.public_id::text AS public_id,
                e.display_name,
                COALESCE((e.profile->>'created')::boolean, false) AS profile_created,
                p.current_xp,
                p.current_level,
                p.current_location_id,
                p.last_seen::text AS last_seen
           FROM players p
           JOIN entities e ON e.id = p.entity_id
          WHERE e.kind = 'player'
          ORDER BY p.last_seen DESC NULLS LAST, p.created_at DESC, p.entity_id DESC`,
      );
    } catch (err) {
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.heroes.players_read_failed',
        error: err,
        data: {message: err instanceof Error ? err.message : String(err)},
      });
      return [];
    }
    if (playerRows.rows.length === 0) return [];
    const playerIds = playerRows.rows.map((r) => r.entity_id);
    const byPlayer = new Map<number, HeroCartridgeStateSummary[]>();
    try {
      const stateRows = await query<{
        player_id: number;
        cartridge_id: string;
        status: string;
        last_session_id: string | null;
        current_location_id: number | null;
        last_location_name: string | null;
        updated_at: string;
      }>(
        `SELECT h.player_id, h.cartridge_id, h.status,
                h.last_session_id,
                h.current_location_id,
                loc.display_name AS last_location_name,
                h.updated_at::text AS updated_at
           FROM hero_cartridge_states h
           LEFT JOIN entities loc ON loc.id = h.current_location_id
          WHERE h.player_id = ANY($1::bigint[])
          ORDER BY h.updated_at DESC`,
        [playerIds],
      );
      for (const r of stateRows.rows) {
        const list = byPlayer.get(r.player_id) ?? [];
        list.push({
          cartridgeId: r.cartridge_id,
          status: r.status as HeroCartridgeStateSummary['status'],
          lastLocationName: r.last_location_name,
          lastSessionId: r.last_session_id,
          updatedAt: r.updated_at,
        });
        byPlayer.set(r.player_id, list);
      }
    } catch (err) {
      // Hero rows still render with empty `states` + null
      // `currentCartridgeId` so the GUI can show the hero list even
      // when the playthrough-state join blows up.
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.heroes.states_read_failed',
        error: err,
        data: {message: err instanceof Error ? err.message : String(err)},
      });
    }
    return playerRows.rows.map((row) => {
      const states = byPlayer.get(row.entity_id) ?? [];
      // Pick a "currentCartridgeId" deterministically: an `active`
      // state wins, otherwise the most recently updated row. This
      // is read-only; gameplay still chooses the world to play
      // through the existing bootstrap path.
      const active = states.find((s) => s.status === 'active');
      const currentCartridgeId =
        active?.cartridgeId ?? states[0]?.cartridgeId ?? null;
      return {
        playerId: row.entity_id,
        publicId: row.public_id,
        name: row.display_name,
        level: row.current_level,
        xp: Number(row.current_xp),
        profileCreated: row.profile_created,
        lastSeenAt: row.last_seen,
        currentCartridgeId,
        states,
      };
    });
  }

  /**
   * FEAT-ENGINE-BASELINE-6 — read-only library status used by the
   * boot flow. Returns ready cartridge count + hero count + default
   * generated Forge project availability so the GUI can route into
   * Worlds & Heroes (or straight to import) without touching player
   * identity.
   *
   * Hardened so the endpoint NEVER returns 500 for any of the
   * documented degraded states (clean worldless engine DB, no
   * cartridges installed, generated Forge project present but not
   * applied, ready install cache present, missing/stale scoped
   * metadata, partially generated Obsidian vault). Each independent
   * SQL section is wrapped so a single failure (missing table, stale
   * pgdata row, partial migration) degrades that section's count to
   * zero and emits structured telemetry under
   * `cartridge_library.status.*_failed` instead of crashing the boot
   * gate. Frontend `BootGate` + `WorldsHeroesScreen` then see
   * deterministic zeros + an explicit `defaultForgeProject.available`
   * flag and can route the operator into Worlds & Heroes / Import.
   */
  static async getLibraryStatus(): Promise<LibraryStatus> {
    let cartridgeCount = 0;
    let readyCartridgeCount = 0;
    const installedCartridgeIds: string[] = [];
    const readyCartridgeIds: string[] = [];
    try {
      const cartridgeRows = await query<{
        cartridge_id: string;
        content_hash: string;
        validation_report: Record<string, unknown> | null;
      }>(
        `SELECT id AS cartridge_id, content_hash, validation_report
           FROM cartridges`,
      );
      for (const row of cartridgeRows.rows) {
        cartridgeCount++;
        if (row.cartridge_id) installedCartridgeIds.push(row.cartridge_id);
        let summary: CartridgeInstallCacheSummary | null = null;
        try {
          const cache = await readInstallCache(row.cartridge_id);
          summary = toInstallCacheSummary(cache, row.content_hash);
        } catch (err) {
          // Stale/missing `cartridge_install_cache` row or table. The
          // cartridge is installed but we cannot prove the install
          // cache is ready, so `readyCartridgeCount` simply skips
          // this row — the GUI still surfaces it via the cartridge
          // list when needed.
          telemetry.record({
            channel: 'gameplay',
            name: 'cartridge_library.status.install_cache_read_failed',
            error: err,
            data: {
              cartridge_id: row.cartridge_id,
              message: err instanceof Error ? err.message : String(err),
            },
          });
        }
        const validation = validationCountsFromReport(row.validation_report);
        if (summary?.ready && validation.errors === 0) {
          readyCartridgeCount++;
          readyCartridgeIds.push(row.cartridge_id);
        }
      }
    } catch (err) {
      // `cartridges` table missing (pre-FEAT-CART-LIB-1 baseline) or
      // genuinely unreachable. Degrade to zero installed cartridges so
      // the GUI shows the "no cartridge installed / import available"
      // branch instead of crashing boot.
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.status.cartridges_read_failed',
        error: err,
        data: {message: err instanceof Error ? err.message : String(err)},
      });
      cartridgeCount = 0;
      readyCartridgeCount = 0;
    }

    let heroCount = 0;
    try {
      const heroRow = await query<{c: number | string}>(
        `SELECT COUNT(*)::int AS c
           FROM players p
           JOIN entities e ON e.id = p.entity_id
          WHERE e.kind = 'player'`,
      );
      heroCount = Number(heroRow.rows[0]?.c ?? 0);
      if (!Number.isFinite(heroCount) || heroCount < 0) heroCount = 0;
    } catch (err) {
      // Players/entities join failed (missing table, dropped column,
      // stale pgdata). Treat as zero heroes — the GUI then routes the
      // operator through Create Hero rather than failing the boot
      // gate.
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.status.heroes_read_failed',
        error: err,
        data: {message: err instanceof Error ? err.message : String(err)},
      });
      heroCount = 0;
    }

    let activePlaythroughCount = 0;
    try {
      const activeRow = await query<{c: number | string}>(
        `SELECT COUNT(*)::int AS c
           FROM hero_cartridge_states h
           JOIN players p ON p.entity_id = h.player_id
           JOIN entities e ON e.id = p.entity_id
           JOIN cartridges c ON c.id = h.cartridge_id
          WHERE h.status = 'active'
            AND e.kind = 'player'
            AND c.status = 'installed'`,
      );
      activePlaythroughCount = Number(activeRow.rows[0]?.c ?? 0);
      if (
        !Number.isFinite(activePlaythroughCount) ||
        activePlaythroughCount < 0
      ) {
        activePlaythroughCount = 0;
      }
    } catch (err) {
      // Missing / damaged playthrough tables mean there is no safe
      // gameplay target to continue. Degrade to zero so BootGate
      // routes through Worlds & Heroes instead of entering a broken
      // session.
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.status.active_playthroughs_read_failed',
        error: err,
        data: {message: err instanceof Error ? err.message : String(err)},
      });
      activePlaythroughCount = 0;
    }

    const defaultForge = resolveDefaultForgeProject();
    const bootMedia = await loadBootMedia(
      readyCartridgeIds,
      installedCartridgeIds,
    ).catch((err) => {
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.status.boot_media_failed',
        error: err,
        data: {message: err instanceof Error ? err.message : String(err)},
      });
      return null;
    });

    return {
      cartridgeCount,
      readyCartridgeCount,
      heroCount,
      activePlaythroughCount,
      defaultForgeProject: {
        path: defaultForge.forgeProject,
        available: defaultForge.available,
      },
      bootMedia,
    };
  }

  /**
   * Flat per-(hero, cartridge) playthrough rows. Useful for the
   * GUI's bottom "selected pair" summary and the bridge-side
   * launch-preview step. Read-only.
   *
   * Hardened (2026-05-18 corrective): any degraded read failure
   * degrades to `[]` so the Worlds & Heroes bottom panel stays
   * empty instead of crashing the whole library load.
   */
  static async listPlaythroughs(): Promise<PlaythroughSummary[]> {
    try {
      const rows = await query<{
        player_id: number;
        public_id: string;
        hero_name: string;
        cartridge_id: string;
        cartridge_title: string;
        status: string;
        last_session_id: string | null;
        last_location_name: string | null;
        updated_at: string;
      }>(
        `SELECT h.player_id,
                p.public_id::text AS public_id,
                e.display_name AS hero_name,
                h.cartridge_id,
                c.title AS cartridge_title,
                h.status,
                h.last_session_id,
                loc.display_name AS last_location_name,
                h.updated_at::text AS updated_at
           FROM hero_cartridge_states h
           JOIN players p ON p.entity_id = h.player_id
           JOIN entities e ON e.id = h.player_id
           JOIN cartridges c ON c.id = h.cartridge_id
           LEFT JOIN entities loc ON loc.id = h.current_location_id
          WHERE e.kind = 'player'
          ORDER BY h.updated_at DESC`,
      );
      return rows.rows.map((r) => ({
        playerId: r.player_id,
        publicId: r.public_id,
        heroName: r.hero_name,
        cartridgeId: r.cartridge_id,
        cartridgeTitle: r.cartridge_title,
        status: r.status as PlaythroughSummary['status'],
        lastLocationName: r.last_location_name,
        lastSessionId: r.last_session_id,
        updatedAt: r.updated_at,
      }));
    } catch (err) {
      telemetry.record({
        channel: 'gameplay',
        name: 'cartridge_library.playthroughs.read_failed',
        error: err,
        data: {message: err instanceof Error ? err.message : String(err)},
      });
      return [];
    }
  }

  /**
   * Permanently remove a hero identity and its local session history.
   *
   * This is a local single-operator library mutation, not a gameplay
   * turn. The player entity is the root; FK cascades remove player
   * progression/state tables and hero_cartridge_states. Sessions are
   * deleted explicitly first so transcript/outbox rows cascade too.
   */
  static async deleteHero(playerId: number): Promise<DeleteHeroResult | null> {
    return await withTransaction(async (client) => {
      const exists = await client.query<{id: number}>(
        `SELECT e.id
           FROM entities e
           JOIN players p ON p.entity_id = e.id
          WHERE e.id = $1
            AND e.kind = 'player'
          LIMIT 1`,
        [playerId],
      );
      if (!exists.rows[0]) return null;

      const sessionRows = await client.query<{id: string}>(
        `SELECT id
           FROM sessions
          WHERE player_id = $1`,
        [playerId],
      );
      const sessionsDeleted = await deleteSessions(
        client,
        sessionRows.rows.map((row) => row.id),
      );

      await client.query(
        `DELETE FROM entities
          WHERE id = $1
            AND kind = 'player'`,
        [playerId],
      );
      return {deleted: true as const, playerId, sessionsDeleted};
    });
  }

  /**
   * Reset every hero run in one installed world while preserving the
   * cartridge and its imported static content. After this operation a
   * hero can select the world again and start from the installed
   * cache without reimporting.
   */
  static async resetCartridge(
    cartridgeId: string,
  ): Promise<ResetCartridgeResult | null> {
    return await withTransaction(async (client) => {
      const exists = await client.query<{id: string}>(
        `SELECT id FROM cartridges WHERE id = $1 LIMIT 1`,
        [cartridgeId],
      );
      if (!exists.rows[0]) return null;

      const stateRows = await client.query<{
        player_id: number;
        last_session_id: string | null;
      }>(
        `SELECT player_id, last_session_id
           FROM hero_cartridge_states
          WHERE cartridge_id = $1`,
        [cartridgeId],
      );
      const playerIds = stateRows.rows.map((row) => row.player_id);
      const sessionIds = stateRows.rows
        .map((row) => row.last_session_id)
        .filter((id): id is string => typeof id === 'string' && id.length > 0);

      if (playerIds.length > 0) {
        await client.query(
          `UPDATE players
              SET current_location_id = NULL,
                  current_scene_id = NULL,
                  dialogue_partner_id = NULL
            WHERE entity_id = ANY($1::bigint[])`,
          [playerIds],
        );
      }
      const sessionsDeleted = await deleteSessions(client, sessionIds);
      const stateDelete = await client.query(
        `DELETE FROM hero_cartridge_states
          WHERE cartridge_id = $1`,
        [cartridgeId],
      );

      return {
        reset: true as const,
        cartridgeId,
        sessionsDeleted,
        playthroughStatesDeleted: stateDelete.rowCount ?? 0,
      };
    });
  }

  /**
   * Permanently remove an installed world. This deletes the cartridge
   * registry row, cartridge-scoped metadata/import/cache rows, all
   * playthrough state for that cartridge, and the non-player static
   * entities imported for the cartridge.
   */
  static async deleteCartridge(
    cartridgeId: string,
  ): Promise<DeleteCartridgeResult | null> {
    const result = await withTransaction(async (client) => {
      const exists = await client.query<{id: string}>(
        `SELECT id FROM cartridges WHERE id = $1 LIMIT 1`,
        [cartridgeId],
      );
      if (!exists.rows[0]) return null;

      const stateRows = await client.query<{last_session_id: string | null}>(
        `SELECT last_session_id
           FROM hero_cartridge_states
          WHERE cartridge_id = $1
            AND last_session_id IS NOT NULL`,
        [cartridgeId],
      );
      const sessionsDeleted = await deleteSessions(
        client,
        stateRows.rows
          .map((row) => row.last_session_id)
          .filter((id): id is string => typeof id === 'string' && id.length > 0),
      );

      const playthroughDelete = await client.query(
        `DELETE FROM hero_cartridge_states
          WHERE cartridge_id = $1`,
        [cartridgeId],
      );

      const entityRows = await client.query<{id: number}>(
        `SELECT id
           FROM entities
          WHERE cartridge_id = $1
            AND kind <> 'player'
            AND COALESCE(dynamic_origin, false) = false`,
        [cartridgeId],
      );
      const entityIds = entityRows.rows.map((row) => row.id);
      await clearPlayerEntityReferences(client, entityIds);
      const entityDelete =
        entityIds.length > 0
          ? await client.query(
              `DELETE FROM entities
                WHERE id = ANY($1::bigint[])`,
              [entityIds],
            )
          : {rowCount: 0};

      await client.query(
        `DELETE FROM cartridges
          WHERE id = $1`,
        [cartridgeId],
      );

      const next = await client.query<{id: string}>(
        `SELECT id
           FROM cartridges
          ORDER BY installed_at ASC, id ASC
          LIMIT 1`,
      );
      const nextDefaultCartridgeId = next.rows[0]?.id ?? null;
      if (nextDefaultCartridgeId) {
        await client.query(
          `INSERT INTO cartridge_meta (key, value, description, updated_at)
           SELECT key, value, description, now()
             FROM cartridge_meta_scoped
            WHERE cartridge_id = $1
           UNION ALL
           SELECT 'cartridge_id', to_jsonb($1::text), 'Identifier of the active cartridge.', now()
            WHERE NOT EXISTS (
              SELECT 1
                FROM cartridge_meta_scoped
               WHERE cartridge_id = $1
                 AND key = 'cartridge_id'
            )
           ON CONFLICT (key) DO UPDATE
             SET value = EXCLUDED.value,
                 description = EXCLUDED.description,
                 updated_at = now()`,
          [nextDefaultCartridgeId],
        );
      } else {
        await client.query(
          `DELETE FROM cartridge_meta`,
        );
      }

      return {
        deleted: true as const,
        cartridgeId,
        entitiesDeleted: entityDelete.rowCount ?? 0,
        sessionsDeleted,
        playthroughStatesDeleted: playthroughDelete.rowCount ?? 0,
        nextDefaultCartridgeId,
      };
    });
    if (result) clearMetaCache();
    return result;
  }
}
