/**
 * @license
 * Copyright 2026 Greenhaven contributors
 * SPDX-License-Identifier: Apache-2.0
 */

// FEAT-ENGINE-BASELINE-7 — stable baseline → cartridge → hero
// playthrough live smoke.
//
// Repeatable backend command that proves the full clean-engine →
// Obsidian-vault → cartridge install → hero launch → new game chain
// against a temp PGlite, without booting a real HTTP listener or
// touching the live `pgdata` directory. Drives the same `cartridge-
// library` Hono routes the boot-phase GUI calls, so any drift in the
// server contract surfaces here.
//
// Steps:
//   1. Temp PGlite + AUTH_DISABLED env.
//   2. `runMigrations()` — must report `fresh-baseline`.
//   3. Authored-content tables (`entities`, `cartridges`,
//      `cartridge_records`, `cartridge_meta_scoped`,
//      `cartridge_install_cache`, `cartridge_import_runs`) must all
//      be empty before any cartridge install.
//   4. Generate a tiny Obsidian vault on disk
//      (`WORLD_MANIFEST.md` + one location note under
//      `GreenHavenWorld/Locations/@Smoke Landing/SmokeLandingMind.md`).
//   5. `POST /api/cartridges/import/jobs` with
//      `sourceKind: 'obsidian_vault'` so the real
//      `compile_vault_to_forge.py` runs against the temp vault.
//   6. Poll the preview job until `ready` (or `failed`).
//   7. `POST /api/cartridges/import/jobs/:jobId/apply` with
//      `acceptWarnings: true`.
//   8. Assert cartridges + cartridge_records + install_cache landed,
//      scoped meta carries `starting_location_slug` +
//      `starting_location_id`.
//   9. `POST /api/heroes` — create a hero (FEAT-CART-LIB-5 contract).
//  10. `POST /api/playthroughs/preview` — confirm
//      mode != `repair_required` for the freshly-installed pair.
//  11. `POST /api/playthroughs/launch`.
//  12. Snapshot `cartridge_import_preview_jobs` +
//      `cartridge_import_runs` + `entities` + `cartridge_records`
//      row counts BEFORE new-game.
//  13. `POST /api/playthroughs/new-game`.
//  14. Re-snapshot the same tables. Assert no new import job /
//      import run / entity / record was created — only playthrough
//      runtime state was reset.
//  15. Write `result.json` to
//      `.codex/run-logs/live-playtest/engine-baseline-cartridge-smoke/`.
//
// Clean engine contract preserved: no archived migration replay,
// no raw vault SQL, no obsidian-dev-apply.
//
// Usage:
//
//   npm --prefix packages/web-server run live:engine-baseline-cartridge
//
// Optional flags:
//
//   --out <dir>          override result.json output dir.
//   --timeout-ms <ms>    preview-job wait timeout (default 240s).
//   --keep-temp          keep the temp PGlite + vault dirs.

import {mkdir, mkdtemp, rm, writeFile} from 'node:fs/promises';
import {existsSync, writeFileSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import type {ImportJobView} from '../services/CartridgeImportPreviewService.js';

interface Blocker {
  step: string;
  detail: string;
}

interface CountSnapshot {
  cartridge_import_preview_jobs: number;
  cartridge_import_runs: number;
  entities: number;
  cartridge_records: number;
  cartridge_meta_scoped: number;
  cartridge_install_cache: number;
}

interface Args {
  outDir: string;
  timeoutMs: number;
  keepTemp: boolean;
}

const FILE = fileURLToPath(import.meta.url);
const REPO_ROOT = path.resolve(path.dirname(FILE), '..', '..', '..', '..');
const DEFAULT_OUT = path.join(
  REPO_ROOT,
  '.codex',
  'run-logs',
  'live-playtest',
  'engine-baseline-cartridge-smoke',
);

function parseArgs(argv: string[]): Args {
  let outDir = DEFAULT_OUT;
  let timeoutMs = 240_000;
  let keepTemp = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--out') {
      outDir = argv[++i] ?? outDir;
    } else if (arg === '--timeout-ms') {
      timeoutMs = Number(argv[++i] ?? timeoutMs) || timeoutMs;
    } else if (arg === '--keep-temp') {
      keepTemp = true;
    }
  }
  return {outDir, timeoutMs, keepTemp};
}

function quoteIdent(identifier: string): string {
  if (!/^[a-z_][a-z0-9_]*$/i.test(identifier)) {
    throw new Error(`unsafe identifier: ${identifier}`);
  }
  return `"${identifier.replaceAll('"', '""')}"`;
}

// Build a tiny Obsidian-style vault that the transformer can read.
// The compile script keys off `WORLD_MANIFEST.md` for the start
// location wikilink, and treats any `GreenHavenWorld/Locations/...`
// `.md` note whose H1 starts with an `@` as a location entity.
async function generateTinyVault(): Promise<string> {
  const dir = await mkdtemp(path.join(os.tmpdir(), 'engine-baseline-smoke-vault-'));
  const locDir = path.join(dir, 'GreenHavenWorld', 'Locations', '@Smoke Landing');
  await mkdir(locDir, {recursive: true});
  const manifest = `# Smoke World

This vault is generated by the engine-baseline-cartridge smoke. It is
intentionally tiny — one start location and nothing else.

## Start of the game

Starting location:
[[SmokeLandingMind|Smoke Landing]]
`;
  await writeFile(path.join(dir, 'WORLD_MANIFEST.md'), manifest, 'utf8');
  const location = `# @Smoke Landing

@Smoke Landing is a flat stone landing high above a quiet city. The
wind is dry. The light is honest. Nothing waits for the player here
yet — that is the point.

## Canon

- Parent area: none — this is the entry point.
- Visibility: open from the first turn.
- Tone: calm, exposed, clean.
- Smoke fixture: yes (delete this note before shipping).
`;
  await writeFile(
    path.join(locDir, 'SmokeLandingMind.md'),
    location,
    'utf8',
  );
  return dir;
}

async function snapshotCounts(): Promise<CountSnapshot> {
  const {query} = await import('../db.js');
  const tables = [
    'cartridge_import_preview_jobs',
    'cartridge_import_runs',
    'entities',
    'cartridge_records',
    'cartridge_meta_scoped',
    'cartridge_install_cache',
  ] as const;
  const out: Partial<Record<(typeof tables)[number], number>> = {};
  for (const table of tables) {
    const row = await query<{c: number}>(
      `SELECT COUNT(*)::int AS c FROM ${quoteIdent(table)}`,
    );
    out[table] = Number(row.rows[0]?.c ?? 0);
  }
  return out as CountSnapshot;
}

interface HonoLike {
  request: (path: string) => Promise<Response> | Response;
}

async function pollPreviewJob(
  app: HonoLike,
  jobId: string,
  timeoutMs: number,
): Promise<ImportJobView | null> {
  const deadline = Date.now() + timeoutMs;
  let last: ImportJobView | null = null;
  while (Date.now() < deadline) {
    await new Promise((r) => setTimeout(r, 250));
    const res = await Promise.resolve(
      app.request(`/api/cartridges/import/jobs/${encodeURIComponent(jobId)}`),
    );
    if (res.status !== 200) {
      return last;
    }
    const view = (await res.json()) as ImportJobView;
    last = view;
    if (view.status === 'ready' || view.status === 'failed' || view.status === 'cancelled') {
      return view;
    }
  }
  return last;
}

async function main(argv: string[]): Promise<number> {
  const args = parseArgs(argv);
  const startedAt = new Date();
  const blockers: Blocker[] = [];
  const out: Record<string, unknown> = {
    startedAt: startedAt.toISOString(),
    passed: false,
  };

  const dbDir = await mkdtemp(path.join(os.tmpdir(), 'engine-baseline-smoke-db-'));
  let vaultDir = '';
  process.env.PGLITE_DATA_DIR = dbDir;
  process.env.AUTH_SECRET ??= 'engine-baseline-cartridge-smoke-secret-32-bytes-min';
  process.env.FEATHERLESS_API_KEY ??= 'smoke-not-real-key';
  process.env.NODE_ENV ??= 'development';
  process.env.AUTH_DISABLED ??= '1';

  // The preview service's `compile_vault_to_forge.py` spawner uses
  // `process.cwd()` to locate the script. `npm --prefix packages/
  // web-server` sets CWD to the package, so we need to chdir up to
  // the repo root before importing the service. Restore on exit so
  // the test runner / CI invoker isn't surprised by a global side
  // effect.
  const originalCwd = process.cwd();
  process.chdir(REPO_ROOT);

  await mkdir(args.outDir, {recursive: true});

  const log = (m: string): void => {
    process.stderr.write(`[engine-baseline-cartridge-smoke] ${m}\n`);
  };

  try {
    // ── 1. Migrations + fresh-baseline assertion ──────────────────
    const {runMigrations} = await import('../migrate.js');
    const {closeDb, query} = await import('../db.js');
    const migrate = await runMigrations();
    out['migrationMode'] = migrate.mode;
    out['migrationApplied'] = migrate.applied.length;
    log(`runMigrations mode=${migrate.mode} applied=${migrate.applied.length}`);
    if (migrate.mode !== 'fresh-baseline') {
      blockers.push({
        step: 'migrations',
        detail: `expected fresh-baseline, got ${migrate.mode}`,
      });
    }

    // ── 2. Pre-install — every cartridge-content table empty ──────
    const preInstall: Record<string, number> = {};
    for (const table of [
      'entities',
      'cartridges',
      'cartridge_records',
      'cartridge_meta_scoped',
      'cartridge_install_cache',
      'cartridge_import_runs',
    ]) {
      const row = await query<{c: number}>(
        `SELECT COUNT(*)::int AS c FROM ${quoteIdent(table)}`,
      );
      const count = Number(row.rows[0]?.c ?? 0);
      preInstall[table] = count;
      if (count !== 0) {
        blockers.push({
          step: 'pre_install_empty',
          detail: `${table} not empty: ${count}`,
        });
      }
    }
    out['preInstallCounts'] = preInstall;

    // ── 3. Generate tiny vault ────────────────────────────────────
    vaultDir = await generateTinyVault();
    out['vaultDir'] = vaultDir;
    log(`vault=${vaultDir}`);

    // ── 4. Mount Hono with cartridge-library routes ──────────────
    const {Hono} = await import('hono');
    const {cartridgeLibraryRoutes} = await import('../routes/cartridges.js');
    const app = new Hono();
    app.route('/api', cartridgeLibraryRoutes);

    // ── 4a. OPERATOR-HERO-CREATE-500 probe — POST /api/heroes BEFORE
    //        any cartridge is installed. Worlds & Heroes Create Hero
    //        is the reported 500 surface; a fresh anonymous player must
    //        mint on the clean engine baseline (no cartridge defaults
    //        in global `cartridge_meta`) and the response must not
    //        leak `recovery_code_hash` / `recovery_code_prefix`.
    {
      const preInstallHeroRes = await app.request('/api/heroes', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({}),
      });
      if (preInstallHeroRes.status !== 200) {
        const body = await preInstallHeroRes.text();
        blockers.push({
          step: 'pre_install_create_hero',
          detail: `expected 200, got ${preInstallHeroRes.status} body=${body.slice(
            0,
            200,
          )}`,
        });
      } else {
        const text = await preInstallHeroRes.text();
        const parsed = JSON.parse(text) as {
          player: {entity_id: number; public_id: string};
          clearClientCache: {keys: string[]; playerPublicId: string};
        };
        out['preInstallHero'] = {
          entity_id: parsed.player?.entity_id ?? null,
          public_id: parsed.player?.public_id ?? null,
          clearKeys: parsed.clearClientCache?.keys ?? [],
        };
        if (text.includes('recovery_code_hash')) {
          blockers.push({
            step: 'pre_install_create_hero_no_hash_leak',
            detail: 'response body leaked recovery_code_hash',
          });
        }
        if (text.includes('recovery_code_prefix')) {
          blockers.push({
            step: 'pre_install_create_hero_no_prefix_leak',
            detail: 'response body leaked recovery_code_prefix',
          });
        }
        // Delete the pre-install probe hero so the rest of the smoke's
        // entity-count snapshots keep their existing meaning. The
        // `entities(id) ON DELETE CASCADE` chain (migration 0001
        // baseline) wipes `players`, `session_tokens`, and the
        // `runtime_fields` trauma row in one shot.
        await query(`DELETE FROM entities WHERE id = $1`, [
          parsed.player.entity_id,
        ]);
      }
    }

    // ── 5. Preview job (sourceKind = obsidian_vault) ──────────────
    const createRes = await app.request('/api/cartridges/import/jobs', {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({
        sourceKind: 'obsidian_vault',
        sourcePath: vaultDir,
        mode: 'install',
      }),
    });
    if (createRes.status !== 201) {
      const body = await createRes.text();
      blockers.push({
        step: 'preview_create',
        detail: `expected 201, got ${createRes.status} body=${body.slice(0, 200)}`,
      });
    }
    const created = (await createRes.json()) as ImportJobView;
    out['previewJobId'] = created.jobId;
    log(`preview job=${created.jobId} status=${created.status}`);

    let previewView: ImportJobView | null = null;
    if (created.jobId) {
      previewView = await pollPreviewJob(app, created.jobId, args.timeoutMs);
      out['previewFinal'] = {
        status: previewView?.status ?? 'unknown',
        phase: previewView?.phase ?? 'unknown',
        error: previewView?.error ?? null,
        cartridgeId: previewView?.result?.cartridgeId ?? null,
        totalRecords: previewView?.result?.totalRecords ?? 0,
        validation: previewView?.result?.validation
          ? {
              errors: previewView.result.validation.errors,
              warnings: previewView.result.validation.warnings,
            }
          : null,
      };
      if (previewView?.status !== 'ready') {
        blockers.push({
          step: 'preview_ready',
          detail: `preview reached ${previewView?.status ?? 'unknown'} (error=${
            previewView?.error?.code ?? 'none'
          })`,
        });
      } else if ((previewView.result?.validation?.errors ?? 0) > 0) {
        blockers.push({
          step: 'preview_validation_errors',
          detail: `preview reported ${previewView.result?.validation?.errors} validation error(s)`,
        });
      }
    }

    // ── 6. Apply (acceptWarnings:true so warning-only previews land) ─
    let appliedView: ImportJobView | null = null;
    let cartridgeId: string | null = null;
    if (previewView?.status === 'ready') {
      const applyRes = await app.request(
        `/api/cartridges/import/jobs/${encodeURIComponent(created.jobId)}/apply`,
        {
          method: 'POST',
          headers: {'Content-Type': 'application/json'},
          body: JSON.stringify({acceptWarnings: true}),
        },
      );
      if (applyRes.status !== 200) {
        const body = await applyRes.text();
        blockers.push({
          step: 'apply',
          detail: `expected 200, got ${applyRes.status} body=${body.slice(0, 200)}`,
        });
      }
      appliedView = (await applyRes.json()) as ImportJobView;
      cartridgeId = appliedView.result?.cartridgeId ?? null;
      out['applyResult'] = {
        status: appliedView.status,
        cartridgeId,
        diff:
          (appliedView.result as unknown as {applyResult?: {diff: unknown}})
            ?.applyResult?.diff ?? null,
        totalRecords: appliedView.result?.totalRecords ?? 0,
      };
      log(
        `apply status=${appliedView.status} cartridge=${cartridgeId} records=${
          appliedView.result?.totalRecords ?? 0
        }`,
      );
      if (appliedView.status !== 'applied') {
        blockers.push({
          step: 'apply_status',
          detail: `apply ended in status=${appliedView.status} error=${
            appliedView.error?.code ?? 'none'
          }`,
        });
      }
    }

    // ── 7. Post-apply state ──────────────────────────────────────
    const postInstall: Record<string, number> = {};
    for (const table of [
      'entities',
      'cartridges',
      'cartridge_records',
      'cartridge_meta_scoped',
      'cartridge_install_cache',
      'cartridge_import_runs',
    ]) {
      const row = await query<{c: number}>(
        `SELECT COUNT(*)::int AS c FROM ${quoteIdent(table)}`,
      );
      postInstall[table] = Number(row.rows[0]?.c ?? 0);
    }
    out['postInstallCounts'] = postInstall;

    let installCacheRow: Record<string, unknown> | null = null;
    let scopedStartingSlug: string | null = null;
    let scopedStartingId: number | null = null;
    let contentHash: string | null = null;
    if (cartridgeId) {
      const cartRow = await query<{content_hash: string | null}>(
        `SELECT content_hash FROM cartridges WHERE id = $1`,
        [cartridgeId],
      );
      contentHash = cartRow.rows[0]?.content_hash ?? null;
      const cacheRow = await query<Record<string, unknown>>(
        `SELECT cartridge_id, state, content_hash, record_count,
                applied_at::text AS applied_at
           FROM cartridge_install_cache
          WHERE cartridge_id = $1`,
        [cartridgeId],
      );
      installCacheRow = cacheRow.rows[0] ?? null;
      out['installCacheRow'] = installCacheRow;
      if (!installCacheRow) {
        blockers.push({
          step: 'install_cache_row',
          detail: 'install_cache row missing for applied cartridge',
        });
      } else {
        const state = String(installCacheRow['state'] ?? '');
        if (state !== 'ready' && state !== 'active_db') {
          blockers.push({
            step: 'install_cache_state',
            detail: `install_cache state=${state} (expected ready|active_db)`,
          });
        }
      }
      const slugRow = await query<{value: string | null}>(
        `SELECT (value #>> '{}')::text AS value
           FROM cartridge_meta_scoped
          WHERE cartridge_id = $1 AND key = 'starting_location_slug'`,
        [cartridgeId],
      );
      scopedStartingSlug = slugRow.rows[0]?.value ?? null;
      const idRow = await query<{value: string | null}>(
        `SELECT (value #>> '{}')::text AS value
           FROM cartridge_meta_scoped
          WHERE cartridge_id = $1 AND key = 'starting_location_id'`,
        [cartridgeId],
      );
      const rawId = idRow.rows[0]?.value;
      scopedStartingId =
        rawId != null && rawId !== '' && Number.isFinite(Number(rawId))
          ? Number(rawId)
          : null;
      out['scopedStarting'] = {
        slug: scopedStartingSlug,
        id: scopedStartingId,
      };
      if (!scopedStartingSlug) {
        blockers.push({
          step: 'scoped_starting_slug',
          detail: 'cartridge_meta_scoped.starting_location_slug missing after apply',
        });
      }
      if (scopedStartingId == null) {
        blockers.push({
          step: 'scoped_starting_id',
          detail: 'cartridge_meta_scoped.starting_location_id missing after apply',
        });
      }
    }
    out['cartridgeId'] = cartridgeId;
    out['contentHash'] = contentHash;

    // ── 8. Create hero ───────────────────────────────────────────
    let heroEntityId: number | null = null;
    let heroPublicId: string | null = null;
    if (blockers.length === 0 && cartridgeId) {
      const createHeroRes = await app.request('/api/heroes', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({displayName: 'Engine Baseline Smoke'}),
      });
      if (createHeroRes.status !== 200) {
        blockers.push({
          step: 'create_hero',
          detail: `expected 200, got ${createHeroRes.status}`,
        });
      }
      const heroBody = (await createHeroRes.json()) as {
        player: {entity_id: number; public_id: string; display_name: string};
        clearClientCache: {keys: string[]; playerPublicId: string};
      };
      heroEntityId = heroBody.player?.entity_id ?? null;
      heroPublicId = heroBody.player?.public_id ?? null;
      out['hero'] = {
        entity_id: heroEntityId,
        public_id: heroPublicId,
        display_name: heroBody.player?.display_name,
        clearKeys: heroBody.clearClientCache?.keys ?? [],
      };
      if (!heroEntityId) {
        blockers.push({step: 'create_hero', detail: 'no entity_id returned'});
      }
    }

    // ── 9. Playthrough preview ───────────────────────────────────
    if (blockers.length === 0 && cartridgeId && heroEntityId) {
      const previewBody = {playerId: heroEntityId, cartridgeId};
      const ptPreviewRes = await app.request('/api/playthroughs/preview', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify(previewBody),
      });
      const ptPreview = (await ptPreviewRes.json()) as {
        mode: string;
        installReady: boolean;
        blockers: string[];
        startingLocationName: string | null;
        startingLocationId: number | null;
      };
      out['playthroughPreview'] = ptPreview;
      if (ptPreviewRes.status !== 200) {
        blockers.push({
          step: 'playthrough_preview',
          detail: `expected 200, got ${ptPreviewRes.status}`,
        });
      } else if (ptPreview.mode === 'repair_required') {
        blockers.push({
          step: 'playthrough_preview',
          detail: `mode=repair_required blockers=${ptPreview.blockers.join(',')}`,
        });
      }

      // ── 10. Launch ───────────────────────────────────────────────
      if (blockers.length === 0) {
        const launchRes = await app.request('/api/playthroughs/launch', {
          method: 'POST',
          headers: {'Content-Type': 'application/json'},
          body: JSON.stringify(previewBody),
        });
        const launch = (await launchRes.json()) as {
          cartridgeId: string;
          playthroughId: string;
          mode: string;
          resetGeneration: number;
          currentLocationId: number | null;
          currentLocationName: string | null;
        };
        out['launch'] = launch;
        if (launchRes.status !== 200) {
          blockers.push({
            step: 'launch',
            detail: `expected 200, got ${launchRes.status}`,
          });
        }

        // ── 11. Pre-new-game snapshot ────────────────────────────────
        const preNewGame = await snapshotCounts();
        out['preNewGameCounts'] = preNewGame;

        // ── 12. New game ─────────────────────────────────────────────
        const newGameRes = await app.request('/api/playthroughs/new-game', {
          method: 'POST',
          headers: {'Content-Type': 'application/json'},
          body: JSON.stringify(previewBody),
        });
        const newGame = (await newGameRes.json()) as {
          cartridgeId: string;
          playthroughId: string;
          mode: string;
          resetGeneration: number;
          currentLocationId: number | null;
          currentLocationName: string | null;
        };
        out['newGame'] = newGame;
        if (newGameRes.status !== 200) {
          blockers.push({
            step: 'new_game',
            detail: `expected 200, got ${newGameRes.status}`,
          });
        }
        if (newGame.playthroughId === launch.playthroughId) {
          blockers.push({
            step: 'new_game_playthrough_id',
            detail: 'new-game returned the same playthrough_id as launch',
          });
        }
        if (newGame.resetGeneration !== launch.resetGeneration + 1) {
          blockers.push({
            step: 'new_game_reset_generation',
            detail: `expected reset_generation ${launch.resetGeneration + 1}, got ${newGame.resetGeneration}`,
          });
        }

        // ── 13. Post-new-game snapshot — assert no reimport ──────────
        const postNewGame = await snapshotCounts();
        out['postNewGameCounts'] = postNewGame;
        if (postNewGame.cartridge_import_preview_jobs !== preNewGame.cartridge_import_preview_jobs) {
          blockers.push({
            step: 'new_game_no_preview',
            detail: `cartridge_import_preview_jobs changed across new-game: ${preNewGame.cartridge_import_preview_jobs} -> ${postNewGame.cartridge_import_preview_jobs}`,
          });
        }
        if (postNewGame.cartridge_import_runs !== preNewGame.cartridge_import_runs) {
          blockers.push({
            step: 'new_game_no_import_run',
            detail: `cartridge_import_runs changed across new-game: ${preNewGame.cartridge_import_runs} -> ${postNewGame.cartridge_import_runs}`,
          });
        }
        if (postNewGame.entities !== preNewGame.entities) {
          blockers.push({
            step: 'new_game_entities_preserved',
            detail: `entities count changed across new-game: ${preNewGame.entities} -> ${postNewGame.entities}`,
          });
        }
        if (postNewGame.cartridge_records !== preNewGame.cartridge_records) {
          blockers.push({
            step: 'new_game_records_preserved',
            detail: `cartridge_records changed across new-game: ${preNewGame.cartridge_records} -> ${postNewGame.cartridge_records}`,
          });
        }
      }
    }

    await closeDb().catch(() => {});
  } catch (err) {
    blockers.push({
      step: 'unexpected',
      detail: err instanceof Error ? `${err.name}: ${err.message}` : String(err),
    });
  } finally {
    try {
      process.chdir(originalCwd);
    } catch {
      // best-effort; the smoke run is exiting anyway.
    }
    if (!args.keepTemp) {
      if (existsSync(dbDir)) {
        await rm(dbDir, {recursive: true, force: true}).catch(() => {});
      }
      if (vaultDir && existsSync(vaultDir)) {
        await rm(vaultDir, {recursive: true, force: true}).catch(() => {});
      }
    }
  }

  const finishedAt = new Date();
  out['finishedAt'] = finishedAt.toISOString();
  out['durationMs'] = finishedAt.getTime() - startedAt.getTime();
  out['blockers'] = blockers;
  out['passed'] = blockers.length === 0;

  writeFileSync(
    path.join(args.outDir, 'result.json'),
    JSON.stringify(out, null, 2),
  );

  if (out['passed']) {
    process.stderr.write(
      `[engine-baseline-cartridge-smoke] PASS — result=${path.join(args.outDir, 'result.json')}\n`,
    );
    return 0;
  }
  process.stderr.write(
    `[engine-baseline-cartridge-smoke] FAIL — blockers: ${JSON.stringify(blockers)}\n`,
  );
  return 1;
}

const isDirect = process.argv[1]
  ? path.resolve(process.argv[1]) === path.resolve(FILE)
  : false;
if (isDirect) {
  main(process.argv.slice(2)).then(
    (code) => process.exit(code),
    (err) => {
      console.error('[engine-baseline-cartridge-smoke] FATAL', err);
      process.exit(1);
    },
  );
}

export {main as runEngineBaselineCartridgeSmoke};
