/**
 * @license
 * Copyright 2026 Greenhaven contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference lib="dom" />

// FEAT-HERO-CONTINUITY-6 — stable cross-world hero continuity smoke.
//
// Drives the production-built `packages/web-ui/dist` against a temp
// PGlite running the clean engine baseline. The smoke imports two
// distinct tiny Obsidian vaults through the Worlds & Heroes GUI,
// creates one hero, launches into cartridge A, seeds hero core +
// portable companion + world-bound control through direct DB writes
// (no GUI exists for those mutations yet), then drives the GUI through
// A → B → A and asserts:
//
//   1. Hero core (level/XP/portable artifact) survives both launches.
//   2. The portable companion materializes in B's universe as a
//      `dynamic_origin=true` projection entity, cartridge_id=B, with
//      status='following', and the capsule slices (stats / strings
//      toward hero / about-hero memories / non-companion statuses)
//      are present on the projection.
//   3. The source-world-only profile reference (`home_id`) is
//      sanitized away from the projection.
//   4. The world-bound bond does NOT spawn a B projection and is
//      reported as a `world_bound` outcome in the launch event.
//   5. The A-local quest entity has no twin in B's cartridge scope.
//   6. On return to A, the live `players.metadata.companions` roster
//      restores the original A source ids.
//
// Failure surfaces: blocker list in `result.json`, JSON in
// `summary.json`, DB count snapshots, network/console JSONL logs,
// screenshots. Exits 1 on any blocker.
//
// CLI:
//   --out <dir>          override result/log output dir.
//   --port <n>           backend port (default 7813).
//   --keep-temp          keep temp PGlite + vault dirs.
//   --timeout-ms <n>     hard ceiling. Default 600_000.

import {chromium, type ConsoleMessage, type Request, type Response} from 'playwright';
import {
  appendFileSync,
  existsSync,
  mkdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import {mkdir, mkdtemp, rm, writeFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const FILE = fileURLToPath(import.meta.url);
const REPO_ROOT = path.resolve(path.dirname(FILE), '..', '..', '..', '..');
const DEFAULT_OUT = path.join(
  REPO_ROOT,
  '.codex',
  'run-logs',
  'live-playtest',
  'hero-continuity-smoke',
);
const DEFAULT_UI_DIST = path.join(REPO_ROOT, 'packages', 'web-ui', 'dist');

interface Args {
  out: string;
  port: number;
  keepTemp: boolean;
  timeoutMs: number;
}

interface SmokeStep {
  name: string;
  status: 'ok' | 'failed';
  details?: Record<string, unknown>;
  error?: string;
}

function parseArgs(argv: string[]): Args {
  let out = DEFAULT_OUT;
  let port = 7813;
  let keepTemp = false;
  let timeoutMs = 600_000;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--out') out = argv[++i] ?? out;
    else if (arg === '--port') port = Number(argv[++i] ?? port) || port;
    else if (arg === '--keep-temp') keepTemp = true;
    else if (arg === '--timeout-ms')
      timeoutMs = Number(argv[++i] ?? timeoutMs) || timeoutMs;
  }
  return {out, port, keepTemp, timeoutMs};
}

async function waitForHealthy(base: string, attempts = 30): Promise<boolean> {
  for (let i = 0; i < attempts; i++) {
    try {
      const r = await fetch(`${base}/api/health`);
      if (r.ok) return true;
    } catch {
      // booting
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  return false;
}

// Distinct tiny vault generator. Vault A and vault B must produce
// distinct cartridge content hashes — different manifest titles,
// starting-location names, and body text are enough.
async function generateVault(
  suffix: string,
  manifestTitle: string,
  locationFolder: string,
  locationFile: string,
  locationLink: string,
  bodyLines: readonly string[],
): Promise<string> {
  const dir = await mkdtemp(
    path.join(os.tmpdir(), `hero-continuity-smoke-${suffix}-`),
  );
  const locDir = path.join(dir, 'GreenHavenWorld', 'Locations', locationFolder);
  await mkdir(locDir, {recursive: true});
  const manifest = [
    `# ${manifestTitle}`,
    '',
    'Generated by `live:hero-continuity` smoke.',
    '',
    '## Start of the game',
    '',
    'Starting location:',
    `[[${locationLink}|${locationFolder.replace(/^@/, '')}]]`,
    '',
  ].join('\n');
  await writeFile(path.join(dir, 'WORLD_MANIFEST.md'), manifest, 'utf8');
  await writeFile(path.join(locDir, locationFile), bodyLines.join('\n'), 'utf8');
  return dir;
}

const VAULT_A_BODY = [
  '# @Hearth Landing',
  '',
  '@Hearth Landing is a wind-warmed stone landing crowning a quiet city.',
  'The world feels familiar here. The hearth in the corner is always lit.',
  '',
  '## Canon',
  '',
  '- Parent area: none — entry point of cartridge A.',
  '- Visibility: open from the first turn.',
  '- Tone: warm, settled, calm.',
  '- Smoke fixture: yes (hero-continuity A vault).',
  '',
];

const VAULT_B_BODY = [
  '# @Pale Garden',
  '',
  '@Pale Garden is a tiered glasshouse perched above another city entirely.',
  'The air here is sharper, the light thinner. Nothing of A is in B.',
  '',
  '## Canon',
  '',
  '- Parent area: none — entry point of cartridge B.',
  '- Visibility: open from the first turn.',
  '- Tone: cold, lucid, foreign.',
  '- Smoke fixture: yes (hero-continuity B vault).',
  '',
];

async function main(argv: string[]): Promise<number> {
  const args = parseArgs(argv);
  const startedAt = new Date();
  const outDir = path.resolve(args.out);
  mkdirSync(outDir, {recursive: true});
  const screenshots = path.join(outDir, 'screenshots');
  mkdirSync(screenshots, {recursive: true});

  for (const name of [
    'summary.json',
    'result.json',
    'console-log.jsonl',
    'network-log.jsonl',
    'snapshots.json',
  ]) {
    const p = path.join(outDir, name);
    if (existsSync(p)) rmSync(p);
  }

  const dbDir = await mkdtemp(
    path.join(os.tmpdir(), 'hero-continuity-smoke-db-'),
  );
  process.env.PGLITE_DATA_DIR = dbDir;
  process.env.GEMINI_WEB_PORT = String(args.port);
  process.env.GREENHAVEN_WEB_UI_DIST = DEFAULT_UI_DIST;
  process.env.AUTH_DISABLED = '1';
  process.env.AUTH_SECRET =
    'hero-continuity-smoke-not-real-secret-32-bytes-or-more-XX';
  process.env.GREENHAVEN_DEBUG_ROUTES = '1';
  process.env.GREENHAVEN_DEBUG_KEY = 'codex-hero-continuity-smoke-debug-key';
  process.env.FEATHERLESS_API_KEY = 'smoke-not-real-key';
  process.env.NODE_ENV = 'development';
  process.env.GREENHAVEN_GAMEPLAY_LOG_DIR = path.join(outDir, 'gameplay-logs');

  const originalCwd = process.cwd();
  process.chdir(REPO_ROOT);

  const steps: SmokeStep[] = [];
  const blockers: string[] = [];
  const snapshots: Record<string, unknown> = {};
  const record = (step: SmokeStep) => {
    steps.push(step);
    process.stderr.write(
      `[hero-continuity-smoke] ${step.status.padEnd(6)} ${step.name}` +
        (step.error ? ` — ${step.error}` : '') +
        '\n',
    );
  };
  const logBlocker = (name: string, msg: string) => {
    record({name, status: 'failed', error: msg});
    blockers.push(`${name}: ${msg}`);
  };

  const {startGreenhavenServer, stopGreenhavenServer} = await import(
    '../index.js'
  );
  const dbModule = await import('../db.js');

  const vaultA = await generateVault(
    'a',
    'Hearth A',
    '@Hearth Landing',
    'HearthLandingMind.md',
    'HearthLandingMind',
    VAULT_A_BODY,
  );
  const vaultB = await generateVault(
    'b',
    'Pale B',
    '@Pale Garden',
    'PaleGardenMind.md',
    'PaleGardenMind',
    VAULT_B_BODY,
  );
  const cleanupVaults = [vaultA, vaultB];

  const server = await startGreenhavenServer({
    port: args.port,
    hostname: '127.0.0.1',
  });
  const base = server.url;

  let cleanupRan = false;
  const cleanup = async () => {
    if (cleanupRan) return;
    cleanupRan = true;
    try {
      await stopGreenhavenServer(server);
    } catch (err) {
      console.warn('[hero-continuity-smoke] stopGreenhavenServer failed', err);
    }
    try {
      process.chdir(originalCwd);
    } catch {
      // best-effort
    }
    if (!args.keepTemp) {
      await rm(dbDir, {recursive: true, force: true}).catch(() => {});
      for (const v of cleanupVaults) {
        await rm(v, {recursive: true, force: true}).catch(() => {});
      }
    }
  };

  const finish = async (): Promise<number> => {
    const finishedAt = new Date();
    const ok = blockers.length === 0;
    const summary = {
      ok,
      startedAt: startedAt.toISOString(),
      finishedAt: finishedAt.toISOString(),
      durationMs: finishedAt.getTime() - startedAt.getTime(),
      outDir,
      steps,
      blockers,
    };
    writeFileSync(
      path.join(outDir, 'summary.json'),
      JSON.stringify(summary, null, 2),
    );
    writeFileSync(
      path.join(outDir, 'result.json'),
      JSON.stringify({passed: ok, blockers, steps}, null, 2),
    );
    writeFileSync(
      path.join(outDir, 'snapshots.json'),
      JSON.stringify(snapshots, null, 2),
    );
    await cleanup();
    return ok ? 0 : 1;
  };

  const timeoutHandle = setTimeout(() => {
    logBlocker('timeout', `smoke exceeded ${args.timeoutMs}ms`);
    void finish().then((code) => process.exit(code));
  }, args.timeoutMs);
  timeoutHandle.unref?.();

  try {
    if (!(await waitForHealthy(base))) {
      logBlocker('bootstrap', '/api/health never returned ok=true');
      return await finish();
    }
    record({name: 'bootstrap_backend', status: 'ok'});

    // ── 1. Boot Chromium and helper functions ────────────────────
    const browser = await chromium.launch({headless: true});
    const context = await browser.newContext({viewport: {width: 1400, height: 900}});
    const page = await context.newPage();

    const consoleLogPath = path.join(outDir, 'console-log.jsonl');
    const networkLogPath = path.join(outDir, 'network-log.jsonl');
    let teardownStarted = false;
    const consoleErrors: Array<{type: string; text: string}> = [];
    const failedRequests: Array<{url: string; failure: string}> = [];
    const serverErrors: Array<{url: string; status: number}> = [];
    page.on('console', (msg: ConsoleMessage) => {
      appendFileSync(
        consoleLogPath,
        JSON.stringify({type: msg.type(), text: msg.text(), ts: Date.now()}) +
          '\n',
      );
      if (msg.type() === 'error' && !teardownStarted) {
        consoleErrors.push({type: msg.type(), text: msg.text()});
      }
    });
    page.on('requestfailed', (req: Request) => {
      const failure = req.failure()?.errorText ?? 'unknown';
      appendFileSync(
        networkLogPath,
        JSON.stringify({
          phase: 'requestfailed',
          url: req.url(),
          method: req.method(),
          failure,
          ts: Date.now(),
        }) + '\n',
      );
      if (teardownStarted) return;
      if (failure.includes('ERR_ABORTED')) return;
      failedRequests.push({url: req.url(), failure});
    });
    page.on('response', (res: Response) => {
      const url = res.url();
      const status = res.status();
      if (status >= 400) {
        appendFileSync(
          networkLogPath,
          JSON.stringify({phase: 'response', url, status, ts: Date.now()}) +
            '\n',
        );
        if (!teardownStarted) serverErrors.push({url, status});
      }
    });
    await context.addInitScript(() => {
      try {
        window.localStorage.setItem('greenhaven.uiLanguage', 'en');
      } catch {
        // ignore
      }
    });
    page.on('dialog', (dialog) => {
      appendFileSync(
        networkLogPath,
        JSON.stringify({
          phase: 'dialog',
          type: dialog.type(),
          message: dialog.message(),
          ts: Date.now(),
        }) + '\n',
      );
      void dialog.accept();
    });

    const enterWorldsHeroes = async (): Promise<void> => {
      await page.waitForSelector('.title-screen', {timeout: 15000});
      await page.waitForTimeout(150);
      await page.keyboard.press('Space');
      await Promise.race([
        page.waitForSelector('.cart-lib', {timeout: 30000}),
        page.waitForSelector('.title-menu', {timeout: 30000}),
      ]);
      if (
        await page
          .locator('.title-menu')
          .isVisible({timeout: 100})
          .catch(() => false)
      ) {
        await page.evaluate(() => {
          const buttons = Array.from(
            document.querySelectorAll('.title-menu__btn'),
          ) as HTMLButtonElement[];
          const wh = buttons.find((b) => {
            const t = (b.textContent ?? '').toLowerCase();
            return t.includes('worlds') || t.includes('миры');
          });
          wh?.click();
        });
        await page.waitForSelector('.cart-lib', {timeout: 15000});
      }
    };

    const importVault = async (vaultPath: string): Promise<void> => {
      const headerClicked = await page.evaluate(() => {
        const buttons = Array.from(
          document.querySelectorAll('.cart-lib__head .cart-lib__btn'),
        ) as HTMLButtonElement[];
        const btn = buttons.find((b) =>
          (b.textContent ?? '').toLowerCase().includes('import world'),
        );
        if (!btn) return false;
        btn.click();
        return true;
      });
      if (!headerClicked) {
        throw new Error('"+ Import world…" button not found');
      }
      await page.waitForSelector('.cart-lib__wizard', {timeout: 10000});
      await page
        .locator('.cart-lib__wizard select')
        .selectOption('obsidian_vault');
      await page.locator('.cart-lib__wizard input[type="text"]').fill(vaultPath);
      await page.evaluate(() => {
        const buttons = Array.from(
          document.querySelectorAll('.cart-lib__wizard-foot .cart-lib__btn'),
        ) as HTMLButtonElement[];
        const primary = buttons.find((b) =>
          b.classList.contains('cart-lib__btn--primary'),
        );
        primary?.click();
      });
      const result = await page
        .waitForFunction(
          () => {
            const ddNodes = Array.from(
              document.querySelectorAll('.cart-lib__wizard-status dd'),
            ) as HTMLElement[];
            if (ddNodes.length === 0) return false;
            const status = ddNodes[0]?.textContent?.toLowerCase() ?? '';
            if (status.includes('failed')) return 'failed';
            if (status.includes('ready')) return 'ready';
            return false;
          },
          undefined,
          {timeout: 90000},
        )
        .then((handle) => handle.jsonValue())
        .catch(() => 'timeout');
      if (result !== 'ready') {
        throw new Error(`preview reached '${String(result)}' instead of ready`);
      }
      await page.evaluate(() => {
        const buttons = Array.from(
          document.querySelectorAll('.cart-lib__wizard-foot .cart-lib__btn'),
        ) as HTMLButtonElement[];
        const primary = buttons.find((b) =>
          b.classList.contains('cart-lib__btn--primary'),
        );
        primary?.click();
      });
      await page.waitForSelector('.cart-lib__wizard', {
        state: 'detached',
        timeout: 60000,
      });
    };

    const selectHeroAndCartridge = async (
      heroName: string,
      cartridgeId: string,
    ): Promise<void> => {
      // Hero column
      await page.evaluate((name: string) => {
        const cols = Array.from(document.querySelectorAll('.cart-lib__col'));
        const heroesCol = cols.find((col) => {
          const heading = col.querySelector('.cart-lib__col-heading');
          return (heading?.textContent ?? '').toLowerCase().includes('hero');
        });
        const cards = Array.from(
          heroesCol?.querySelectorAll('.cart-lib__card') ?? [],
        ) as HTMLButtonElement[];
        const target = cards.find((c) =>
          (c.textContent ?? '').includes(name),
        );
        target?.click();
      }, heroName);
      // World column — match by the FEAT-HERO-CONTINUITY-6 stable
      // `data-cartridge-id` attribute the GUI emits on each card. The
      // smoke fails fast if the attribute is missing rather than
      // silently falling back to a different cartridge.
      const clicked = await page.evaluate((id: string) => {
        const target = document.querySelector(
          `.cart-lib__list .cart-lib__card[data-cartridge-id="${CSS.escape(id)}"]`,
        ) as HTMLButtonElement | null;
        if (!target) return false;
        target.click();
        return true;
      }, cartridgeId);
      if (!clicked) {
        throw new Error(
          `no .cart-lib__card[data-cartridge-id="${cartridgeId}"] found in Worlds column`,
        );
      }
      // Wait for Launch to enable
      await page
        .waitForFunction(
          () => {
            const launch = Array.from(
              document.querySelectorAll('.cart-lib__actions .cart-lib__btn'),
            ).find((b) => {
              const text = (b.textContent ?? '').toLowerCase();
              return text.includes('launch') || text.includes('enter');
            }) as HTMLButtonElement | undefined;
            return launch != null && !launch.disabled;
          },
          undefined,
          {timeout: 20000},
        )
        .catch(() => {
          throw new Error(
            `launch button never enabled for hero=${heroName} cart=${cartridgeId}`,
          );
        });
    };

    const clickLaunch = async (): Promise<void> => {
      await page.evaluate(() => {
        const launch = Array.from(
          document.querySelectorAll('.cart-lib__actions .cart-lib__btn'),
        ).find((b) => {
          const text = (b.textContent ?? '').toLowerCase();
          return text.includes('launch') || text.includes('enter');
        }) as HTMLButtonElement | undefined;
        launch?.click();
      });
      const reached = await Promise.race([
        page.waitForSelector('main.game-shell', {timeout: 30000}).then(() => 'game-shell'),
        page.waitForSelector('.creator-overlay', {timeout: 30000}).then(() => 'creator-overlay'),
      ]).catch(() => null);
      if (!reached) {
        throw new Error('neither main.game-shell nor .creator-overlay rendered after Launch');
      }
    };

    // ── 2. Empty library → import vault A ────────────────────────
    await page.goto(base, {waitUntil: 'domcontentloaded', timeout: 30000});
    await enterWorldsHeroes();
    await page.screenshot({
      path: path.join(screenshots, '01-empty-library.png'),
      fullPage: true,
    });
    // Vault A keeps the compiler's default cartridge id (grinhaven-full).
    delete process.env.GREENHAVEN_FORGE_TARGET_CARTRIDGE_ID;
    await importVault(vaultA);
    await page.screenshot({
      path: path.join(screenshots, '02-after-vault-a.png'),
      fullPage: true,
    });
    record({name: 'imported_vault_a', status: 'ok'});

    // ── 3. Import vault B (still on Worlds & Heroes) ─────────────
    // FEAT-HERO-CONTINUITY-6 — override the compiler's hardcoded
    // `target_cartridge_id` so vault B lands as a distinct cartridge
    // row rather than colliding with vault A. Production Obsidian
    // imports leave the env var unset and keep the default id.
    process.env.GREENHAVEN_FORGE_TARGET_CARTRIDGE_ID = 'pale-garden-b';
    await importVault(vaultB);
    delete process.env.GREENHAVEN_FORGE_TARGET_CARTRIDGE_ID;
    await page.screenshot({
      path: path.join(screenshots, '03-after-vault-b.png'),
      fullPage: true,
    });
    record({name: 'imported_vault_b', status: 'ok'});

    const cartridgeRows = await dbModule.query<{
      id: string;
      installed_at: string;
    }>(`SELECT id, installed_at FROM cartridges WHERE id != 'greenhaven-noir' ORDER BY installed_at ASC`);
    if (cartridgeRows.rows.length !== 2) {
      logBlocker(
        'two_cartridges_installed',
        `expected 2 imported cartridges, got ${cartridgeRows.rows.length}`,
      );
      return await finish();
    }
    const cartridgeAId = String(cartridgeRows.rows[0]!.id);
    const cartridgeBId = String(cartridgeRows.rows[1]!.id);
    snapshots.cartridgeAId = cartridgeAId;
    snapshots.cartridgeBId = cartridgeBId;
    record({
      name: 'two_cartridges_installed',
      status: 'ok',
      details: {a: cartridgeAId, b: cartridgeBId},
    });

    // ── 4. B's continuity policy must accept portable contracts ──
    // Without this, the carryover service classifies the bond as
    // `suppressed (target_policy_disallows_portable_contracts)`.
    await dbModule.query(
      `INSERT INTO cartridge_meta_scoped (cartridge_id, key, value)
       VALUES ($1, 'hero_continuity_policy', $2::jsonb)
       ON CONFLICT (cartridge_id, key)
       DO UPDATE SET value = EXCLUDED.value`,
      [
        cartridgeBId,
        JSON.stringify({
          schema_version: 'greenhaven.hero_continuity_policy.v1',
          carry: {
            xp_level: 'visible',
            titles: 'visible',
            companions: 'portable_contracts',
          },
        }),
      ],
    );
    record({name: 'configured_b_policy', status: 'ok'});

    // ── 5. Create hero ───────────────────────────────────────────
    await page.evaluate(() => {
      const btn = Array.from(
        document.querySelectorAll('.cart-lib__btn'),
      ).find((b) =>
        (b.textContent ?? '').toLowerCase().includes('create hero'),
      ) as HTMLButtonElement | undefined;
      btn?.click();
    });

    // Wait for the main premium hero creator screen to be mounted
    await page.waitForSelector('.hero-creator-screen', {timeout: 10000});

    // Wait for the character creator overlay/wizard interface to be ready
    await page.waitForSelector('.creator-overlay', {timeout: 15000});

    const heroName = 'Hero Continuity Smoke';

    // Step I: Threshold (Name)
    await page.locator('.creator-step.threshold input[type="text"]').fill(heroName);
    await page.click('.creator-page-footer button.next');

    // Step II: Form (Description)
    await page.waitForSelector('.creator-step.form', {timeout: 5000});
    await page.locator('.creator-step.form textarea').fill('Pale hands, a quiet city shadow, speaks slow when sober.');
    await page.click('.creator-page-footer button.next');

    // Step III: Past (History)
    await page.waitForSelector('.creator-step.past', {timeout: 5000});
    await page.locator('.creator-step.past textarea').fill('Carried a heavy leather-bound ledger from the old world.');
    await page.click('.creator-page-footer button.next');

    // Step IV: Synthesis Intro (Click Bind the Page)
    await page.waitForSelector('.creator-step.synthesis.intro', {timeout: 5000});
    await page.click('button.creator-bind');

    // Step V: Synthesis Review (Wait for synthesis, then click final commit button)
    await page.waitForSelector('button.creator-sign-button', {timeout: 30000});
    await page.click('button.creator-sign-button');

    // Wait for the entire creator screen to finish and close
    await page.waitForSelector('.hero-creator-screen', {
      state: 'detached',
      timeout: 15000,
    });

    const heroRow = await dbModule.query<{entity_id: number}>(
      `SELECT entity_id FROM players ORDER BY entity_id DESC LIMIT 1`,
    );
    const heroId = Number(heroRow.rows[0]?.entity_id ?? 0);
    snapshots.heroId = heroId;
    if (!heroId) {
      logBlocker('hero_created', 'hero player row missing after Create Hero');
      return await finish();
    }
    record({name: 'hero_created', status: 'ok', details: {heroId}});

    // Mark profile created so launches don't bounce to character creator
    const patchProfile = await fetch(
      `${base}/api/player/${heroId}/profile`,
      {
        method: 'PATCH',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({created: true}),
      },
    );
    if (patchProfile.status !== 200) {
      logBlocker(
        'patch_profile_created',
        `PATCH profile returned ${patchProfile.status}`,
      );
    }

    // ── 6. Reload → select hero + A → Launch ─────────────────────
    await page.reload({waitUntil: 'domcontentloaded'});
    await enterWorldsHeroes();
    await page.waitForSelector('.cart-lib__list .cart-lib__card', {
      timeout: 10000,
    });
    await selectHeroAndCartridge(heroName, cartridgeAId);
    await page.screenshot({
      path: path.join(screenshots, '04-preview-a.png'),
      fullPage: true,
    });
    await clickLaunch();
    await page.screenshot({
      path: path.join(screenshots, '05-after-launch-a.png'),
      fullPage: true,
    });
    record({name: 'launched_a_first_time', status: 'ok'});

    // ── 7. Seed hero core + portable companion + world-bound in A
    // Award progression on players row (level 5, +1500 xp).
    await dbModule.query(
      `UPDATE players
          SET current_level = 5,
              current_xp = 1500
        WHERE entity_id = $1`,
      [heroId],
    );
    // Hero portable artifact: an equipped title that should survive
    // both launches.
    await dbModule.query(
      `INSERT INTO hero_portable_artifacts
         (player_id, artifact_key, kind, portability, source_cartridge_id, power_rating, payload)
       VALUES ($1, 'title:hearthwarden', 'title', 'portable', $2, 3, $3::jsonb)
       ON CONFLICT (player_id, artifact_key) DO NOTHING`,
      [
        heroId,
        cartridgeAId,
        JSON.stringify({
          display_name: 'Hearthwarden of Hearth Landing',
          awarded_in: cartridgeAId,
        }),
      ],
    );

    // Universe instance ids for A and B (the apply step created the
    // default `local_single_player` row per cartridge).
    const universeRows = await dbModule.query<{
      cartridge_id: string;
      id: string;
    }>(`SELECT cartridge_id, id FROM universe_instances WHERE is_default = true`);
    const universeA =
      universeRows.rows.find((r) => r.cartridge_id === cartridgeAId)?.id ??
      null;
    const universeB =
      universeRows.rows.find((r) => r.cartridge_id === cartridgeBId)?.id ??
      null;
    snapshots.universeAId = universeA;
    snapshots.universeBId = universeB;
    if (!universeA || !universeB) {
      logBlocker(
        'default_universe_instances',
        `missing default universe_instances rows: A=${universeA} B=${universeB}`,
      );
      return await finish();
    }

    // Seed A-local NPCs: portable companion + world-bound NPC.
    const portableRow = await dbModule.query<{id: number}>(
      `INSERT INTO entities (kind, display_name, summary, profile, cartridge_id, dynamic_origin)
       VALUES ('person', 'Mira of Hearth', 'A wandering apothecary the hero saved.',
               $1::jsonb, $2, false)
       RETURNING id`,
      [
        JSON.stringify({
          source_slug: 'companion:mira_of_hearth',
          persona_slug: 'apothecary',
          mood: 'watchful',
          voice: 'low and dry',
          oath: 'Pay back the debt to the hearth.',
          // Source-world-only references — should be sanitized away on
          // projection per the carryover sanitizer.
          home_id: 9991,
          current_location_id: 9991,
          home_location_id: 9991,
        }),
        cartridgeAId,
      ],
    );
    const portableEntityId = Number(portableRow.rows[0]!.id);

    const worldBoundRow = await dbModule.query<{id: number}>(
      `INSERT INTO entities (kind, display_name, summary, profile, cartridge_id, dynamic_origin)
       VALUES ('person', 'Old Reeve', 'A reeve sworn to never leave the hearth.',
               $1::jsonb, $2, false)
       RETURNING id`,
      [
        JSON.stringify({
          source_slug: 'companion:old_reeve',
          persona_slug: 'reeve',
          mood: 'duty-bound',
        }),
        cartridgeAId,
      ],
    );
    const worldBoundEntityId = Number(worldBoundRow.rows[0]!.id);

    // A-local quest (kind='quest'): proves quest entities stay in A's
    // cartridge scope; the hero may have player_quests row but B-scope
    // queries on entities should not see it.
    const questEntityRow = await dbModule.query<{id: number}>(
      `INSERT INTO entities (kind, display_name, summary, profile, cartridge_id)
       VALUES ('quest', 'Rescue the Hearth Cat',
               'A local quest that stays in A.',
               '{}'::jsonb, $1) RETURNING id`,
      [cartridgeAId],
    );
    const questEntityId = Number(questEntityRow.rows[0]!.id);
    await dbModule.query(
      `INSERT INTO player_quests (player_id, quest_entity_id, status, current_phase)
       VALUES ($1, $2, 'active', 1)
       ON CONFLICT (player_id, quest_entity_id) DO NOTHING`,
      [heroId, questEntityId],
    );

    // Companion-owned npc_stats (3 stats).
    for (const [statKey, value] of [
      ['empathy', 7],
      ['perception', 6],
      ['discipline', 5],
    ] as const) {
      await dbModule.query(
        `INSERT INTO npc_stats (npc_entity_id, stat_key, current, base)
         VALUES ($1, $2, $3, $3)
         ON CONFLICT (npc_entity_id, stat_key) DO UPDATE SET current = EXCLUDED.current`,
        [portableEntityId, statKey, value],
      );
    }

    // Companion's strings runtime field — sanitizer must keep only the
    // hero entry. The 9990 stranger id should NOT survive into B.
    const strangerId = 9990;
    const stringsField = await dbModule.query<{id: number}>(
      `INSERT INTO runtime_fields
         (owner_entity_id, field_key, value_type, default_value, scope)
       VALUES ($1, 'strings', 'json', '{}'::jsonb, 'permanent') RETURNING id`,
      [portableEntityId],
    );
    const stringsFieldId = Number(stringsField.rows[0]!.id);
    await dbModule.query(
      `INSERT INTO runtime_values (field_id, value, source)
       VALUES ($1, $2::jsonb, 'smoke_seed')`,
      [stringsFieldId, JSON.stringify({[String(heroId)]: 7, [String(strangerId)]: 4})],
    );

    // Non-`strings` runtime field that's safe — mood — should be copied.
    const moodField = await dbModule.query<{id: number}>(
      `INSERT INTO runtime_fields
         (owner_entity_id, field_key, value_type, default_value, scope)
       VALUES ($1, 'mood', 'string', '"calm"'::jsonb, 'permanent') RETURNING id`,
      [portableEntityId],
    );
    await dbModule.query(
      `INSERT INTO runtime_values (field_id, value, source)
       VALUES ($1, $2::jsonb, 'smoke_seed')`,
      [Number(moodField.rows[0]!.id), JSON.stringify('watchful')],
    );

    // Entity-ref runtime field that MUST be suppressed by the carryover
    // sanitizer because it could carry a source-world id into B.
    const homeRefField = await dbModule.query<{id: number}>(
      `INSERT INTO runtime_fields
         (owner_entity_id, field_key, value_type, default_value, scope)
       VALUES ($1, 'home_ref', 'entity_ref', 'null'::jsonb, 'permanent') RETURNING id`,
      [portableEntityId],
    );
    await dbModule.query(
      `INSERT INTO runtime_values (field_id, value, source)
       VALUES ($1, $2::jsonb, 'smoke_seed')`,
      [Number(homeRefField.rows[0]!.id), JSON.stringify(9991)],
    );

    // Companion-owned memory about the hero (must carry).
    // npc_memories schema: text is the single payload column, importance is REAL [0,1].
    await dbModule.query(
      `INSERT INTO npc_memories
         (owner_entity_id, about_entity_id, text, importance)
       VALUES ($1, $2, 'Hero pulled me from the well at first light. I owe him the rest of the night.', 0.7)`,
      [portableEntityId, heroId],
    );

    // Source-world-only memory anchored to the world-bound NPC. This
    // memory is NOT owned by the companion → must NOT be copied to B.
    await dbModule.query(
      `INSERT INTO npc_memories
         (owner_entity_id, about_entity_id, text, importance)
       VALUES ($1, $2, 'Old Reeve once vowed the hearth would never go cold.', 0.5)`,
      [worldBoundEntityId, heroId],
    );

    // Companion-owned inventory entry (an A-cartridge item with a stable
    // source_slug — the carryover service resolves through source_slug).
    const itemRow = await dbModule.query<{id: number}>(
      `INSERT INTO entities (kind, display_name, summary, profile, cartridge_id)
       VALUES ('item', 'Bone-Handled Knife', 'A small utility blade.',
               $1::jsonb, $2) RETURNING id`,
      [JSON.stringify({source_slug: 'item:bone_handled_knife'}), cartridgeAId],
    );
    const itemEntityId = Number(itemRow.rows[0]!.id);
    await dbModule.query(
      `INSERT INTO cartridge_records
         (cartridge_id, record_id, kind, slug, content_hash, imported_entity_id)
       VALUES ($1, 'item:bone_handled_knife', 'item',
               'item:bone_handled_knife', 'smoke_hash_a', $2)
       ON CONFLICT (cartridge_id, kind, slug) DO NOTHING`,
      [cartridgeAId, itemEntityId],
    );
    await dbModule.query(
      `INSERT INTO inventory_entries (holder_entity_id, item_entity_id, count)
       VALUES ($1, $2, 1)
       ON CONFLICT (holder_entity_id, item_entity_id) DO UPDATE SET count = EXCLUDED.count`,
      [portableEntityId, itemEntityId],
    );

    // Mirror that item into B's cartridge so the carryover resolver can
    // find a target equivalent via source_slug. The B-side item entity
    // must exist with the same `profile.source_slug` for the resolver
    // to map cleanly.
    const itemBRow = await dbModule.query<{id: number}>(
      `INSERT INTO entities (kind, display_name, summary, profile, cartridge_id)
       VALUES ('item', 'Bone-Handled Knife', 'B-cartridge twin.',
               $1::jsonb, $2) RETURNING id`,
      [JSON.stringify({source_slug: 'item:bone_handled_knife'}), cartridgeBId],
    );
    await dbModule.query(
      `INSERT INTO cartridge_records
         (cartridge_id, record_id, kind, slug, content_hash, imported_entity_id)
       VALUES ($1, 'item:bone_handled_knife', 'item',
               'item:bone_handled_knife', 'smoke_hash_b', $2)
       ON CONFLICT (cartridge_id, kind, slug) DO NOTHING`,
      [cartridgeBId, Number(itemBRow.rows[0]!.id)],
    );
    snapshots.bItemEntityId = Number(itemBRow.rows[0]!.id);

    // Actor statuses on companion: one `companion='following'` (will be
    // re-authored by the carryover) plus a non-companion status (mood)
    // that must travel under sanitization.
    await dbModule.query(
      `INSERT INTO actor_statuses (player_id, actor_entity_id, status_kind, status_value, metadata)
       VALUES ($1, $2, 'companion', 'following', '{}'::jsonb),
              ($1, $2, 'mood', 'watchful', $3::jsonb)`,
      [
        heroId,
        portableEntityId,
        JSON.stringify({since_turn: 12}),
      ],
    );

    // Update players.metadata.companions to include the companion id.
    await dbModule.query(
      `UPDATE players
          SET metadata = COALESCE(metadata, '{}'::jsonb)
                      || jsonb_build_object('companions', $1::jsonb)
        WHERE entity_id = $2`,
      [JSON.stringify([portableEntityId, worldBoundEntityId]), heroId],
    );

    // Hero companion bonds: 1 portable for the companion, 1 world-bound
    // for the reeve.
    await dbModule.query(
      `INSERT INTO hero_companion_bonds
         (player_id, companion_key, source_entity_id, source_universe_instance_id,
          source_cartridge_id, status, portability, public_summary)
       VALUES ($1, 'companion:mira_of_hearth', $2, $3::uuid, $4,
               'traveling', 'portable', 'Mira travels with the hero.')
       ON CONFLICT (player_id, companion_key) DO NOTHING`,
      [heroId, portableEntityId, universeA, cartridgeAId],
    );
    await dbModule.query(
      `INSERT INTO hero_companion_bonds
         (player_id, companion_key, source_entity_id, source_universe_instance_id,
          source_cartridge_id, status, portability, public_summary)
       VALUES ($1, 'companion:old_reeve', $2, $3::uuid, $4,
               'world_bound', 'local_locked', 'Reeve stays with the hearth.')
       ON CONFLICT (player_id, companion_key) DO NOTHING`,
      [heroId, worldBoundEntityId, universeA, cartridgeAId],
    );

    snapshots.portableEntityId = portableEntityId;
    snapshots.worldBoundEntityId = worldBoundEntityId;
    snapshots.questEntityId = questEntityId;
    snapshots.itemEntityIdA = itemEntityId;
    record({name: 'seeded_a_state', status: 'ok'});

    // Snapshot pre-A-departure hero state for later comparison.
    const heroBeforeB = await dbModule.query<{
      current_level: number | string;
      current_xp: number | string;
    }>(`SELECT current_level, current_xp FROM players WHERE entity_id = $1`, [
      heroId,
    ]);
    snapshots.heroBeforeBCore = heroBeforeB.rows[0];

    // ── 8. Launch into B (cross-world transfer) ──────────────────
    await page.reload({waitUntil: 'domcontentloaded'});
    await enterWorldsHeroes();
    await page.waitForSelector('.cart-lib__list .cart-lib__card', {
      timeout: 10000,
    });
    await selectHeroAndCartridge(heroName, cartridgeBId);
    await page.screenshot({
      path: path.join(screenshots, '06-preview-b.png'),
      fullPage: true,
    });
    await clickLaunch();
    await page.screenshot({
      path: path.join(screenshots, '07-after-launch-b.png'),
      fullPage: true,
    });
    record({name: 'launched_b_cross_world', status: 'ok'});

    // ── 9. Verify cross-world carryover in B ─────────────────────
    const heroAfterB = await dbModule.query<{
      current_level: number | string;
      current_xp: number | string;
    }>(`SELECT current_level, current_xp FROM players WHERE entity_id = $1`, [
      heroId,
    ]);
    snapshots.heroAfterBCore = heroAfterB.rows[0];
    if (
      Number(heroAfterB.rows[0]?.current_level) !== 5 ||
      Number(heroAfterB.rows[0]?.current_xp) !== 1500
    ) {
      logBlocker(
        'hero_core_carries_to_b',
        `expected lvl=5 xp=1500 in B, got ${JSON.stringify(heroAfterB.rows[0])}`,
      );
    } else {
      record({name: 'hero_core_carries_to_b', status: 'ok'});
    }

    // Portable artifact still present.
    const artifactRow = await dbModule.query<{c: number}>(
      `SELECT COUNT(*)::int AS c FROM hero_portable_artifacts
        WHERE player_id = $1 AND artifact_key = 'title:hearthwarden'`,
      [heroId],
    );
    if (Number(artifactRow.rows[0]?.c ?? 0) !== 1) {
      logBlocker(
        'portable_artifact_in_b',
        `expected 1 hearthwarden artifact row, got ${artifactRow.rows[0]?.c}`,
      );
    } else {
      record({name: 'portable_artifact_in_b', status: 'ok'});
    }

    // Companion projection materialized in B.
    const projRow = await dbModule.query<{
      projection_entity_id: number | null;
      status: string;
      arrival_payload: unknown;
    }>(
      `SELECT projection_entity_id, status, arrival_payload
         FROM companion_universe_projections
        WHERE universe_instance_id = $1::uuid`,
      [universeB],
    );
    if (projRow.rows.length !== 1) {
      logBlocker(
        'projection_count_in_b',
        `expected exactly 1 projection in B universe, got ${projRow.rows.length}`,
      );
    }
    const projection = projRow.rows[0];
    const projectionEntityId = Number(projection?.projection_entity_id ?? 0);
    snapshots.projectionEntityId = projectionEntityId;
    snapshots.projectionArrival = projection?.arrival_payload;
    if (!projectionEntityId) {
      logBlocker(
        'projection_entity_set',
        'companion_universe_projections.projection_entity_id is null',
      );
    }
    if (projection?.status !== 'following') {
      logBlocker(
        'projection_status_following',
        `expected status=following, got ${projection?.status}`,
      );
    }

    // Projection entity attributes: kind='person', cartridge_id=B,
    // dynamic_origin=true, profile sanitized (no home_id /
    // current_location_id / home_location_id).
    const projEntityRow = await dbModule.query<{
      kind: string;
      cartridge_id: string | null;
      dynamic_origin: boolean;
      profile: Record<string, unknown>;
    }>(
      `SELECT kind, cartridge_id, dynamic_origin, profile
         FROM entities WHERE id = $1`,
      [projectionEntityId],
    );
    const projEntity = projEntityRow.rows[0];
    snapshots.projectionEntity = projEntity;
    if (projEntity?.kind !== 'person') {
      logBlocker(
        'projection_entity_kind',
        `expected projection kind=person, got ${projEntity?.kind}`,
      );
    }
    if (projEntity?.cartridge_id !== cartridgeBId) {
      logBlocker(
        'projection_entity_cartridge',
        `expected projection cartridge_id=${cartridgeBId}, got ${projEntity?.cartridge_id}`,
      );
    }
    if (projEntity?.dynamic_origin !== true) {
      logBlocker(
        'projection_dynamic_origin',
        `expected dynamic_origin=true, got ${projEntity?.dynamic_origin}`,
      );
    }
    const profile = (projEntity?.profile ?? {}) as Record<string, unknown>;
    for (const denyKey of ['home_id', 'current_location_id', 'home_location_id']) {
      if (denyKey in profile) {
        logBlocker(
          'projection_profile_sanitized',
          `denied key '${denyKey}' survived into projection profile`,
        );
      }
    }
    if (
      profile.mood !== 'watchful' ||
      profile.voice !== 'low and dry' ||
      profile.persona_slug !== 'apothecary'
    ) {
      logBlocker(
        'projection_profile_safe_carry',
        `safe keys missing from projection profile: ${JSON.stringify(profile)}`,
      );
    }
    if (!blockers.some((b) => b.startsWith('projection_'))) {
      record({name: 'projection_entity_safe', status: 'ok'});
    }

    // Projection actor status row.
    const actorStatusRows = await dbModule.query<{
      status_kind: string;
      status_value: string;
    }>(
      `SELECT status_kind, status_value
         FROM actor_statuses
        WHERE player_id = $1 AND actor_entity_id = $2
        ORDER BY status_kind`,
      [heroId, projectionEntityId],
    );
    snapshots.projectionStatuses = actorStatusRows.rows;
    const hasFollowing = actorStatusRows.rows.some(
      (r) => r.status_kind === 'companion' && r.status_value === 'following',
    );
    const hasMood = actorStatusRows.rows.some(
      (r) => r.status_kind === 'mood' && r.status_value === 'watchful',
    );
    if (!hasFollowing) {
      logBlocker(
        'projection_following_status',
        'actor_statuses missing companion=following on projection',
      );
    }
    if (!hasMood) {
      logBlocker(
        'projection_mood_status_carried',
        'non-companion status (mood=watchful) did not carry to projection',
      );
    }
    if (hasFollowing && hasMood) {
      record({name: 'projection_statuses_applied', status: 'ok'});
    }

    // Projection's `strings` runtime field must contain only the hero
    // entry (foreign stranger id 9990 dropped).
    const projStringsRow = await dbModule.query<{value: unknown}>(
      `SELECT rv.value
         FROM runtime_fields rf
         JOIN runtime_values rv ON rv.field_id = rf.id
        WHERE rf.owner_entity_id = $1 AND rf.field_key = 'strings'`,
      [projectionEntityId],
    );
    const strings = (projStringsRow.rows[0]?.value ?? {}) as Record<string, unknown>;
    snapshots.projectionStrings = strings;
    if (!(String(heroId) in strings)) {
      logBlocker(
        'projection_strings_hero_present',
        `hero entry missing from projection strings: ${JSON.stringify(strings)}`,
      );
    }
    if (String(strangerId) in strings) {
      logBlocker(
        'projection_strings_stranger_dropped',
        `foreign stranger id ${strangerId} leaked into projection strings: ${JSON.stringify(strings)}`,
      );
    }

    // `entity_ref` runtime field (`home_ref`) must NOT be copied.
    const homeRefRow = await dbModule.query<{c: number}>(
      `SELECT COUNT(*)::int AS c
         FROM runtime_fields
        WHERE owner_entity_id = $1 AND field_key = 'home_ref'`,
      [projectionEntityId],
    );
    if (Number(homeRefRow.rows[0]?.c ?? 0) !== 0) {
      logBlocker(
        'projection_entity_ref_suppressed',
        'home_ref entity_ref runtime field leaked into projection',
      );
    }
    if (
      !blockers.some(
        (b) =>
          b.startsWith('projection_strings_') ||
          b.startsWith('projection_entity_ref_'),
      )
    ) {
      record({name: 'projection_runtime_sanitized', status: 'ok'});
    }

    // About-hero memory carried; world-bound NPC's memory not carried.
    const projMemRow = await dbModule.query<{c: number}>(
      `SELECT COUNT(*)::int AS c
         FROM npc_memories
        WHERE owner_entity_id = $1 AND about_entity_id = $2`,
      [projectionEntityId, heroId],
    );
    if (Number(projMemRow.rows[0]?.c ?? 0) < 1) {
      logBlocker(
        'projection_about_hero_memory',
        'about-hero memory missing from projection',
      );
    } else {
      record({name: 'projection_about_hero_memory', status: 'ok'});
    }
    // Inventory carryover: projection should hold the B-cartridge item.
    const projInvRow = await dbModule.query<{
      holder_entity_id: number;
      item_entity_id: number;
      count: number | string;
    }>(
      `SELECT holder_entity_id, item_entity_id, count
         FROM inventory_entries
        WHERE holder_entity_id = $1`,
      [projectionEntityId],
    );
    snapshots.projectionInventory = projInvRow.rows;
    if (projInvRow.rows.length < 1) {
      logBlocker(
        'projection_inventory_carried',
        'companion-owned inventory entry did not resolve to a B item',
      );
    } else {
      record({name: 'projection_inventory_carried', status: 'ok'});
    }

    // World-bound bond MUST NOT have a projection in B's universe.
    const worldBoundProjRow = await dbModule.query<{c: number}>(
      `SELECT COUNT(*)::int AS c
         FROM companion_universe_projections cup
         JOIN hero_companion_bonds b ON b.id = cup.companion_bond_id
        WHERE b.companion_key = 'companion:old_reeve'
          AND cup.universe_instance_id = $1::uuid`,
      [universeB],
    );
    if (Number(worldBoundProjRow.rows[0]?.c ?? 0) !== 0) {
      logBlocker(
        'world_bound_no_projection',
        `world-bound bond materialized a projection in B universe`,
      );
    } else {
      record({name: 'world_bound_no_projection', status: 'ok'});
    }

    // The world-bound NPC entity itself stays scoped to A (no twin in B).
    const reeveInBRow = await dbModule.query<{c: number}>(
      `SELECT COUNT(*)::int AS c
         FROM entities WHERE cartridge_id = $1
           AND profile->>'source_slug' = 'companion:old_reeve'`,
      [cartridgeBId],
    );
    if (Number(reeveInBRow.rows[0]?.c ?? 0) !== 0) {
      logBlocker(
        'world_bound_not_in_b_cartridge',
        'world-bound NPC entity unexpectedly exists in B cartridge scope',
      );
    } else {
      record({name: 'world_bound_not_in_b_cartridge', status: 'ok'});
    }

    // A-local quest entity has no equivalent in B's cartridge scope.
    const questInBRow = await dbModule.query<{c: number}>(
      `SELECT COUNT(*)::int AS c
         FROM entities WHERE id = $1 AND cartridge_id = $2`,
      [questEntityId, cartridgeBId],
    );
    if (Number(questInBRow.rows[0]?.c ?? 0) !== 0) {
      logBlocker(
        'a_local_quest_isolated',
        'A-local quest entity is somehow scoped to B',
      );
    } else {
      record({name: 'a_local_quest_isolated', status: 'ok'});
    }

    // Continuity events: both launches recorded.
    const eventRows = await dbModule.query<{
      event_type: string;
      target_cartridge_id: string | null;
      source_cartridge_id: string | null;
    }>(
      `SELECT event_type, target_cartridge_id, source_cartridge_id
         FROM hero_continuity_events
        WHERE player_id = $1
        ORDER BY id ASC`,
      [heroId],
    );
    snapshots.continuityEvents = eventRows.rows;
    if (eventRows.rows.length < 2) {
      logBlocker(
        'continuity_events_recorded',
        `expected at least 2 continuity events, got ${eventRows.rows.length}`,
      );
    } else {
      const lastTargets = eventRows.rows.map((r) => r.target_cartridge_id);
      if (!lastTargets.includes(cartridgeAId) || !lastTargets.includes(cartridgeBId)) {
        logBlocker(
          'continuity_events_targets',
          `events missing A or B target: ${JSON.stringify(lastTargets)}`,
        );
      } else {
        record({name: 'continuity_events_recorded', status: 'ok'});
      }
    }

    // Live roster after B launch must be the projection, not the source.
    const rosterAfterBRow = await dbModule.query<{companions: unknown}>(
      `SELECT metadata->'companions' AS companions FROM players WHERE entity_id = $1`,
      [heroId],
    );
    const rosterAfterB = Array.isArray(rosterAfterBRow.rows[0]?.companions)
      ? (rosterAfterBRow.rows[0]!.companions as unknown[]).map(Number)
      : [];
    snapshots.rosterAfterB = rosterAfterB;
    if (
      rosterAfterB.length !== 1 ||
      rosterAfterB[0] !== projectionEntityId
    ) {
      logBlocker(
        'roster_in_b_is_projection',
        `expected roster=[${projectionEntityId}] in B, got ${JSON.stringify(rosterAfterB)}`,
      );
    } else {
      record({name: 'roster_in_b_is_projection', status: 'ok'});
    }

    // A's hero_cartridge_states.world_snapshot must hold the A roster.
    const aSnapRow = await dbModule.query<{companions: unknown}>(
      `SELECT world_snapshot->'companions' AS companions
         FROM hero_cartridge_states
        WHERE player_id = $1 AND cartridge_id = $2`,
      [heroId, cartridgeAId],
    );
    const aSnap = Array.isArray(aSnapRow.rows[0]?.companions)
      ? (aSnapRow.rows[0]!.companions as unknown[]).map(Number)
      : [];
    snapshots.aWorldSnapshotCompanions = aSnap;
    if (
      !aSnap.includes(portableEntityId) ||
      !aSnap.includes(worldBoundEntityId)
    ) {
      logBlocker(
        'a_world_snapshot_holds_a_roster',
        `A world_snapshot lost the original roster: ${JSON.stringify(aSnap)}`,
      );
    } else {
      record({name: 'a_world_snapshot_holds_a_roster', status: 'ok'});
    }

    // ── 10. Return to A — assert local restoration ───────────────
    await page.reload({waitUntil: 'domcontentloaded'});
    await enterWorldsHeroes();
    await page.waitForSelector('.cart-lib__list .cart-lib__card', {
      timeout: 10000,
    });
    await selectHeroAndCartridge(heroName, cartridgeAId);
    await page.screenshot({
      path: path.join(screenshots, '08-preview-a-return.png'),
      fullPage: true,
    });
    await clickLaunch();
    await page.screenshot({
      path: path.join(screenshots, '09-after-return-a.png'),
      fullPage: true,
    });
    record({name: 'returned_to_a', status: 'ok'});

    // After returning to A, the live roster should be back to the A
    // source ids (companion + world-bound), not the B projection.
    const rosterAfterReturnRow = await dbModule.query<{companions: unknown}>(
      `SELECT metadata->'companions' AS companions FROM players WHERE entity_id = $1`,
      [heroId],
    );
    const rosterAfterReturn = Array.isArray(rosterAfterReturnRow.rows[0]?.companions)
      ? (rosterAfterReturnRow.rows[0]!.companions as unknown[]).map(Number)
      : [];
    snapshots.rosterAfterReturn = rosterAfterReturn;
    if (
      !rosterAfterReturn.includes(portableEntityId) ||
      !rosterAfterReturn.includes(worldBoundEntityId)
    ) {
      logBlocker(
        'a_roster_restored',
        `expected A roster to restore to source ids, got ${JSON.stringify(rosterAfterReturn)}`,
      );
    } else {
      record({name: 'a_roster_restored', status: 'ok'});
    }
    if (rosterAfterReturn.includes(projectionEntityId)) {
      logBlocker(
        'a_roster_no_b_projection',
        `B projection id ${projectionEntityId} leaked into restored A roster`,
      );
    } else {
      record({name: 'a_roster_no_b_projection', status: 'ok'});
    }

    // Active/available state on hero_cartridge_states.
    const statesRow = await dbModule.query<{
      cartridge_id: string;
      status: string;
    }>(
      `SELECT cartridge_id, status
         FROM hero_cartridge_states
        WHERE player_id = $1
        ORDER BY cartridge_id`,
      [heroId],
    );
    snapshots.heroCartridgeStates = statesRow.rows;
    const aState = statesRow.rows.find((r) => r.cartridge_id === cartridgeAId);
    const bState = statesRow.rows.find((r) => r.cartridge_id === cartridgeBId);
    if (aState?.status !== 'active') {
      logBlocker(
        'a_state_active_after_return',
        `expected A state=active, got ${aState?.status}`,
      );
    }
    if (bState?.status !== 'available') {
      logBlocker(
        'b_state_available_after_return',
        `expected B state=available, got ${bState?.status}`,
      );
    }
    if (aState?.status === 'active' && bState?.status === 'available') {
      record({name: 'hero_cartridge_states_flip', status: 'ok'});
    }

    // ── 11. Final console / network blocker pass ─────────────────
    teardownStarted = true;
    if (consoleErrors.length > 0) {
      logBlocker(
        'browser_console_clean',
        `console errors: ${JSON.stringify(consoleErrors.slice(0, 5))}`,
      );
    } else {
      record({name: 'browser_console_clean', status: 'ok'});
    }
    if (failedRequests.length > 0) {
      logBlocker(
        'no_failed_requests',
        `${failedRequests.length} requestfailed events`,
      );
    } else {
      record({name: 'no_failed_requests', status: 'ok'});
    }
    if (serverErrors.length > 0) {
      logBlocker(
        'no_4xx_5xx',
        `${serverErrors.length} 4xx/5xx responses: ${JSON.stringify(serverErrors.slice(0, 5))}`,
      );
    } else {
      record({name: 'no_4xx_5xx', status: 'ok'});
    }

    await context.close();
    await browser.close();
    clearTimeout(timeoutHandle);
    return await finish();
  } catch (err) {
    clearTimeout(timeoutHandle);
    logBlocker(
      'unexpected_exception',
      err instanceof Error ? `${err.name}: ${err.message}` : String(err),
    );
    return await finish();
  }
}

const isDirectRun = process.argv[1]
  ? path.resolve(process.argv[1]) === path.resolve(FILE)
  : false;
if (isDirectRun) {
  main(process.argv.slice(2)).then(
    (code) => process.exit(code),
    (err) => {
      console.error('[hero-continuity-smoke] FATAL', err);
      process.exit(1);
    },
  );
}

export {main as runHeroContinuitySmoke};
