-- Spec 110 - full language packs for core seed entity labels.
-- Covers the base character classes, starting social skills, and the first
-- faction pack. Later content-pack migrations reuse gh_lang_pack().

CREATE OR REPLACE FUNCTION gh_lang_pack(
  en text, ru text, uk text, bg text, sr text, es text, fr text, de text,
  it text, pt text, ro text, he text, ar text, fa text, ur text, hi text,
  mr text, ne text, bn text, th text, el text, hy text, ka text, ko text,
  ja text, zh text
) RETURNS jsonb
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT jsonb_build_object(
    'en', en, 'ru', ru, 'uk', uk, 'bg', bg, 'sr', sr, 'es', es, 'fr', fr,
    'de', de, 'it', it, 'pt', pt, 'ro', ro, 'he', he, 'ar', ar, 'fa', fa,
    'ur', ur, 'hi', hi, 'mr', mr, 'ne', ne, 'bn', bn, 'th', th, 'el', el,
    'hy', hy, 'ka', ka, 'ko', ko, 'ja', ja, 'zh', zh
  );
$$;

WITH raw_packs(entity_id, field_name, pack) AS (
  VALUES
  (600, 'display_name', gh_lang_pack(
    $gh$Wanderer$gh$, $gh$Странник$gh$, $gh$Мандрівник$gh$, $gh$Скитник$gh$, $gh$Луталица$gh$, $gh$Errante$gh$, $gh$Errant$gh$, $gh$Wanderer$gh$, $gh$Viandante$gh$, $gh$Andarilho$gh$, $gh$Rătăcitor$gh$, $gh$נודד$gh$, $gh$جوال$gh$, $gh$رهگذر$gh$, $gh$آوارہ گرد$gh$, $gh$पथिक$gh$, $gh$भटक्या$gh$, $gh$यात्री$gh$, $gh$পথিক$gh$, $gh$นักพเนจร$gh$, $gh$Περιπλανώμενος$gh$, $gh$Թափառական$gh$, $gh$მოხეტიალე$gh$, $gh$방랑자$gh$, $gh$放浪者$gh$, $gh$流浪者$gh$
  )),
  (600, 'summary', gh_lang_pack(
    $gh$A traveller without allegiance. Learns by doing.$gh$, $gh$Путник без принадлежности. Учится делом.$gh$, $gh$Мандрівник без належності. Вчиться дією.$gh$, $gh$Пътник без вярност към никого. Учи се чрез действие.$gh$, $gh$Путник без припадности. Учи кроз дело.$gh$, $gh$Viajero sin lealtad fija. Aprende haciendo.$gh$, $gh$Voyageur sans allégeance. Apprend par l'action.$gh$, $gh$Reisender ohne Bindung. Lernt durch Handeln.$gh$, $gh$Viaggiatore senza appartenenza. Impara agendo.$gh$, $gh$Viajante sem afiliação. Aprende fazendo.$gh$, $gh$Călător fără apartenență. Învață prin faptă.$gh$, $gh$נוסע ללא נאמנות קבועה. לומד מתוך מעשה.$gh$, $gh$مسافر بلا ولاء ثابت. يتعلم بالفعل.$gh$, $gh$مسافری بی‌وابستگی. با عمل می‌آموزد.$gh$, $gh$بے وابستہ مسافر۔ عمل سے سیکھتا ہے۔$gh$, $gh$बिना निष्ठा का यात्री। करके सीखता है।$gh$, $gh$निष्ठा नसलेला प्रवासी. कृतीतून शिकतो.$gh$, $gh$कुनै निष्ठा नभएको यात्री। काम गरेर सिक्छ।$gh$, $gh$কোনো আনুগত্যহীন পথিক। কাজ করে শেখে।$gh$, $gh$นักเดินทางไร้สังกัด เรียนรู้จากการลงมือทำ$gh$, $gh$Ταξιδιώτης χωρίς δεσμούς. Μαθαίνει πράττοντας.$gh$, $gh$Ճամփորդ առանց պատկանելության։ Սովորում է գործով։$gh$, $gh$მგზავრი კუთვნილების გარეშე. საქმით სწავლობს.$gh$, $gh$소속 없는 여행자. 행동으로 배운다.$gh$, $gh$所属を持たない旅人。行動から学ぶ。$gh$, $gh$无归属的旅人。靠行动学习。$gh$
  )),
  (600, 'description', gh_lang_pack(
    $gh$Versatile social survivor. Bargains and reads people instead of swinging a blade.$gh$, $gh$Гибкий социальный выживальщик. Торгуется и читает людей вместо того, чтобы махать клинком.$gh$, $gh$Гнучкий соціальний виживальник. Торгується й читає людей замість махати клинком.$gh$, $gh$Гъвкав оцелял в обществото. Пазарува се и чете хората вместо да размахва острие.$gh$, $gh$Сналажљив друштвени преживљавач. Ценка се и чита људе уместо да маше сечивом.$gh$, $gh$Superviviente social versátil. Regatea y lee a la gente en lugar de blandir una hoja.$gh$, $gh$Survivant social polyvalent. Négocie et lit les gens au lieu d'agiter une lame.$gh$, $gh$Vielseitiger sozialer Überlebender. Verhandelt und liest Menschen statt die Klinge zu schwingen.$gh$, $gh$Sopravvissuto sociale versatile. Contratta e legge le persone invece di agitare una lama.$gh$, $gh$Sobrevivente social versátil. Barganha e lê pessoas em vez de brandir uma lâmina.$gh$, $gh$Supraviețuitor social versatil. Negociază și citește oamenii în loc să fluture o lamă.$gh$, $gh$שורד חברתי גמיש. מתמקח וקורא אנשים במקום להניף להב.$gh$, $gh$ناج اجتماعي مرن. يساوم ويقرأ الناس بدلاً من التلويح بنصل.$gh$, $gh$بازمانده‌ای اجتماعی و منعطف. چانه می‌زند و آدم‌ها را می‌خواند نه اینکه تیغ بچرخاند.$gh$, $gh$لچک دار سماجی بچنے والا۔ تلوار چلانے کے بجائے سودا کرتا اور لوگوں کو پڑھتا ہے۔$gh$, $gh$लचीला सामाजिक जीवित रहने वाला। तलवार चलाने के बजाय सौदा करता और लोगों को पढ़ता है।$gh$, $gh$बहुगुणी सामाजिक जगणारा. पात्याऐवजी सौदेबाजी करतो आणि लोकांना वाचतो.$gh$, $gh$लचिलो सामाजिक जीवितकर्ता। तरबार चलाउनुको सट्टा मोलतोल गर्छ र मान्छे पढ्छ।$gh$, $gh$বহুমুখী সামাজিক টিকে থাকা মানুষ। তরবারি চালানোর বদলে দর কষাকষি করে ও মানুষ পড়ে।$gh$, $gh$ผู้เอาตัวรอดทางสังคมที่ยืดหยุ่น ต่อรองและอ่านคนแทนการแกว่งดาบ$gh$, $gh$Ευέλικτος κοινωνικός επιζών. Παζαρεύει και διαβάζει ανθρώπους αντί να σηκώνει λεπίδα.$gh$, $gh$Ճկուն սոցիալական գոյատևող։ Սակարկում և կարդում է մարդկանց՝ սուր ճոճելու փոխարեն։$gh$, $gh$მოქნილი სოციალური გადარჩენილი. ხმლის ქნევის ნაცვლად ვაჭრობს და ადამიანებს კითხულობს.$gh$, $gh$유연한 사회적 생존자. 칼을 휘두르기보다 흥정하고 사람을 읽는다.$gh$, $gh$柔軟な社交型の生存者。刃を振るうより交渉し、人を読む。$gh$, $gh$灵活的社交生存者。不挥刀，而是谈判并读懂人心。$gh$
  )),

  (601, 'display_name', gh_lang_pack(
    $gh$Rogue$gh$, $gh$Плут$gh$, $gh$Плут$gh$, $gh$Мошеник$gh$, $gh$Лупеж$gh$, $gh$Pícaro$gh$, $gh$Roublard$gh$, $gh$Schurke$gh$, $gh$Canaglia$gh$, $gh$Ladino$gh$, $gh$Pungaș$gh$, $gh$נוכל$gh$, $gh$مخادع$gh$, $gh$فریبکار$gh$, $gh$چالاک$gh$, $gh$धूर्त$gh$, $gh$धूर्त$gh$, $gh$धूर्त$gh$, $gh$চতুর বদমাশ$gh$, $gh$จอมเจ้าเล่ห์$gh$, $gh$Κατεργάρης$gh$, $gh$Խարդախ$gh$, $gh$მაქცია$gh$, $gh$도적$gh$, $gh$ローグ$gh$, $gh$游荡者$gh$
  )),
  (601, 'summary', gh_lang_pack(
    $gh$Quick-witted, light-stepping operator. Lives by stealth, nimble hands, and the right word.$gh$, $gh$Остроумный и легкий на шаг делец. Живет скрытностью, ловкими руками и вовремя сказанным словом.$gh$, $gh$Кмітливий і легкий на крок діяч. Живе скритністю, спритними руками й вчасним словом.$gh$, $gh$Съобразителен и лек в стъпката играч. Живее със скритост, ловки ръце и точната дума.$gh$, $gh$Домишљат и лаког корака. Живи од прикривености, спретних руку и праве речи.$gh$, $gh$Operador astuto y ligero. Vive del sigilo, las manos hábiles y la palabra justa.$gh$, $gh$Opérateur vif et léger. Vit de discrétion, de mains agiles et du bon mot.$gh$, $gh$Schneller Kopf, leiser Schritt. Lebt von Heimlichkeit, flinken Händen und dem richtigen Wort.$gh$, $gh$Operatore scaltro e dal passo leggero. Vive di furtività, mani rapide e parola giusta.$gh$, $gh$Operador esperto e leve. Vive de furtividade, mãos ágeis e da palavra certa.$gh$, $gh$Operator iute la minte și ușor la pas. Trăiește din furiș, mâini dibace și cuvântul potrivit.$gh$, $gh$פעיל חד מחשבה וקל צעד. חי מהתגנבות, ידיים זריזות והמילה הנכונה.$gh$, $gh$عامل سريع البديهة وخفيف الخطى. يعيش بالتسلل واليد الخفيفة والكلمة المناسبة.$gh$, $gh$کاری تیزهوش و سبک‌قدم. با پنهان‌کاری، دست‌های چابک و واژه درست زنده می‌ماند.$gh$, $gh$تیز فہم، ہلکے قدموں والا کاریگر۔ چپکے پن، پھرتیلے ہاتھوں اور درست لفظ سے جیتا ہے۔$gh$, $gh$तेज दिमाग, हल्के कदम वाला कामगार। चोरी-छिपे, फुर्तीले हाथों और सही शब्द से जीता है।$gh$, $gh$चपळ बुद्धीचा, हलक्या पावलांचा कारस्थानी. गुप्तता, चपळ हात आणि योग्य शब्दावर जगतो.$gh$, $gh$छिटो सोच्ने, हल्का पाइला चाल्ने व्यक्ति। गोप्यता, छरिता हात र सही शब्दमा बाँच्दछ।$gh$, $gh$তীক্ষ্ণবুদ্ধি, হালকা পায়ের কারিগর। গোপনতা, চটপটে হাত আর ঠিক কথায় বাঁচে।$gh$, $gh$คนทำงานหัวไว ฝีเท้าเบา อยู่รอดด้วยความลับ มือไว และคำที่ถูกจังหวะ$gh$, $gh$Γρήγορος στο μυαλό και ελαφρύς στο βήμα. Ζει με μυστικότητα, επιδέξια χέρια και τη σωστή λέξη.$gh$, $gh$Սուր միտք և թեթև քայլ ունեցող գործիչ։ Ապրում է գաղտնիությամբ, ճարպիկ ձեռքերով և ճիշտ խոսքով։$gh$, $gh$სწრაფგონება და მსუბუქფეხა მოთამაშე. ცხოვრობს მალვით, მოქნილი ხელებით და საჭირო სიტყვით.$gh$, $gh$재치 있고 발걸음이 가벼운 해결사. 은신, 손재주, 알맞은 말로 살아간다.$gh$, $gh$機転が利き、足取りの軽い工作者。隠密、器用な手、ふさわしい言葉で生きる。$gh$, $gh$机敏轻步的行家。靠潜行、巧手与恰到好处的话语谋生。$gh$
  )),

  (701, 'display_name', gh_lang_pack(
    $gh$Bargain$gh$, $gh$Торг$gh$, $gh$Торг$gh$, $gh$Пазарлък$gh$, $gh$Ценкање$gh$, $gh$Regatear$gh$, $gh$Marchandage$gh$, $gh$Feilschen$gh$, $gh$Contrattare$gh$, $gh$Barganha$gh$, $gh$Tocmeală$gh$, $gh$מיקוח$gh$, $gh$مساومة$gh$, $gh$چانه‌زنی$gh$, $gh$سودا بازی$gh$, $gh$मोलभाव$gh$, $gh$सौदेबाजी$gh$, $gh$मोलमोलाइ$gh$, $gh$দর কষাকষি$gh$, $gh$ต่อรอง$gh$, $gh$Παζάρι$gh$, $gh$Սակարկություն$gh$, $gh$ვაჭრობა$gh$, $gh$흥정$gh$, $gh$値切り$gh$, $gh$议价$gh$
  )),
  (701, 'summary', gh_lang_pack(
    $gh$Reads a seller's tells and cuts the price.$gh$, $gh$Читает повадки продавца и сбивает цену.$gh$, $gh$Читає ознаки продавця й збиває ціну.$gh$, $gh$Разчита знаците на продавача и сваля цената.$gh$, $gh$Чита знаке продавца и обара цену.$gh$, $gh$Lee las señales del vendedor y baja el precio.$gh$, $gh$Lit les tics du vendeur et fait baisser le prix.$gh$, $gh$Liest die Signale eines Händlers und drückt den Preis.$gh$, $gh$Legge i segnali del venditore e abbassa il prezzo.$gh$, $gh$Lê os sinais do vendedor e reduz o preço.$gh$, $gh$Citește semnele vânzătorului și scade prețul.$gh$, $gh$קורא את סימני המוכר ומוריד את המחיר.$gh$, $gh$يقرأ إشارات البائع ويخفض السعر.$gh$, $gh$نشانه‌های فروشنده را می‌خواند و قیمت را پایین می‌آورد.$gh$, $gh$بیچنے والے کے اشارے پڑھتا ہے اور قیمت گھٹاتا ہے۔$gh$, $gh$विक्रेता के संकेत पढ़ता है और कीमत घटाता है।$gh$, $gh$विक्रेत्याचे संकेत ओळखतो आणि किंमत कमी करतो.$gh$, $gh$बिक्रेताका संकेत पढ्छ र मूल्य घटाउँछ।$gh$, $gh$বিক্রেতার লক্ষণ পড়ে দাম কমায়।$gh$, $gh$อ่านท่าทีของคนขายแล้วกดราคา$gh$, $gh$Διαβάζει τα σημάδια του πωλητή και ρίχνει την τιμή.$gh$, $gh$Կարդում է վաճառողի նշանները և իջեցնում գինը։$gh$, $gh$კითხულობს გამყიდველის ნიშნებს და ფასს აკლებს.$gh$, $gh$상인의 기색을 읽고 가격을 깎는다.$gh$, $gh$売り手の癖を読み、値を下げる。$gh$, $gh$看出卖家的破绽并压低价格。$gh$
  )),
  (701, 'description', gh_lang_pack(
    $gh$During a transaction, roll CHA against the DC to improve the price.$gh$, $gh$Во время сделки брось Харизму против СЛ, чтобы улучшить цену.$gh$, $gh$Під час угоди кинь Харизму проти СК, щоб поліпшити ціну.$gh$, $gh$По време на сделка хвърли Харизма срещу ТС, за да подобриш цената.$gh$, $gh$Током посла баци Харизму против ТН да поправиш цену.$gh$, $gh$Durante una transacción, tira CAR contra la CD para mejorar el precio.$gh$, $gh$Pendant une transaction, lance CHA contre la DD pour améliorer le prix.$gh$, $gh$Bei einem Handel würfle CHA gegen den SG, um den Preis zu verbessern.$gh$, $gh$Durante una transazione tira CAR contro la CD per migliorare il prezzo.$gh$, $gh$Durante uma transação, role CAR contra a CD para melhorar o preço.$gh$, $gh$Într-o tranzacție, aruncă CAR contra DC ca să îmbunătățești prețul.$gh$, $gh$בזמן עסקה גלגל כריזמה מול הדירוג כדי לשפר את המחיר.$gh$, $gh$أثناء صفقة، ارم الكاريزما ضد الصعوبة لتحسين السعر.$gh$, $gh$هنگام معامله، کاریزما را در برابر درجه سختی بینداز تا قیمت بهتر شود.$gh$, $gh$لین دین کے دوران قیمت بہتر کرنے کے لیے کرشمہ کو مشکل درجے کے خلاف پھینکو۔$gh$, $gh$लेन-देन में कीमत सुधारने के लिए करिश्मा को DC के विरुद्ध रोल करो।$gh$, $gh$व्यवहारात किंमत सुधारण्यासाठी करिश्मा DC विरुद्ध फेका.$gh$, $gh$लेनदेनमा मूल्य राम्रो बनाउन करिश्मा DC विरुद्ध रोल गर।$gh$, $gh$লেনদেনে দাম ভালো করতে ক্যারিশমা DC-এর বিরুদ্ধে রোল করো।$gh$, $gh$ระหว่างซื้อขาย ทอยเสน่ห์เทียบ DC เพื่อให้ราคาเป็นใจ$gh$, $gh$Σε συναλλαγή, ρίξε Χάρισμα ενάντια στη ΔΔ για καλύτερη τιμή.$gh$, $gh$Գործարքի ժամանակ գցիր Հմայք DC-ի դեմ՝ գինը բարելավելու համար։$gh$, $gh$გარიგებისას ქარიზმა გადააგდე DC-ის წინააღმდეგ ფასის გასაუმჯობესებლად.$gh$, $gh$거래 중 가격을 좋게 하려면 매력으로 DC에 맞서 굴린다.$gh$, $gh$取引中、価格を良くするために魅力でDCに対抗してロールする。$gh$, $gh$交易时以魅力对抗 DC 掷骰，以改善价格。$gh$
  )),

  (702, 'display_name', gh_lang_pack(
    $gh$Charm$gh$, $gh$Обаяние$gh$, $gh$Чарівність$gh$, $gh$Очарование$gh$, $gh$Шарм$gh$, $gh$Encanto$gh$, $gh$Charme$gh$, $gh$Charme$gh$, $gh$Fascino$gh$, $gh$Encanto$gh$, $gh$Farmec$gh$, $gh$קסם אישי$gh$, $gh$سحر$gh$, $gh$جاذبه$gh$, $gh$دلکشی$gh$, $gh$आकर्षण$gh$, $gh$मोहिनी$gh$, $gh$आकर्षण$gh$, $gh$মোহনীয়তা$gh$, $gh$เสน่ห์$gh$, $gh$Γοητεία$gh$, $gh$Հմայք$gh$, $gh$ხიბლი$gh$, $gh$매혹$gh$, $gh$魅了$gh$, $gh$魅力$gh$
  )),
  (702, 'summary', gh_lang_pack(
    $gh$Wins a moment of trust from someone wary.$gh$, $gh$Выигрывает миг доверия у настороженного человека.$gh$, $gh$Здобуває мить довіри від настороженої людини.$gh$, $gh$Печели миг доверие от предпазлив човек.$gh$, $gh$Осваја тренутак поверења од опрезне особе.$gh$, $gh$Gana un instante de confianza de alguien receloso.$gh$, $gh$Gagne un instant de confiance d'une personne méfiante.$gh$, $gh$Gewinnt einen Moment Vertrauen von jemandem, der misstrauisch ist.$gh$, $gh$Ottiene un momento di fiducia da qualcuno diffidente.$gh$, $gh$Conquista um instante de confiança de alguém cauteloso.$gh$, $gh$Câștigă o clipă de încredere de la cineva precaut.$gh$, $gh$זוכה לרגע של אמון מאדם חשדן.$gh$, $gh$يكسب لحظة ثقة من شخص حذر.$gh$, $gh$لحظه‌ای اعتماد از کسی محتاط به دست می‌آورد.$gh$, $gh$کسی محتاط شخص سے ایک لمحہ اعتماد جیتتا ہے۔$gh$, $gh$सतर्क व्यक्ति से भरोसे का एक पल जीतता है।$gh$, $gh$सावध व्यक्तीकडून विश्वासाचा क्षण मिळवतो.$gh$, $gh$सचेत व्यक्तिबाट विश्वासको एक क्षण जित्छ।$gh$, $gh$সতর্ক কারও কাছ থেকে এক মুহূর্তের বিশ্বাস জিতে নেয়।$gh$, $gh$ชนะใจคนระแวงได้ชั่วขณะ$gh$, $gh$Κερδίζει μια στιγμή εμπιστοσύνης από κάποιον επιφυλακτικό.$gh$, $gh$Զգուշավոր մարդուց վստահության մի պահ է շահում։$gh$, $gh$ფრთხილი ადამიანისგან ნდობის ერთ წამს იგებს.$gh$, $gh$경계하는 사람에게서 잠깐의 신뢰를 얻는다.$gh$, $gh$警戒する相手から一瞬の信頼を得る。$gh$, $gh$从戒备之人那里赢得片刻信任。$gh$
  )),
  (702, 'description', gh_lang_pack(
    $gh$Roll CHA to soften a hostile or neutral NPC by one step.$gh$, $gh$Брось Харизму, чтобы смягчить враждебного или нейтрального NPC на один шаг.$gh$, $gh$Кинь Харизму, щоб пом'якшити ворожого чи нейтрального NPC на один крок.$gh$, $gh$Хвърли Харизма, за да смекчиш враждебен или неутрален NPC с една степен.$gh$, $gh$Баци Харизму да ублажиш непријатељског или неутралног NPC-а за један корак.$gh$, $gh$Tira CAR para suavizar un NPC hostil o neutral un paso.$gh$, $gh$Lance CHA pour adoucir d'un cran un PNJ hostile ou neutre.$gh$, $gh$Würfle CHA, um einen feindlichen oder neutralen NSC um eine Stufe milder zu stimmen.$gh$, $gh$Tira CAR per ammorbidire di un passo un PNG ostile o neutrale.$gh$, $gh$Role CAR para abrandar um NPC hostil ou neutro em um passo.$gh$, $gh$Aruncă CAR ca să îmblânzești cu un pas un NPC ostil sau neutru.$gh$, $gh$גלגל כריזמה כדי לרכך דמות עוינת או ניטרלית בצעד אחד.$gh$, $gh$ارم الكاريزما لتليين موقف شخصية معادية أو محايدة درجة واحدة.$gh$, $gh$کاریزما بینداز تا NPC دشمن یا خنثی را یک پله نرم‌تر کنی.$gh$, $gh$دشمن یا غیر جانبدار NPC کو ایک قدم نرم کرنے کے لیے کرشمہ پھینکو۔$gh$, $gh$शत्रुतापूर्ण या तटस्थ NPC को एक कदम नरम करने के लिए करिश्मा रोल करो।$gh$, $gh$शत्रू किंवा तटस्थ NPC ला एक पायरी मवाळ करण्यासाठी करिश्मा फेका.$gh$, $gh$विरोधी वा तटस्थ NPC लाई एक कदम नरम बनाउन करिश्मा रोल गर।$gh$, $gh$শত্রু বা নিরপেক্ষ NPC-কে এক ধাপ নরম করতে ক্যারিশমা রোল করো।$gh$, $gh$ทอยเสน่ห์เพื่อทำให้ NPC ที่เป็นศัตรูหรือเป็นกลางอ่อนลงหนึ่งขั้น$gh$, $gh$Ρίξε Χάρισμα για να μαλακώσεις έναν εχθρικό ή ουδέτερο NPC κατά ένα βήμα.$gh$, $gh$Գցիր Հմայք՝ թշնամական կամ չեզոք NPC-ին մեկ աստիճան մեղմելու համար։$gh$, $gh$ქარიზმა გადააგდე, რომ მტრული ან ნეიტრალური NPC ერთი საფეხურით მოალბო.$gh$, $gh$적대적이거나 중립적인 NPC를 한 단계 누그러뜨리려면 매력으로 굴린다.$gh$, $gh$敵対的または中立のNPCを一段階和らげるために魅力でロールする。$gh$, $gh$以魅力掷骰，让敌对或中立 NPC 的态度缓和一级。$gh$
  )),

  (800, 'display_name', gh_lang_pack(
    $gh$Quickgrin Merchants$gh$, $gh$Торговцы Хитрогрин$gh$, $gh$Купці Хитрогрин$gh$, $gh$Търговците Хитрогрин$gh$, $gh$Трговци Хитрогрин$gh$, $gh$Mercaderes Quickgrin$gh$, $gh$Marchands Quickgrin$gh$, $gh$Quickgrin-Händler$gh$, $gh$Mercanti Quickgrin$gh$, $gh$Mercadores Quickgrin$gh$, $gh$Negustorii Quickgrin$gh$, $gh$סוחרי קוויקגרין$gh$, $gh$تجار كويكغرين$gh$, $gh$بازرگانان کوییک‌گرین$gh$, $gh$کوئک گرن تاجر$gh$, $gh$क्विकग्रिन व्यापारी$gh$, $gh$क्विकग्रिन व्यापारी$gh$, $gh$क्विकग्रिन व्यापारीहरू$gh$, $gh$কুইকগ্রিন বণিকেরা$gh$, $gh$พ่อค้า Quickgrin$gh$, $gh$Έμποροι Quickgrin$gh$, $gh$Քուիքգրինի վաճառականներ$gh$, $gh$ქვიქგრინის ვაჭრები$gh$, $gh$퀵그린 상인들$gh$, $gh$クイックグリン商人団$gh$, $gh$快 grin 商人会$gh$
  )),
  (800, 'summary', gh_lang_pack(
    $gh$A loose guild of brokers, fence-merchants, and contract-runners around Quickgrin Lane.$gh$, $gh$Вольная гильдия брокеров, скупщиков и исполнителей контрактов вокруг переулка Хитрогрин.$gh$, $gh$Вільна гільдія брокерів, перекупників і виконавців контрактів навколо провулка Хитрогрин.$gh$, $gh$Свободна гилдия от брокери, прекупвачи и изпълнители на договори около уличката Хитрогрин.$gh$, $gh$Лабав еснаф посредника, препродаваца и извршилаца уговора око улице Хитрогрин.$gh$, $gh$Gremio flexible de corredores, revendedores y ejecutores de contratos en Quickgrin Lane.$gh$, $gh$Guilde lâche de courtiers, receleurs et porteurs de contrats autour de Quickgrin Lane.$gh$, $gh$Lockerer Bund aus Maklern, Hehlerhändlern und Auftragsläufern rund um Quickgrin Lane.$gh$, $gh$Gilda libera di mediatori, ricettatori e corrieri di contratti attorno a Quickgrin Lane.$gh$, $gh$Guilda solta de corretores, atravessadores e cumpridores de contratos em Quickgrin Lane.$gh$, $gh$Breaslă liberă de brokeri, negustori de marfă dubioasă și alergători de contracte din Quickgrin Lane.$gh$, $gh$גילדה רופפת של מתווכים, סוחרי סחורה מפוקפקת ומריצי חוזים סביב סמטת קוויקגרין.$gh$, $gh$نقابة فضفاضة من السماسرة وتجار السلع المشبوهة ومنفذي العقود حول زقاق كويكغرين.$gh$, $gh$اتحادیه‌ای آزاد از دلالان، مال‌خرها و دونده‌های قرارداد پیرامون کوییک‌گرین لین.$gh$, $gh$کوئک گرن لین کے گرد دلالوں، مال خریدنے والوں اور معاہدہ برداروں کی ڈھیلی انجمن۔$gh$, $gh$क्विकग्रिन लेन के आसपास दलालों, माल-खरीदारों और अनुबंध-दौड़कों का ढीला संघ।$gh$, $gh$क्विकग्रिन लेनभोवती दलाल, मालखरेदी व्यापारी आणि करारधावकांची सैल संघटना.$gh$, $gh$क्विकग्रिन लेन वरिपरि दलाल, शंकास्पद व्यापारी र करार-दौडाहाहरूको खुकुलो गिल्ड।$gh$, $gh$কুইকগ্রিন লেন ঘিরে দালাল, বেআইনি পণ্য-ব্যবসায়ী ও চুক্তি-দৌড়কদের আলগা গিল্ড।$gh$, $gh$สมาคมหลวม ๆ ของนายหน้า พ่อค้าของไม่สะอาด และผู้วิ่งงานสัญญารอบ Quickgrin Lane$gh$, $gh$Χαλαρή συντεχνία μεσαζόντων, κλεπταποδόχων και δρομέων συμβολαίων γύρω από την Quickgrin Lane.$gh$, $gh$Քուիքգրին փողոցի շուրջ բրոքերների, վերավաճառողների և պայմանագրային վազորդների ազատ գիլդիա։$gh$, $gh$ქვიქგრინის ქუჩის გარშემო ბროკერების, გადამყიდველებისა და კონტრაქტის გამტარებლების თავისუფალი გილდია.$gh$, $gh$퀵그린 레인 주변의 중개인, 장물상, 계약 심부름꾼들의 느슨한 길드.$gh$, $gh$クイックグリン小路周辺の仲介人、故買商、契約運びたちの緩い組合。$gh$, $gh$快 grin 巷一带由掮客、销赃商和契约跑腿组成的松散行会。$gh$
  )),
  (800, 'description', gh_lang_pack(
    $gh$Loyalty is to the deal, not the crown.$gh$, $gh$Верность здесь отдают сделке, а не короне.$gh$, $gh$Вірність тут належить угоді, а не короні.$gh$, $gh$Верността е към сделката, не към короната.$gh$, $gh$Оданост припада послу, не круни.$gh$, $gh$La lealtad es al trato, no a la corona.$gh$, $gh$La loyauté va au marché, pas à la couronne.$gh$, $gh$Die Treue gilt dem Geschäft, nicht der Krone.$gh$, $gh$La lealtà va all'accordo, non alla corona.$gh$, $gh$A lealdade é ao acordo, não à coroa.$gh$, $gh$Loialitatea este față de înțelegere, nu față de coroană.$gh$, $gh$הנאמנות היא לעסקה, לא לכתר.$gh$, $gh$الولاء للصفقة لا للتاج.$gh$, $gh$وفاداری به معامله است، نه به تاج.$gh$, $gh$وفاداری سودے سے ہے، تاج سے نہیں۔$gh$, $gh$निष्ठा सौदे से है, ताज से नहीं।$gh$, $gh$निष्ठा कराराशी आहे, मुकुटाशी नाही.$gh$, $gh$निष्ठा सम्झौताप्रति हो, मुकुटप्रति होइन।$gh$, $gh$আনুগত্য চুক্তির প্রতি, মুকুটের প্রতি নয়।$gh$, $gh$ความภักดีมีให้ข้อตกลง ไม่ใช่มงกุฎ$gh$, $gh$Η πίστη ανήκει στη συμφωνία, όχι στο στέμμα.$gh$, $gh$Հավատարմությունը գործարքին է, ոչ թե թագին։$gh$, $gh$ერთგულება გარიგებას ეკუთვნის, არა გვირგვინს.$gh$, $gh$충성은 왕관이 아니라 거래를 향한다.$gh$, $gh$忠誠は王冠ではなく取引に向く。$gh$, $gh$忠诚献给交易，而非王冠。$gh$
  ))
),
entity_packs AS (
  SELECT entity_id, jsonb_object_agg(field_name, pack) AS pack
    FROM raw_packs
   GROUP BY entity_id
)
UPDATE entities AS entity
   SET i18n = COALESCE(entity.i18n, '{}'::jsonb) || entity_packs.pack
  FROM entity_packs
 WHERE entity.id = entity_packs.entity_id;
