-- Spec 110 - full language packs for seed item entities.

WITH raw_packs(entity_id, field_name, pack) AS (
  VALUES
  (300, 'display_name', gh_lang_pack(
    $gh$Gold Coin$gh$, $gh$Золотая монета$gh$, $gh$Золота монета$gh$, $gh$Златна монета$gh$, $gh$Златник$gh$, $gh$Moneda de oro$gh$, $gh$Pièce d'or$gh$, $gh$Goldmünze$gh$, $gh$Moneta d'oro$gh$, $gh$Moeda de ouro$gh$, $gh$Monedă de aur$gh$, $gh$מטבע זהב$gh$, $gh$عملة ذهبية$gh$, $gh$سکه طلا$gh$, $gh$سونے کا سکہ$gh$, $gh$सोने का सिक्का$gh$, $gh$सोन्याचे नाणे$gh$, $gh$सुनको सिक्का$gh$, $gh$সোনার মুদ্রা$gh$, $gh$เหรียญทอง$gh$, $gh$Χρυσό νόμισμα$gh$, $gh$Ոսկե մետաղադրամ$gh$, $gh$ოქროს მონეტა$gh$, $gh$금화$gh$, $gh$金貨$gh$, $gh$金币$gh$
  )),
  (300, 'summary', gh_lang_pack(
    $gh$Standard Quickgrin currency. Inventory tools are the only canonical way to move it.$gh$, $gh$Стандартная валюта Хитрогрин. Канонически перемещается только инструментами инвентаря.$gh$, $gh$Стандартна валюта Хитрогрин. Канонічно переміщується лише інструментами інвентарю.$gh$, $gh$Стандартна валута на Хитрогрин. Канонично се мести само чрез инструментите на инвентара.$gh$, $gh$Стандардна валута Хитрогрина. Канонски се помера само алатима инвентара.$gh$, $gh$Moneda estándar de Quickgrin. Solo las herramientas de inventario la mueven de forma canónica.$gh$, $gh$Monnaie standard de Quickgrin. Seuls les outils d'inventaire la déplacent canoniquement.$gh$, $gh$Standardwährung von Quickgrin. Nur Inventarwerkzeuge bewegen sie kanonisch.$gh$, $gh$Valuta standard di Quickgrin. Solo gli strumenti d'inventario la muovono in modo canonico.$gh$, $gh$Moeda padrão de Quickgrin. Só ferramentas de inventário a movem de forma canônica.$gh$, $gh$Moneda standard din Quickgrin. Doar uneltele de inventar o mută canonic.$gh$, $gh$המטבע הסטנדרטי של קוויקגרין. רק כלי המלאי מזיזים אותו באופן קאנוני.$gh$, $gh$عملة كويكغرين القياسية. أدوات الجرد وحدها تنقلها بشكل قانوني في العالم.$gh$, $gh$ارز رایج کوییک‌گرین. فقط ابزارهای موجودی آن را به‌صورت کانونی جابه‌جا می‌کنند.$gh$, $gh$کوئک گرن کی معیاری کرنسی۔ اسے صرف انوینٹری ٹولز ہی کینن میں منتقل کرتے ہیں۔$gh$, $gh$क्विकग्रिन की मानक मुद्रा। इसे कैनन में केवल इन्वेंटरी उपकरण ही हिलाते हैं।$gh$, $gh$क्विकग्रिनचे प्रमाण चलन. ते फक्त इन्व्हेंटरी साधनांनीच कॅननमध्ये हलते.$gh$, $gh$क्विकग्रिनको मानक मुद्रा। यसलाई क्याननमा इनभेन्टरी उपकरणले मात्र सार्छ।$gh$, $gh$কুইকগ্রিনের মানক মুদ্রা। কেবল ইনভেন্টরি টুলই এটিকে ক্যাননে সরায়।$gh$, $gh$สกุลเงินมาตรฐานของ Quickgrin ย้ายได้ตามกฎผ่านเครื่องมือคลังเท่านั้น$gh$, $gh$Τυπικό νόμισμα του Quickgrin. Μόνο τα εργαλεία αποθέματος το μετακινούν κανονικά.$gh$, $gh$Քուիքգրինի ստանդարտ արժույթը։ Կանոնիկորեն տեղափոխվում է միայն գույքագրման գործիքներով։$gh$, $gh$ქვიქგრინის სტანდარტული ვალუტა. კანონიკურად მხოლოდ ინვენტარის ხელსაწყოებით გადაადგილდება.$gh$, $gh$퀵그린의 표준 화폐. 인벤토리 도구만이 정식으로 이동시킨다.$gh$, $gh$クイックグリン標準の通貨。正史上はインベントリツールだけが移動できる。$gh$, $gh$快 grin 的标准货币。只有库存工具能以正史方式移动它。$gh$
  )),

  (301, 'display_name', gh_lang_pack(
    $gh$Extinguished Lamp$gh$, $gh$Погасшая лампа$gh$, $gh$Згасла лампа$gh$, $gh$Угаснала лампа$gh$, $gh$Угашена лампа$gh$, $gh$Lámpara apagada$gh$, $gh$Lampe éteinte$gh$, $gh$Erloschene Lampe$gh$, $gh$Lampada spenta$gh$, $gh$Lâmpada apagada$gh$, $gh$Lampă stinsă$gh$, $gh$מנורה כבויה$gh$, $gh$مصباح مطفأ$gh$, $gh$چراغ خاموش$gh$, $gh$بجھا ہوا چراغ$gh$, $gh$बुझा हुआ दीपक$gh$, $gh$विझलेला दिवा$gh$, $gh$निभेको बत्ती$gh$, $gh$নেভা প্রদীপ$gh$, $gh$ตะเกียงดับ$gh$, $gh$Σβηστή λάμπα$gh$, $gh$Մարած լամպ$gh$, $gh$ჩამქრალი ლამპა$gh$, $gh$꺼진 램프$gh$, $gh$消えたランプ$gh$, $gh$熄灭的灯$gh$
  )),
  (301, 'summary', gh_lang_pack(
    $gh$A booth-side lamp gone dark. It can point toward privacy work.$gh$, $gh$Лампа у кабинки погасла. Она может указать на приватное дело.$gh$, $gh$Лампа біля кабінки згасла. Вона може вказати на приватну справу.$gh$, $gh$Лампа до кабинка е угаснала. Може да насочи към частна работа.$gh$, $gh$Лампа крај кабине се угасила. Може указати на приватни посао.$gh$, $gh$Una lámpara junto a la cabina se apagó. Puede señalar un asunto privado.$gh$, $gh$Une lampe près d'une alcôve s'est éteinte. Elle peut pointer vers une affaire privée.$gh$, $gh$Eine Lampe an der Nische ist erloschen. Sie kann auf eine private Sache weisen.$gh$, $gh$Una lampada accanto al separé si è spenta. Può indicare un affare privato.$gh$, $gh$Uma lâmpada junto à cabine apagou. Pode apontar para um serviço privado.$gh$, $gh$O lampă de lângă cabină s-a stins. Poate indica o treabă privată.$gh$, $gh$מנורה ליד התא כבתה. היא עשויה להצביע על עניין פרטי.$gh$, $gh$مصباح قرب المقصورة انطفأ. قد يدل على شأن خاص.$gh$, $gh$چراغ کنار غرفه خاموش شده است. شاید به کاری خصوصی اشاره کند.$gh$, $gh$بوتھ کے پاس چراغ بجھ گیا ہے۔ یہ کسی نجی کام کی طرف اشارہ کر سکتا ہے۔$gh$, $gh$कक्ष के पास दीपक बुझ गया है। यह निजी काम की ओर इशारा कर सकता है।$gh$, $gh$कॅबिनजवळचा दिवा विझला आहे. तो खाजगी कामाकडे इशारा करू शकतो.$gh$, $gh$बुथ छेउको बत्ती निभेको छ। यसले निजी कामतर्फ संकेत गर्न सक्छ।$gh$, $gh$বুথের পাশের প্রদীপ নিভেছে। এটি ব্যক্তিগত কাজের ইঙ্গিত দিতে পারে।$gh$, $gh$ตะเกียงข้างคูหาดับลง อาจชี้ไปสู่งานส่วนตัว$gh$, $gh$Μια λάμπα δίπλα στο θάλαμο έσβησε. Μπορεί να δείχνει ιδιωτική δουλειά.$gh$, $gh$Խցիկի կողքի լամպը մարել է։ Այն կարող է մատնանշել մասնավոր գործ։$gh$, $gh$კაბინასთან მდგომი ლამპა ჩამქრალია. შეიძლება კერძო საქმეზე მიანიშნებდეს.$gh$, $gh$부스 옆 램프가 꺼졌다. 사적인 일로 이어질 단서일 수 있다.$gh$, $gh$ブース脇のランプが消えている。私的な仕事への手がかりかもしれない。$gh$, $gh$包厢旁的灯熄了。它可能指向一件私密委托。$gh$
  )),
  (301, 'description', gh_lang_pack(
    $gh$A booth-side lamp gone dark.$gh$, $gh$Погасшая лампа у кабинки.$gh$, $gh$Згасла лампа біля кабінки.$gh$, $gh$Угаснала лампа до кабинка.$gh$, $gh$Угашена лампа крај кабине.$gh$, $gh$Una lámpara apagada junto a la cabina.$gh$, $gh$Une lampe éteinte près d'une alcôve.$gh$, $gh$Eine erloschene Lampe an der Nische.$gh$, $gh$Una lampada spenta accanto al separé.$gh$, $gh$Uma lâmpada apagada junto à cabine.$gh$, $gh$O lampă stinsă lângă cabină.$gh$, $gh$מנורה כבויה ליד התא.$gh$, $gh$مصباح مطفأ قرب المقصورة.$gh$, $gh$چراغی خاموش کنار غرفه.$gh$, $gh$بوتھ کے پاس بجھا چراغ۔$gh$, $gh$कक्ष के पास बुझा दीपक।$gh$, $gh$कॅबिनजवळचा विझलेला दिवा.$gh$, $gh$बुथ छेउको निभेको बत्ती।$gh$, $gh$বুথের পাশে নেভা প্রদীপ।$gh$, $gh$ตะเกียงดับข้างคูหา$gh$, $gh$Σβηστή λάμπα δίπλα στο θάλαμο.$gh$, $gh$Խցիկի կողքի մարած լամպ։$gh$, $gh$კაბინასთან ჩამქრალი ლამპა.$gh$, $gh$부스 옆의 꺼진 램프.$gh$, $gh$ブース脇の消えたランプ。$gh$, $gh$包厢旁熄灭的灯。$gh$
  )),
  (301, 'voice', gh_lang_pack(
    $gh$silent clue that changes the room's mood$gh$, $gh$безмолвная улика, меняющая настроение комнаты$gh$, $gh$мовчазна зачіпка, що змінює настрій кімнати$gh$, $gh$мълчалива улика, която променя настроението на стаята$gh$, $gh$неми траг који мења расположење собе$gh$, $gh$pista silenciosa que cambia el ánimo de la sala$gh$, $gh$indice muet qui change l'humeur de la pièce$gh$, $gh$stummer Hinweis, der die Stimmung des Raums verändert$gh$, $gh$indizio silenzioso che cambia l'umore della stanza$gh$, $gh$pista silenciosa que muda o clima da sala$gh$, $gh$indiciu tăcut care schimbă starea camerei$gh$, $gh$רמז שקט שמשנה את מצב הרוח בחדר$gh$, $gh$دليل صامت يغيّر مزاج الغرفة$gh$, $gh$سرنخی خاموش که حال اتاق را عوض می‌کند$gh$, $gh$خاموش اشارہ جو کمرے کا مزاج بدل دیتا ہے$gh$, $gh$मौन सुराग जो कमरे का मूड बदल देता है$gh$, $gh$खोलीचा मूड बदलणारा शांत धागा$gh$, $gh$कोठाको भाव बदल्ने मौन संकेत$gh$, $gh$নীরব সূত্র যা ঘরের মেজাজ বদলে দেয়$gh$, $gh$เบาะแสเงียบที่เปลี่ยนอารมณ์ของห้อง$gh$, $gh$σιωπηλή ένδειξη που αλλάζει τη διάθεση του δωματίου$gh$, $gh$լուռ հուշում, որ փոխում է սենյակի տրամադրությունը$gh$, $gh$მდუმარე მინიშნება, რომელიც ოთახის განწყობას ცვლის$gh$, $gh$방의 분위기를 바꾸는 조용한 단서$gh$, $gh$部屋の空気を変える沈黙の手がかり$gh$, $gh$改变房间气氛的无声线索$gh$
  )),

  (302, 'display_name', gh_lang_pack(
    $gh$Heavy Crate$gh$, $gh$Тяжелый ящик$gh$, $gh$Важкий ящик$gh$, $gh$Тежък сандък$gh$, $gh$Тежак сандук$gh$, $gh$Cajón pesado$gh$, $gh$Caisse lourde$gh$, $gh$Schwere Kiste$gh$, $gh$Cassa pesante$gh$, $gh$Caixote pesado$gh$, $gh$Ladă grea$gh$, $gh$ארגז כבד$gh$, $gh$صندوق ثقيل$gh$, $gh$جعبه سنگین$gh$, $gh$بھاری کریٹ$gh$, $gh$भारी बक्सा$gh$, $gh$जड खोका$gh$, $gh$गह्रौं बाकस$gh$, $gh$ভারী বাক্স$gh$, $gh$ลังหนัก$gh$, $gh$Βαρύ κιβώτιο$gh$, $gh$Ծանր արկղ$gh$, $gh$მძიმე ყუთი$gh$, $gh$무거운 상자$gh$, $gh$重い木箱$gh$, $gh$沉重木箱$gh$
  )),
  (302, 'summary', gh_lang_pack(
    $gh$A weathered wooden crate, too heavy to move casually.$gh$, $gh$Потрепанный деревянный ящик, слишком тяжелый для случайного толчка.$gh$, $gh$Потертий дерев'яний ящик, надто важкий для легкого поштовху.$gh$, $gh$Олющен дървен сандък, твърде тежък за небрежно местене.$gh$, $gh$Истрошен дрвени сандук, претежак за успутно померање.$gh$, $gh$Un cajón de madera gastada, demasiado pesado para moverlo sin esfuerzo.$gh$, $gh$Une caisse de bois usée, trop lourde pour la déplacer sans effort.$gh$, $gh$Eine verwitterte Holzkiste, zu schwer für beiläufiges Schieben.$gh$, $gh$Una cassa di legno consumata, troppo pesante da spostare per caso.$gh$, $gh$Um caixote de madeira gasto, pesado demais para mover sem esforço.$gh$, $gh$O ladă de lemn uzată, prea grea pentru a fi mutată lejer.$gh$, $gh$ארגז עץ שחוק, כבד מדי להזזה אגבית.$gh$, $gh$صندوق خشبي متآكل، أثقل من أن يُزاح بلا جهد.$gh$, $gh$جعبه‌ای چوبی و فرسوده، سنگین‌تر از آن که بی‌زحمت جابه‌جا شود.$gh$, $gh$پرانی لکڑی کا بھاری کریٹ، یوں ہی سرکانے کے لیے بہت وزنی۔$gh$, $gh$घिसा हुआ लकड़ी का बक्सा, यूँ ही हटाने के लिए बहुत भारी।$gh$, $gh$झिजलेला लाकडी खोका, सहज हलवायला फार जड.$gh$, $gh$पुरानो काठको बाकस, सजिलै सार्न धेरै भारी।$gh$, $gh$জীর্ণ কাঠের বাক্স, সহজে সরানোর জন্য খুব ভারী।$gh$, $gh$ลังไม้เก่า หนักเกินกว่าจะขยับเล่น ๆ$gh$, $gh$Φθαρμένο ξύλινο κιβώτιο, πολύ βαρύ για πρόχειρη μετακίνηση.$gh$, $gh$Մաշված փայտե արկղ, չափազանց ծանր՝ անփույթ շարժելու համար։$gh$, $gh$დაძველებული ხის ყუთი, ზედმეტად მძიმეა შემთხვევით გადასაწევად.$gh$, $gh$낡은 나무 상자. 가볍게 밀기엔 너무 무겁다.$gh$, $gh$風雨にさらされた木箱。気軽に動かすには重すぎる。$gh$, $gh$风化的木箱，重到不能随手挪开。$gh$
  )),
  (302, 'description', gh_lang_pack(
    $gh$A weathered crate half-blocking a side path.$gh$, $gh$Потрепанный ящик наполовину перекрывает боковой проход.$gh$, $gh$Потертий ящик наполовину перекриває бічний прохід.$gh$, $gh$Олющен сандък наполовина блокира странична пътека.$gh$, $gh$Истрошен сандук напола заклања споредни пролаз.$gh$, $gh$Un cajón gastado bloquea a medias un paso lateral.$gh$, $gh$Une caisse usée bloque à moitié un passage latéral.$gh$, $gh$Eine verwitterte Kiste versperrt halb einen Seitenweg.$gh$, $gh$Una cassa consumata blocca a metà un passaggio laterale.$gh$, $gh$Um caixote gasto bloqueia meio caminho lateral.$gh$, $gh$O ladă uzată blochează pe jumătate o potecă laterală.$gh$, $gh$ארגז שחוק חוסם למחצה מעבר צדדי.$gh$, $gh$صندوق متآكل يسد نصف ممر جانبي.$gh$, $gh$جعبه‌ای فرسوده نیمی از گذر کناری را بسته است.$gh$, $gh$پرانی کریٹ ایک سائیڈ راستہ آدھا روکے ہے۔$gh$, $gh$घिसा बक्सा एक किनारे का रास्ता आधा रोकता है।$gh$, $gh$झिजलेला खोका बाजूचा मार्ग अर्धा अडवतो.$gh$, $gh$पुरानो बाकसले छेउको बाटो आधा रोकेको छ।$gh$, $gh$জীর্ণ বাক্স পাশের পথ অর্ধেক আটকে রেখেছে।$gh$, $gh$ลังเก่าขวางทางแยกไว้ครึ่งหนึ่ง$gh$, $gh$Φθαρμένο κιβώτιο μισοκλείνει ένα πλαϊνό πέρασμα.$gh$, $gh$Մաշված արկղը կիսով չափ փակում է կողային անցումը։$gh$, $gh$დაძველებული ყუთი გვერდით ბილიკს ნახევრად კეტავს.$gh$, $gh$낡은 상자가 옆길을 반쯤 막고 있다.$gh$, $gh$古びた木箱が脇道を半分ふさいでいる。$gh$, $gh$破旧木箱半挡住一条侧路。$gh$
  )),

  (303, 'display_name', gh_lang_pack(
    $gh$Vendor's Cart$gh$, $gh$Тележка торговца$gh$, $gh$Візок торговця$gh$, $gh$Количка на търговец$gh$, $gh$Колица продавца$gh$, $gh$Carro de vendedor$gh$, $gh$Charrette de vendeur$gh$, $gh$Händlerkarren$gh$, $gh$Carretto del venditore$gh$, $gh$Carrinho de vendedor$gh$, $gh$Căruț de negustor$gh$, $gh$עגלת מוכר$gh$, $gh$عربة بائع$gh$, $gh$گاری فروشنده$gh$, $gh$دکاندار کی گاڑی$gh$, $gh$विक्रेता की गाड़ी$gh$, $gh$विक्रेत्याची गाडी$gh$, $gh$बिक्रेताको गाडा$gh$, $gh$বিক্রেতার গাড়ি$gh$, $gh$รถเข็นพ่อค้า$gh$, $gh$Καρότσι πωλητή$gh$, $gh$Վաճառողի սայլակ$gh$, $gh$გამყიდველის ურიკა$gh$, $gh$상인의 손수레$gh$, $gh$売り子の荷車$gh$, $gh$商贩手推车$gh$
  )),
  (303, 'summary', gh_lang_pack(
    $gh$A two-wheeled cart loaded with empty barrels, abandoned mid-aisle.$gh$, $gh$Двухколесная тележка с пустыми бочками, брошенная посреди прохода.$gh$, $gh$Двоколісний візок із порожніми діжками, покинутий посеред проходу.$gh$, $gh$Двуколесна количка с празни бъчви, изоставена насред прохода.$gh$, $gh$Двоточкаш са празним бурадима, остављен насред пролаза.$gh$, $gh$Carro de dos ruedas con barriles vacíos, abandonado en medio del pasillo.$gh$, $gh$Charrette à deux roues chargée de tonneaux vides, abandonnée au milieu de l'allée.$gh$, $gh$Zweirädriger Karren mit leeren Fässern, mitten im Gang stehen gelassen.$gh$, $gh$Carretto a due ruote carico di barili vuoti, abbandonato in mezzo al passaggio.$gh$, $gh$Carrinho de duas rodas com barris vazios, abandonado no meio do corredor.$gh$, $gh$Căruț cu două roți încărcat cu butoaie goale, abandonat pe culoar.$gh$, $gh$עגלה דו-גלגלית עמוסה חביות ריקות, נטושה באמצע המעבר.$gh$, $gh$عربة بعجلتين محملة ببراميل فارغة، متروكة وسط الممر.$gh$, $gh$گاری دوچرخی پر از بشکه‌های خالی، رها شده در میانه راهرو.$gh$, $gh$خالی بیرلوں سے لدی دو پہیوں کی گاڑی، راستے کے بیچ چھوڑی ہوئی۔$gh$, $gh$खाली पीपों से भरी दो-पहिया गाड़ी, रास्ते के बीच छोड़ी हुई।$gh$, $gh$रिकाम्या पिंपांनी भरलेली दोन चाकांची गाडी, मधोमध सोडलेली.$gh$, $gh$खाली पिपाहरूले भरिएको दुईपांग्रे गाडा, गल्लीको बीचमा छोडिएको।$gh$, $gh$খালি পিপেতে বোঝাই দুই চাকার গাড়ি, পথের মাঝখানে ফেলে রাখা।$gh$, $gh$รถเข็นสองล้อบรรทุกถังเปล่า ถูกทิ้งไว้กลางทางเดิน$gh$, $gh$Δίτροχο καρότσι φορτωμένο άδεια βαρέλια, παρατημένο στη μέση του διαδρόμου.$gh$, $gh$Երկանիվ սայլակ՝ դատարկ տակառներով, լքված անցուղու մեջտեղում։$gh$, $gh$ორბორბლიანი ურიკა ცარიელი კასრებით, შუა გასასვლელში მიტოვებული.$gh$, $gh$빈 통이 실린 두 바퀴 손수레가 통로 한가운데 버려져 있다.$gh$, $gh$空樽を積んだ二輪の荷車が通路の真ん中に放置されている。$gh$, $gh$装满空桶的两轮手推车，被丢在过道中央。$gh$
  )),
  (303, 'description', gh_lang_pack(
    $gh$A barrel-loaded handcart blocks traffic at an awkward angle.$gh$, $gh$Тележка с бочками неловко перекрывает движение.$gh$, $gh$Візок із діжками незручно перекриває рух.$gh$, $gh$Количка с бъчви неудобно блокира движението.$gh$, $gh$Колица са бурадима незгодно заклања пролаз.$gh$, $gh$Una carretilla con barriles bloquea el paso en un ángulo incómodo.$gh$, $gh$Une charrette de tonneaux bloque la circulation sous un angle gênant.$gh$, $gh$Ein Handkarren voller Fässer blockiert schräg den Verkehr.$gh$, $gh$Un carretto di barili blocca il traffico con un angolo scomodo.$gh$, $gh$Um carrinho de barris bloqueia a passagem em ângulo ruim.$gh$, $gh$Un cărucior cu butoaie blochează traficul într-un unghi incomod.$gh$, $gh$עגלת חביות חוסמת את המעבר בזווית גרועה.$gh$, $gh$عربة براميل تسد الحركة بزاوية مزعجة.$gh$, $gh$گاری بشکه‌ها با زاویه‌ای بد راه را بسته است.$gh$, $gh$بیرلوں والی گاڑی ٹیڑھے زاویے پر راستہ روکے ہے۔$gh$, $gh$पीपों वाली गाड़ी अटपटे कोण पर रास्ता रोकती है।$gh$, $gh$पिंपांची गाडी विचित्र कोनात रस्ता अडवते.$gh$, $gh$पिपा बोकेको गाडाले अप्ठ्यारो कोणमा बाटो रोकेको छ।$gh$, $gh$পিপে-ভরা গাড়ি অস্বস্তিকর কোণে চলাচল আটকে রেখেছে।$gh$, $gh$รถเข็นถังขวางทางในมุมเกะกะ$gh$, $gh$Καρότσι με βαρέλια κλείνει την κυκλοφορία σε άβολο γωνία.$gh$, $gh$Տակառներով սայլակը անհարմար անկյունով փակում է անցումը։$gh$, $gh$კასრებით დატვირთული ურიკა უხერხული კუთხით კეტავს გზას.$gh$, $gh$통을 실은 손수레가 어색한 각도로 길을 막는다.$gh$, $gh$樽を積んだ手押し車が妙な角度で通行をふさいでいる。$gh$, $gh$装桶的手推车以别扭角度挡住通行。$gh$
  )),

  (310, 'display_name', gh_lang_pack(
    $gh$Wooden Mug of Ale$gh$, $gh$Деревянная кружка эля$gh$, $gh$Дерев'яний кухоль елю$gh$, $gh$Дървена халба ейл$gh$, $gh$Дрвена кригла ела$gh$, $gh$Jarra de madera con ale$gh$, $gh$Chope de bière en bois$gh$, $gh$Holzkrug Ale$gh$, $gh$Boccale di legno di ale$gh$, $gh$Caneca de madeira de ale$gh$, $gh$Halbă de lemn cu bere$gh$, $gh$ספל עץ של אייל$gh$, $gh$قدح خشبي من الجعة$gh$, $gh$لیوان چوبی ایل$gh$, $gh$ایل کا لکڑی کا مگ$gh$, $gh$एले का लकड़ी का मग$gh$, $gh$एलेचा लाकडी मग$gh$, $gh$एलेको काठको मग$gh$, $gh$এলের কাঠের মগ$gh$, $gh$แก้วไม้ใส่เอล$gh$, $gh$Ξύλινη κούπα μπίρας$gh$, $gh$Էլի փայտե գավաթ$gh$, $gh$ელის ხის კათხა$gh$, $gh$나무 에일 잔$gh$, $gh$木製エールジョッキ$gh$, $gh$木制麦酒杯$gh$
  )),
  (310, 'summary', gh_lang_pack(
    $gh$A heavy wooden mug; foam settles over malt and woodsmoke.$gh$, $gh$Тяжелая деревянная кружка; пена оседает над солодом и древесным дымком.$gh$, $gh$Важкий дерев'яний кухоль; піна осідає над солодом і деревним димом.$gh$, $gh$Тежка дървена халба; пяната спада над малц и дървен дим.$gh$, $gh$Тешка дрвена кригла; пена се слеже над сладом и димом дрвета.$gh$, $gh$Jarra pesada de madera; la espuma cae sobre malta y humo de leña.$gh$, $gh$Lourde chope de bois; la mousse retombe sur le malt et la fumée de bois.$gh$, $gh$Schwerer Holzkrug; Schaum setzt sich über Malz und Holzrauch.$gh$, $gh$Pesante boccale di legno; la schiuma cala su malto e fumo di legna.$gh$, $gh$Caneca pesada de madeira; a espuma assenta sobre malte e fumaça de lenha.$gh$, $gh$Halbă grea de lemn; spuma se așază peste malț și fum de lemn.$gh$, $gh$ספל עץ כבד; הקצף שוקע מעל לתת ועשן עץ.$gh$, $gh$قدح خشبي ثقيل؛ تهبط الرغوة فوق رائحة الشعير ودخان الخشب.$gh$, $gh$لیوانی چوبی و سنگین؛ کف روی بوی مالت و دود چوب می‌نشیند.$gh$, $gh$بھاری لکڑی کا مگ؛ جھاگ مالٹ اور لکڑی کے دھوئیں پر بیٹھتی ہے۔$gh$, $gh$भारी लकड़ी का मग; झाग माल्ट और लकड़ी के धुएँ पर बैठता है।$gh$, $gh$जड लाकडी मग; फेस माल्ट आणि लाकडी धुरावर खाली बसतो.$gh$, $gh$गह्रौं काठको मग; फिँज माल्ट र काठको धुवाँमाथि बस्छ।$gh$, $gh$ভারী কাঠের মগ; ফেনা মাল্ট ও কাঠের ধোঁয়ার গন্ধে বসে যাচ্ছে।$gh$, $gh$แก้วไม้หนัก ฟองค่อย ๆ ยุบเหนือกลิ่นมอลต์และควันไม้$gh$, $gh$Βαριά ξύλινη κούπα· ο αφρός κάθεται πάνω σε βύνη και καπνό ξύλου.$gh$, $gh$Ծանր փայտե գավաթ․ փրփուրը նստում է ածիկի և փայտածխի հոտի վրա։$gh$, $gh$მძიმე ხის კათხა; ქაფი ალაოსა და ხის კვამლზე ჯდება.$gh$, $gh$무거운 나무 잔. 거품이 맥아와 나무 연기 향 위로 가라앉는다.$gh$, $gh$重い木製ジョッキ。泡が麦芽と薪煙の香りの上に沈む。$gh$, $gh$沉重木杯；泡沫在麦芽与木烟气味上慢慢落下。$gh$
  ))
),
entity_packs AS (
  SELECT entity_id, jsonb_object_agg(field_name, pack) AS pack
    FROM raw_packs
   GROUP BY entity_id
)
UPDATE entities AS entity
   SET i18n = COALESCE(entity.i18n, '{}'::jsonb) || entity_packs.pack
  FROM entity_packs
 WHERE entity.id = entity_packs.entity_id;
