-- Spec 110 - full language packs for authored quest cards and stable stage
-- labels. The nested keys match src/i18n.ts questStageI18nKey().

WITH raw_packs(entity_id, field_name, pack) AS (
  VALUES
  (500, 'display_name', gh_lang_pack(
    $gh$Mikka's Private Price$gh$, $gh$Приватная цена Микки$gh$, $gh$Приватна ціна Мікки$gh$, $gh$Частната цена на Мика$gh$, $gh$Микина приватна цена$gh$, $gh$El precio privado de Mikka$gh$, $gh$Le prix privé de Mikka$gh$, $gh$Mikkas privater Preis$gh$, $gh$Il prezzo privato di Mikka$gh$, $gh$O preço privado de Mikka$gh$, $gh$Prețul privat al Mikkăi$gh$, $gh$המחיר הפרטי של מיקה$gh$, $gh$ثمن ميكا الخاص$gh$, $gh$بهای خصوصی میکا$gh$, $gh$میکا کی نجی قیمت$gh$, $gh$मिक्का की निजी कीमत$gh$, $gh$मिक्काची खाजगी किंमत$gh$, $gh$मिक्काको निजी मूल्य$gh$, $gh$মিক্কার ব্যক্তিগত দাম$gh$, $gh$ราคาส่วนตัวของ Mikka$gh$, $gh$Το ιδιωτικό τίμημα της Mikka$gh$, $gh$Միկկայի մասնավոր գինը$gh$, $gh$მიკკას კერძო ფასი$gh$, $gh$미카의 사적 대가$gh$, $gh$ミッカの私的な代価$gh$, $gh$米卡的私下代价$gh$
  )),
  (500, 'summary', gh_lang_pack(
    $gh$Negotiate Mikka's private service through explicit agreement, payment, or a mutually accepted substitute.$gh$, $gh$Договорись о приватной услуге Микки через явное согласие, оплату или взаимно принятую замену.$gh$, $gh$Домовся про приватну послугу Мікки через явну згоду, оплату або взаємно прийняту заміну.$gh$, $gh$Договори частната услуга на Мика чрез ясно съгласие, плащане или взаимно приета замяна.$gh$, $gh$Испреговарај Микину приватну услугу кроз јасан договор, плаћање или обострано прихваћену замену.$gh$, $gh$Negocia el servicio privado de Mikka mediante acuerdo explícito, pago o sustituto aceptado por ambos.$gh$, $gh$Négocie le service privé de Mikka par accord explicite, paiement ou substitut accepté par les deux parties.$gh$, $gh$Verhandle Mikkas privaten Dienst durch klare Zustimmung, Zahlung oder beiderseits akzeptierten Ersatz.$gh$, $gh$Negozia il servizio privato di Mikka tramite accordo esplicito, pagamento o sostituto accettato da entrambi.$gh$, $gh$Negocie o serviço privado de Mikka por acordo explícito, pagamento ou substituto aceito por ambos.$gh$, $gh$Negociază serviciul privat al Mikkăi prin acord explicit, plată sau înlocuire acceptată de ambele părți.$gh$, $gh$נהל את השירות הפרטי של מיקה דרך הסכמה מפורשת, תשלום או תחליף שמקובל על שני הצדדים.$gh$, $gh$فاوض على خدمة ميكا الخاصة عبر اتفاق صريح أو دفع أو بديل مقبول من الطرفين.$gh$, $gh$خدمت خصوصی میکا را با توافق روشن، پرداخت یا جایگزینی پذیرفته‌شده از دو طرف مذاکره کن.$gh$, $gh$میکا کی نجی خدمت کو صاف رضامندی، ادائیگی یا دونوں کی قبول کردہ بدل کے ذریعے طے کرو۔$gh$, $gh$मिक्का की निजी सेवा को स्पष्ट सहमति, भुगतान या दोनों द्वारा स्वीकार विकल्प से तय करो।$gh$, $gh$मिक्काची खाजगी सेवा स्पष्ट संमती, पेमेंट किंवा दोघांनी मान्य केलेल्या पर्यायातून ठरव.$gh$, $gh$मिक्काको निजी सेवा स्पष्ट सहमति, भुक्तानी वा दुवैले मानेको विकल्पबाट तय गर।$gh$, $gh$মিক্কার ব্যক্তিগত সেবা স্পষ্ট সম্মতি, পেমেন্ট বা দুজনের মেনে নেওয়া বিকল্পে দর-কষাকষি করো।$gh$, $gh$ต่อรองบริการส่วนตัวของ Mikka ผ่านข้อตกลงชัดเจน การจ่าย หรือสิ่งทดแทนที่ทั้งสองฝ่ายยอมรับ$gh$, $gh$Διαπραγματεύσου την ιδιωτική υπηρεσία της Mikka με ρητή συμφωνία, πληρωμή ή αμοιβαία αποδεκτό υποκατάστατο.$gh$, $gh$Բանակցիր Միկկայի մասնավոր ծառայությունը հստակ համաձայնությամբ, վճարմամբ կամ փոխադարձ ընդունված փոխարինմամբ։$gh$, $gh$მიკკას კერძო მომსახურება მოილაპარაკე აშკარა შეთანხმებით, გადახდით ან ორმხრივად მიღებული შემცვლელით.$gh$, $gh$명시적 합의, 지불, 또는 양측이 받아들인 대체 조건으로 미카의 사적 서비스를 협상한다.$gh$, $gh$明示の合意、支払い、または双方が受け入れる代替条件で、ミッカの私的サービスを交渉する。$gh$, $gh$通过明确同意、付款或双方接受的替代条件，谈妥米卡的私下服务。$gh$
  )),
  (500, 'profile.stages.approach.name', gh_lang_pack(
    $gh$Approach$gh$, $gh$Подход$gh$, $gh$Підхід$gh$, $gh$Подход$gh$, $gh$Приступ$gh$, $gh$Acercamiento$gh$, $gh$Approche$gh$, $gh$Annäherung$gh$, $gh$Approccio$gh$, $gh$Abordagem$gh$, $gh$Abordare$gh$, $gh$גישה$gh$, $gh$اقتراب$gh$, $gh$نزدیک‌شدن$gh$, $gh$قریب آنا$gh$, $gh$निकट जाना$gh$, $gh$जवळ जाणे$gh$, $gh$नजिकिनु$gh$, $gh$কাছে আসা$gh$, $gh$เข้าหา$gh$, $gh$Προσέγγιση$gh$, $gh$Մոտեցում$gh$, $gh$მიახლოება$gh$, $gh$접근$gh$, $gh$接近$gh$, $gh$接近$gh$
  )),
  (500, 'profile.stages.approach.description', gh_lang_pack(
    $gh$The player opens the private negotiation or offer; nothing is canon until commitment is explicit.$gh$, $gh$Игрок открывает приватные переговоры или предложение; ничто не канонично, пока обязательство не выражено явно.$gh$, $gh$Гравець відкриває приватні переговори або пропозицію; нічого не є каноном, доки зобов'язання не явне.$gh$, $gh$Играчът започва частните преговори или оферта; нищо не е канон, докато ангажиментът не е ясен.$gh$, $gh$Играч отвара приватне преговоре или понуду; ништа није канон док обавеза није јасна.$gh$, $gh$El jugador abre la negociación u oferta privada; nada es canon hasta que el compromiso sea explícito.$gh$, $gh$Le joueur ouvre la négociation ou l'offre privée ; rien n'est canon tant que l'engagement n'est pas explicite.$gh$, $gh$Der Spieler eröffnet private Verhandlung oder Angebot; nichts ist kanonisch, bis die Verpflichtung ausdrücklich ist.$gh$, $gh$Il giocatore apre la negoziazione o offerta privata; nulla è canonico finché l'impegno non è esplicito.$gh$, $gh$O jogador abre a negociação ou oferta privada; nada é cânone até o compromisso ser explícito.$gh$, $gh$Jucătorul deschide negocierea sau oferta privată; nimic nu e canonic până când angajamentul nu este explicit.$gh$, $gh$השחקן פותח משא ומתן או הצעה פרטית; דבר אינו קאנוני עד שההתחייבות מפורשת.$gh$, $gh$يفتح اللاعب التفاوض أو العرض الخاص؛ لا يصبح شيء قانونياً حتى يكون الالتزام صريحاً.$gh$, $gh$بازیکن مذاکره یا پیشنهاد خصوصی را آغاز می‌کند؛ تا تعهد روشن نباشد چیزی کانونی نیست.$gh$, $gh$کھلاڑی نجی بات چیت یا پیشکش شروع کرتا ہے؛ جب تک عہد صاف نہ ہو کچھ کینن نہیں۔$gh$, $gh$खिलाड़ी निजी बातचीत या प्रस्ताव शुरू करता है; प्रतिबद्धता स्पष्ट होने तक कुछ कैनन नहीं।$gh$, $gh$खेळाडू खाजगी वाटाघाटी किंवा प्रस्ताव सुरू करतो; स्पष्ट बांधिलकी येईपर्यंत काहीही कॅनन नाही.$gh$, $gh$खेलाडी निजी वार्ता वा प्रस्ताव सुरु गर्छ; प्रतिबद्धता स्पष्ट नभएसम्म केही क्यानन हुँदैन।$gh$, $gh$খেলোয়াড় ব্যক্তিগত দর-কষাকষি বা প্রস্তাব শুরু করে; অঙ্গীকার স্পষ্ট না হওয়া পর্যন্ত কিছু ক্যানন নয়।$gh$, $gh$ผู้เล่นเปิดการเจรจาหรือข้อเสนอส่วนตัว ยังไม่มีอะไรเป็นแคนนอนจนกว่าการตกลงจะชัดเจน$gh$, $gh$Ο παίκτης ανοίγει ιδιωτική διαπραγμάτευση ή προσφορά· τίποτα δεν είναι κανόνας μέχρι η δέσμευση να γίνει ρητή.$gh$, $gh$Խաղացողը բացում է մասնավոր բանակցությունը կամ առաջարկը. ոչինչ կանոնիկ չէ, մինչև պարտավորությունը հստակ չլինի։$gh$, $gh$მოთამაშე ხსნის კერძო მოლაპარაკებას ან შეთავაზებას; არაფერი ხდება კანონიკურად, სანამ ვალდებულება აშკარა არ არის.$gh$, $gh$플레이어가 사적 협상이나 제안을 연다. 명시적 약속 전까지 아무것도 정사가 아니다.$gh$, $gh$プレイヤーが私的交渉または提案を始める。明示の約束があるまで何も正史ではない。$gh$, $gh$玩家开启私下谈判或提议；承诺明确前，一切都不是正史。$gh$
  )),
  (500, 'profile.stages.consent.name', gh_lang_pack(
    $gh$Consent and price$gh$, $gh$Согласие и цена$gh$, $gh$Згода і ціна$gh$, $gh$Съгласие и цена$gh$, $gh$Сагласност и цена$gh$, $gh$Consentimiento y precio$gh$, $gh$Consentement et prix$gh$, $gh$Zustimmung und Preis$gh$, $gh$Consenso e prezzo$gh$, $gh$Consentimento e preço$gh$, $gh$Consimțământ și preț$gh$, $gh$הסכמה ומחיר$gh$, $gh$موافقة وثمن$gh$, $gh$رضایت و بها$gh$, $gh$رضامندی اور قیمت$gh$, $gh$सहमति और कीमत$gh$, $gh$संमती आणि किंमत$gh$, $gh$सहमति र मूल्य$gh$, $gh$সম্মতি ও দাম$gh$, $gh$ความยินยอมและราคา$gh$, $gh$Συναίνεση και τίμημα$gh$, $gh$Համաձայնություն և գին$gh$, $gh$თანხმობა და ფასი$gh$, $gh$동의와 대가$gh$, $gh$同意と代価$gh$, $gh$同意与代价$gh$
  )),
  (500, 'profile.stages.consent.description', gh_lang_pack(
    $gh$Mikka accepts a concrete bargain, payment, or substitute; paid gold must be recorded by the payment recipe tools.$gh$, $gh$Микка принимает конкретную сделку, оплату или замену; золото должно быть записано инструментами payment recipe.$gh$, $gh$Мікка приймає конкретну угоду, оплату або заміну; золото має бути записане інструментами payment recipe.$gh$, $gh$Мика приема конкретна сделка, плащане или замяна; платеното злато трябва да се запише с инструментите на рецептата за плащане.$gh$, $gh$Мика прихвата конкретан договор, плаћање или замену; плаћено злато морају записати алати рецепта плаћања.$gh$, $gh$Mikka acepta un trato, pago o sustituto concreto; el oro pagado debe registrarse con las herramientas de receta de pago.$gh$, $gh$Mikka accepte un marché, paiement ou substitut concret ; l'or payé doit être enregistré par les outils de recette de paiement.$gh$, $gh$Mikka akzeptiert Handel, Zahlung oder Ersatz konkret; gezahltes Gold muss durch Zahlungsrezept-Werkzeuge erfasst werden.$gh$, $gh$Mikka accetta un patto, pagamento o sostituto concreto; l'oro pagato va registrato dagli strumenti della ricetta di pagamento.$gh$, $gh$Mikka aceita trato, pagamento ou substituto concreto; ouro pago deve ser registrado pelas ferramentas da receita de pagamento.$gh$, $gh$Mikka acceptă o înțelegere, plată sau înlocuire concretă; aurul plătit trebuie înregistrat de uneltele rețetei de plată.$gh$, $gh$מיקה מקבלת עסקה, תשלום או תחליף ממשי; זהב ששולם חייב להירשם בכלי מתכון התשלום.$gh$, $gh$تقبل ميكا صفقة أو دفعاً أو بديلاً محدداً؛ الذهب المدفوع يجب تسجيله بأدوات وصفة الدفع.$gh$, $gh$میکا معامله، پرداخت یا جایگزین مشخص را می‌پذیرد؛ طلای پرداختی باید با ابزارهای دستور پرداخت ثبت شود.$gh$, $gh$میکا ٹھوس سودا، ادائیگی یا بدل قبول کرتی ہے؛ ادا شدہ سونا payment recipe ٹولز سے درج ہونا چاہیے۔$gh$, $gh$मिक्का ठोस सौदा, भुगतान या विकल्प स्वीकारती है; चुकाया सोना payment recipe उपकरणों से दर्ज होना चाहिए।$gh$, $gh$मिक्का ठोस करार, पेमेंट किंवा पर्याय स्वीकारते; दिलेले सोने payment recipe साधनांनी नोंदले पाहिजे.$gh$, $gh$मिक्काले ठोस सम्झौता, भुक्तानी वा विकल्प स्वीकार्छे; तिरेको सुन payment recipe उपकरणले दर्ता गर्नुपर्छ।$gh$, $gh$মিক্কা নির্দিষ্ট চুক্তি, পেমেন্ট বা বিকল্প মেনে নেয়; দেওয়া সোনা payment recipe টুলে নথিভুক্ত হতে হবে।$gh$, $gh$Mikka ยอมรับข้อตกลง การจ่าย หรือสิ่งทดแทนที่ชัดเจน ทองที่จ่ายต้องบันทึกด้วยเครื่องมือ payment recipe$gh$, $gh$Η Mikka δέχεται συγκεκριμένη συμφωνία, πληρωμή ή υποκατάστατο· το χρυσάφι πρέπει να καταγραφεί με τα εργαλεία συνταγής πληρωμής.$gh$, $gh$Միկկան ընդունում է կոնկրետ գործարք, վճարում կամ փոխարինում. վճարված ոսկին պետք է գրանցվի payment recipe գործիքներով։$gh$, $gh$მიკკა იღებს კონკრეტულ გარიგებას, გადახდას ან შემცვლელს; გადახდილი ოქრო payment recipe ხელსაწყოებმა უნდა ჩაიწერონ.$gh$, $gh$미카가 구체적 거래, 지불, 대체 조건을 받아들인다. 지불된 금화는 payment recipe 도구로 기록해야 한다.$gh$, $gh$ミッカが具体的な取引、支払い、代替条件を受け入れる。支払われた金は payment recipe ツールで記録されなければならない。$gh$, $gh$米卡接受具体交易、付款或替代条件；支付的金币必须由 payment recipe 工具记录。$gh$
  )),
  (500, 'profile.stages.foreplay.name', gh_lang_pack(
    $gh$Escalation$gh$, $gh$Эскалация$gh$, $gh$Ескалація$gh$, $gh$Ескалация$gh$, $gh$Ескалација$gh$, $gh$Escalada$gh$, $gh$Escalade$gh$, $gh$Steigerung$gh$, $gh$Escalatione$gh$, $gh$Escalada$gh$, $gh$Escaladare$gh$, $gh$הסלמה$gh$, $gh$تصعيد$gh$, $gh$اوج‌گیری$gh$, $gh$شدت$gh$, $gh$वृद्धि$gh$, $gh$वाढ$gh$, $gh$बढोत्तरी$gh$, $gh$তীব্রতা$gh$, $gh$ไต่ระดับ$gh$, $gh$Κλιμάκωση$gh$, $gh$Սրում$gh$, $gh$გამძაფრება$gh$, $gh$고조$gh$, $gh$高まり$gh$, $gh$升级$gh$
  )),
  (500, 'profile.stages.foreplay.description', gh_lang_pack(
    $gh$The scene intensifies through mutual action and recorded memories or string changes, not invented hidden meters.$gh$, $gh$Сцена усиливается через взаимные действия и записанные памяти или strings, а не через выдуманные скрытые шкалы.$gh$, $gh$Сцена посилюється через взаємні дії та записані спогади або strings, а не через вигадані приховані шкали.$gh$, $gh$Сцената се усилва чрез взаимни действия и записани спомени или strings, не чрез измислени скрити измерители.$gh$, $gh$Сцена се појачава кроз узајамне радње и записана сећања или strings, не измишљене скривене мераче.$gh$, $gh$La escena se intensifica mediante acciones mutuas y recuerdos o strings registrados, no medidores ocultos inventados.$gh$, $gh$La scène s'intensifie par actions mutuelles et souvenirs ou strings enregistrés, pas par jauges cachées inventées.$gh$, $gh$Die Szene steigert sich durch gegenseitige Handlungen und aufgezeichnete Erinnerungen oder Strings, nicht erfundene versteckte Werte.$gh$, $gh$La scena cresce tramite azioni reciproche e memorie o stringhe registrate, non tramite misuratori nascosti inventati.$gh$, $gh$A cena se intensifica por ações mútuas e memórias ou strings registradas, não por medidores ocultos inventados.$gh$, $gh$Scena se intensifică prin acțiuni reciproce și amintiri sau strings înregistrate, nu prin contoare ascunse inventate.$gh$, $gh$הסצנה מתעצמת דרך פעולות הדדיות וזיכרונות או strings שנרשמו, לא דרך מדדים חבויים שהומצאו.$gh$, $gh$يتصاعد المشهد عبر أفعال متبادلة وذكريات أو strings مسجلة، لا عبر مقاييس مخفية مخترعة.$gh$, $gh$صحنه با کنش متقابل و خاطره‌ها یا strings ثبت‌شده شدت می‌گیرد، نه با مترهای پنهانِ ساختگی.$gh$, $gh$منظر باہمی عمل اور درج یادوں یا strings سے بڑھتا ہے، گھڑے ہوئے پوشیدہ میٹرز سے نہیں۔$gh$, $gh$दृश्य पारस्परिक क्रिया और दर्ज स्मृतियों या strings से बढ़ता है, गढ़े हुए छिपे मीटरों से नहीं।$gh$, $gh$दृश्य परस्पर कृती आणि नोंदलेल्या स्मृती किंवा strings मुळे वाढते, बनावट लपलेल्या मीटरमुळे नाही.$gh$, $gh$दृश्य पारस्परिक काम र दर्ता स्मृति वा strings बाट बढ्छ, बनाइएका लुकेका मीटरबाट होइन।$gh$, $gh$দৃশ্য পারস্পরিক কাজ ও নথিভুক্ত স্মৃতি বা strings দিয়ে তীব্র হয়, বানানো গোপন মিটার দিয়ে নয়।$gh$, $gh$ฉากไต่ระดับผ่านการกระทำร่วมกันและความทรงจำหรือ strings ที่บันทึกไว้ ไม่ใช่มิเตอร์ลับที่แต่งขึ้น$gh$, $gh$Η σκηνή εντείνεται με αμοιβαίες πράξεις και καταγεγραμμένες μνήμες ή strings, όχι με επινοημένους κρυφούς μετρητές.$gh$, $gh$Տեսարանը սրվում է փոխադարձ գործողությամբ և գրանցված հիշողություններով կամ strings-ներով, ոչ թե հորինված թաքնված չափիչներով։$gh$, $gh$სცენა მძაფრდება ორმხრივი მოქმედებით და ჩაწერილი მოგონებებით ან strings-ებით, არა გამოგონილი ფარული მრიცხველებით.$gh$, $gh$장면은 상호 행동과 기록된 기억 또는 strings로 고조된다. 꾸며낸 숨은 미터로 고조되지 않는다.$gh$, $gh$場面は相互行動と記録された記憶または strings によって高まる。作られた隠しメーターではない。$gh$, $gh$场景通过相互行动以及已记录的记忆或 strings 升级，而不是靠编造的隐藏计量条。$gh$
  )),
  (500, 'profile.stages.climax.name', gh_lang_pack(
    $gh$Climax$gh$, $gh$Кульминация$gh$, $gh$Кульмінація$gh$, $gh$Кулминация$gh$, $gh$Кулминација$gh$, $gh$Clímax$gh$, $gh$Climax$gh$, $gh$Höhepunkt$gh$, $gh$Culmine$gh$, $gh$Clímax$gh$, $gh$Climax$gh$, $gh$שיא$gh$, $gh$ذروة$gh$, $gh$اوج$gh$, $gh$عروج$gh$, $gh$चरम$gh$, $gh$परमोच्च बिंदू$gh$, $gh$चरमबिन्दु$gh$, $gh$চূড়ান্ত মুহূর্ত$gh$, $gh$จุดสูงสุด$gh$, $gh$Κορύφωση$gh$, $gh$Գագաթնակետ$gh$, $gh$კულმინაცია$gh$, $gh$절정$gh$, $gh$クライマックス$gh$, $gh$高潮$gh$
  )),
  (500, 'profile.stages.climax.description', gh_lang_pack(
    $gh$The decisive beat lands; advance here only when the fiction itself reaches the peak.$gh$, $gh$Наступает решающий такт; переходи сюда только когда сама история достигает пика.$gh$, $gh$Настає вирішальний такт; переходь сюди лише коли сама історія сягає піку.$gh$, $gh$Решаващият момент настъпва; премини тук само когато самата история стигне върха.$gh$, $gh$Одлучујући тренутак пада; пређи овде само кад сама фикција досегне врх.$gh$, $gh$Llega el momento decisivo; avanza aquí solo cuando la ficción alcance su pico.$gh$, $gh$Le moment décisif tombe ; avance ici seulement quand la fiction atteint son sommet.$gh$, $gh$Der entscheidende Schlag landet; rücke erst hierher vor, wenn die Fiktion selbst den Höhepunkt erreicht.$gh$, $gh$Arriva il momento decisivo; avanza qui solo quando la finzione raggiunge il picco.$gh$, $gh$O momento decisivo chega; avance aqui só quando a ficção alcançar o pico.$gh$, $gh$Momentul decisiv cade; avansează aici doar când ficțiunea atinge vârful.$gh$, $gh$הרגע המכריע מגיע; התקדם לכאן רק כשהבדיה עצמה מגיעה לשיא.$gh$, $gh$تحل اللحظة الحاسمة؛ تقدّم هنا فقط عندما تبلغ الحكاية نفسها الذروة.$gh$, $gh$ضرباهنگ تعیین‌کننده فرامی‌رسد؛ فقط وقتی خود روایت به اوج رسید به اینجا برو.$gh$, $gh$فیصلہ کن لمحہ آتا ہے؛ یہاں تبھی بڑھو جب کہانی خود عروج پر پہنچے۔$gh$, $gh$निर्णायक क्षण आता है; यहाँ तभी बढ़ो जब कथा स्वयं चरम पर पहुँचे।$gh$, $gh$निर्णायक क्षण येतो; कथा स्वतः शिखरावर पोचल्यावरच इथे जा.$gh$, $gh$निर्णायक क्षण आउँछ; कथा आफैं चरममा पुग्दा मात्र यहाँ अघि बढ।$gh$, $gh$নির্ণায়ক মুহূর্ত আসে; কাহিনি নিজে চূড়ায় পৌঁছালে তবেই এখানে এগোও।$gh$, $gh$จังหวะตัดสินมาถึง เข้าขั้นนี้เฉพาะเมื่อเรื่องเล่าไปถึงจุดสูงสุดเอง$gh$, $gh$Η αποφασιστική στιγμή πέφτει· προχώρησε εδώ μόνο όταν η ίδια η μυθοπλασία φτάσει στην κορυφή.$gh$, $gh$Վճռական հարվածը հասնում է. անցիր այստեղ միայն երբ պատմությունն ինքը գագաթնակետին հասնի։$gh$, $gh$გადამწყვეტი წამი დგება; აქ გადადი მხოლოდ მაშინ, როცა თავად ფიქცია მწვერვალს აღწევს.$gh$, $gh$결정적 순간이 도착한다. 허구 자체가 정점에 닿았을 때만 여기로 진행한다.$gh$, $gh$決定的な拍が来る。物語そのものが頂点に達した時だけここへ進める。$gh$, $gh$决定性节拍落下；只有当叙事本身抵达顶点时才推进到这里。$gh$
  )),
  (500, 'profile.stages.aftermath.name', gh_lang_pack(
    $gh$Aftermath$gh$, $gh$Последствия$gh$, $gh$Наслідки$gh$, $gh$Последствия$gh$, $gh$Последице$gh$, $gh$Consecuencias$gh$, $gh$Retombées$gh$, $gh$Nachklang$gh$, $gh$Conseguenze$gh$, $gh$Consequências$gh$, $gh$Urmări$gh$, $gh$השלכות$gh$, $gh$ما بعد الحدث$gh$, $gh$پیامد$gh$, $gh$بعد کے اثرات$gh$, $gh$परिणाम$gh$, $gh$परिणाम$gh$, $gh$परिणाम$gh$, $gh$পরিণতি$gh$, $gh$ผลลัพธ์หลังเหตุการณ์$gh$, $gh$Επακόλουθα$gh$, $gh$Հետևանքներ$gh$, $gh$შედეგები$gh$, $gh$여파$gh$, $gh$余波$gh$, $gh$后果$gh$
  )),
  (500, 'profile.stages.aftermath.description', gh_lang_pack(
    $gh$Close the encounter with quest completion, rewards, memories, strings, and any eligible partner move.$gh$, $gh$Закрой встречу завершением квеста, наградами, памятью, strings и подходящим partner move.$gh$, $gh$Закрий зустріч завершенням квесту, нагородами, спогадами, strings і придатним partner move.$gh$, $gh$Затвори срещата със завършване на куеста, награди, спомени, strings и подходящ partner move.$gh$, $gh$Затвори сусрет завршетком квеста, наградама, сећањима, strings и одговарајућим partner move.$gh$, $gh$Cierra el encuentro con finalización de misión, recompensas, recuerdos, strings y cualquier movimiento de pareja válido.$gh$, $gh$Clôture la rencontre avec fin de quête, récompenses, souvenirs, strings et tout mouvement de partenaire éligible.$gh$, $gh$Schließe die Begegnung mit Questabschluss, Belohnungen, Erinnerungen, Strings und passendem Partnermanöver.$gh$, $gh$Chiudi l'incontro con completamento quest, ricompense, memorie, strings e ogni mossa partner valida.$gh$, $gh$Feche o encontro com conclusão de missão, recompensas, memórias, strings e qualquer movimento de parceiro elegível.$gh$, $gh$Închide întâlnirea cu finalizarea questului, recompense, amintiri, strings și orice mișcare de partener eligibilă.$gh$, $gh$סגור את המפגש עם השלמת קווסט, פרסים, זיכרונות, strings וכל מהלך בן זוג מתאים.$gh$, $gh$أغلق اللقاء بإكمال المهمة والمكافآت والذكريات وstrings وأي حركة شريك مؤهلة.$gh$, $gh$دیدار را با تکمیل کوئست، پاداش‌ها، خاطره‌ها، strings و هر حرکت شریک مجاز ببند.$gh$, $gh$ملاقات کو کوئسٹ مکمل، انعامات، یادوں، strings اور کسی اہل partner move سے بند کرو۔$gh$, $gh$मुठभेड़ को quest completion, पुरस्कार, स्मृतियाँ, strings और योग्य partner move से बंद करो।$gh$, $gh$भेट क्वेस्ट पूर्णता, बक्षिसे, स्मृती, strings आणि योग्य partner move ने बंद कर.$gh$, $gh$भेटलाई क्वेस्ट पूरा, पुरस्कार, स्मृति, strings र योग्य partner move सहित बन्द गर।$gh$, $gh$ঘটনাটি কোয়েস্ট সমাপ্তি, পুরস্কার, স্মৃতি, strings এবং যোগ্য partner move দিয়ে বন্ধ করো।$gh$, $gh$ปิดการพบกันด้วยการจบเควสต์ รางวัล ความทรงจำ strings และ partner move ที่เข้าเงื่อนไข$gh$, $gh$Κλείσε τη συνάντηση με ολοκλήρωση αποστολής, ανταμοιβές, μνήμες, strings και κάθε έγκυρη κίνηση συντρόφου.$gh$, $gh$Փակիր հանդիպումը քվեստի ավարտով, պարգևներով, հիշողություններով, strings-ներով և թույլատրելի partner move-ով։$gh$, $gh$შეხვედრა დახურე ქვესტის დასრულებით, ჯილდოებით, მოგონებებით, strings-ებით და შესაბამისი partner move-ით.$gh$, $gh$퀘스트 완료, 보상, 기억, strings, 적격 파트너 동작으로 조우를 닫는다.$gh$, $gh$クエスト完了、報酬、記憶、strings、該当する partner move で遭遇を閉じる。$gh$, $gh$用任务完成、奖励、记忆、strings 以及符合条件的 partner move 收束这次遭遇。$gh$
  )),

  (700, 'display_name', gh_lang_pack(
    $gh$Mikka's Trust$gh$, $gh$Доверие Микки$gh$, $gh$Довіра Мікки$gh$, $gh$Доверието на Мика$gh$, $gh$Микино поверење$gh$, $gh$La confianza de Mikka$gh$, $gh$La confiance de Mikka$gh$, $gh$Mikkas Vertrauen$gh$, $gh$La fiducia di Mikka$gh$, $gh$A confiança de Mikka$gh$, $gh$Încrederea Mikkăi$gh$, $gh$האמון של מיקה$gh$, $gh$ثقة ميكا$gh$, $gh$اعتماد میکا$gh$, $gh$میکا کا اعتماد$gh$, $gh$मिक्का का भरोसा$gh$, $gh$मिक्काचा विश्वास$gh$, $gh$मिक्काको विश्वास$gh$, $gh$মিক্কার বিশ্বাস$gh$, $gh$ความไว้ใจของ Mikka$gh$, $gh$Η εμπιστοσύνη της Mikka$gh$, $gh$Միկկայի վստահությունը$gh$, $gh$მიკკას ნდობა$gh$, $gh$미카의 신뢰$gh$, $gh$ミッカの信頼$gh$, $gh$米卡的信任$gh$
  )),
  (700, 'summary', gh_lang_pack(
    $gh$Earn enough strings with Mikka through helpful action to unlock a lasting information-broker discount.$gh$, $gh$Заработай достаточно strings у Микки полезными действиями, чтобы открыть постоянную скидку инфоброкера.$gh$, $gh$Зароби достатньо strings у Мікки корисними діями, щоб відкрити постійну знижку інфоброкера.$gh$, $gh$Спечели достатъчно strings при Мика чрез полезни действия, за да отключиш трайна отстъпка от информационния брокер.$gh$, $gh$Заради довољно strings код Мике корисним радњама да откључаш трајни попуст инфо-брокера.$gh$, $gh$Gana suficientes strings con Mikka mediante acciones útiles para desbloquear un descuento duradero de informante.$gh$, $gh$Gagne assez de strings auprès de Mikka par des actions utiles pour débloquer une remise durable d'informatrice.$gh$, $gh$Verdiene genug Strings bei Mikka durch hilfreiche Taten, um einen dauerhaften Info-Broker-Rabatt freizuschalten.$gh$, $gh$Ottieni abbastanza strings con Mikka tramite azioni utili per sbloccare uno sconto duraturo da broker d'informazioni.$gh$, $gh$Ganhe strings suficientes com Mikka por ações úteis para desbloquear desconto duradouro de corretora de informações.$gh$, $gh$Câștigă destule strings cu Mikka prin acțiuni utile ca să deblochezi o reducere permanentă de broker de informații.$gh$, $gh$צבור מספיק strings אצל מיקה דרך מעשים מועילים כדי לפתוח הנחת מתווכת מידע קבועה.$gh$, $gh$اكسب strings كافية لدى ميكا عبر أفعال نافعة لفتح خصم دائم عند وسيطة المعلومات.$gh$, $gh$با کارهای مفید نزد میکا strings کافی به دست آور تا تخفیف پایدار کارگزار اطلاعات باز شود.$gh$, $gh$مفید عمل سے میکا کے ساتھ کافی strings کماؤ تاکہ مستقل انفارمیشن بروکر رعایت کھلے۔$gh$, $gh$मददगार कामों से मिक्का के साथ पर्याप्त strings कमाओ ताकि स्थायी सूचना-ब्रोकर छूट खुले।$gh$, $gh$उपयुक्त कृतींनी मिक्काकडे पुरेसे strings कमाव, जेणेकरून कायम माहिती-दलाल सवलत उघडेल.$gh$, $gh$सहयोगी कामबाट मिक्कासँग पर्याप्त strings कमाऊ, ताकि स्थायी सूचना-ब्रोकर छुट खुलोस्।$gh$, $gh$উপকারী কাজে মিক্কার কাছে যথেষ্ট strings অর্জন করো, যাতে স্থায়ী তথ্য-ব্রোকার ছাড় খুলে যায়।$gh$, $gh$สร้าง strings กับ Mikka ให้พอผ่านการช่วยเหลือ เพื่อปลดล็อกส่วนลดนายหน้าข้อมูลถาวร$gh$, $gh$Κέρδισε αρκετά strings με τη Mikka μέσω χρήσιμων πράξεων για να ανοίξεις μόνιμη έκπτωση μεσίτριας πληροφοριών.$gh$, $gh$Օգտակար գործողություններով Միկկայի մոտ բավարար strings վաստակիր՝ մշտական տեղեկատվական բրոքերի զեղչ բացելու համար։$gh$, $gh$სასარგებლო ქმედებებით მიკკასთან საკმარისი strings მოიპოვე, რათა მუდმივი ინფორმაციის ბროკერის ფასდაკლება გაიხსნას.$gh$, $gh$도움 되는 행동으로 미카와 충분한 strings를 얻어 지속 정보 중개 할인 혜택을 연다.$gh$, $gh$役に立つ行動でミッカとの strings を十分に得て、永続的な情報仲介割引を開放する。$gh$, $gh$通过有帮助的行动在米卡那里赢得足够 strings，解锁长期信息掮客折扣。$gh$
  )),
  (700, 'profile.stages.first-string.name', gh_lang_pack(
    $gh$First trust earned$gh$, $gh$Первое доверие заслужено$gh$, $gh$Першу довіру здобуто$gh$, $gh$Първото доверие е спечелено$gh$, $gh$Прво поверење заслужено$gh$, $gh$Primera confianza ganada$gh$, $gh$Première confiance gagnée$gh$, $gh$Erstes Vertrauen verdient$gh$, $gh$Prima fiducia guadagnata$gh$, $gh$Primeira confiança conquistada$gh$, $gh$Prima încredere câștigată$gh$, $gh$אמון ראשון נרכש$gh$, $gh$اكتساب الثقة الأولى$gh$, $gh$اعتماد نخست به دست آمد$gh$, $gh$پہلا اعتماد کمایا گیا$gh$, $gh$पहला भरोसा कमाया$gh$, $gh$पहिला विश्वास मिळाला$gh$, $gh$पहिलो विश्वास कमाइयो$gh$, $gh$প্রথম বিশ্বাস অর্জিত$gh$, $gh$ได้ความไว้ใจแรก$gh$, $gh$Πρώτη εμπιστοσύνη κερδισμένη$gh$, $gh$Առաջին վստահությունը վաստակված է$gh$, $gh$პირველი ნდობა მოპოვებულია$gh$, $gh$첫 신뢰 획득$gh$, $gh$最初の信頼を得た$gh$, $gh$赢得初步信任$gh$
  )),
  (700, 'profile.stages.first-string.description', gh_lang_pack(
    $gh$The player earns the first string on Mikka through helpful action, not seduction.$gh$, $gh$Игрок получает первый string у Микки полезным действием, а не соблазнением.$gh$, $gh$Гравець здобуває перший string у Мікки корисною дією, а не спокушанням.$gh$, $gh$Играчът печели първия string при Мика чрез полезно действие, не чрез съблазняване.$gh$, $gh$Играч добија први string код Мике корисном радњом, не завођењем.$gh$, $gh$El jugador gana el primer string con Mikka mediante ayuda, no seducción.$gh$, $gh$Le joueur gagne le premier string auprès de Mikka par une action utile, pas par séduction.$gh$, $gh$Der Spieler verdient den ersten String bei Mikka durch hilfreiches Handeln, nicht Verführung.$gh$, $gh$Il giocatore guadagna il primo string con Mikka tramite un'azione utile, non seduzione.$gh$, $gh$O jogador ganha o primeiro string com Mikka por ação útil, não sedução.$gh$, $gh$Jucătorul câștigă primul string cu Mikka prin acțiune utilă, nu seducție.$gh$, $gh$השחקן זוכה ב-string הראשון אצל מיקה דרך פעולה מועילה, לא פיתוי.$gh$, $gh$يكسب اللاعب أول string لدى ميكا عبر فعل نافع، لا إغواء.$gh$, $gh$بازیکن نخستین string نزد میکا را با عمل مفید، نه اغوا، به دست می‌آورد.$gh$, $gh$کھلاڑی میکا کے ساتھ پہلا string مفید عمل سے کماتا ہے، بہکاوے سے نہیں۔$gh$, $gh$खिलाड़ी मिक्का के साथ पहला string मददगार काम से कमाता है, लुभाने से नहीं।$gh$, $gh$खेळाडू मिक्काकडे पहिला string उपयुक्त कृतीने मिळवतो, मोहाने नाही.$gh$, $gh$खेलाडीले मिक्कासँग पहिलो string सहयोगी कामबाट कमाउँछ, लोभ्याएर होइन।$gh$, $gh$খেলোয়াড় মিক্কার কাছে প্রথম string অর্জন করে সাহায্যকারী কাজে, প্রলোভনে নয়।$gh$, $gh$ผู้เล่นได้ string แรกกับ Mikka ผ่านการช่วยเหลือ ไม่ใช่การยั่วยวน$gh$, $gh$Ο παίκτης κερδίζει το πρώτο string με τη Mikka μέσω χρήσιμης πράξης, όχι αποπλάνησης.$gh$, $gh$Խաղացողը Միկկայի մոտ առաջին string-ը վաստակում է օգտակար գործողությամբ, ոչ թե հրապուրանքով։$gh$, $gh$მოთამაშე მიკკასთან პირველ string-ს სასარგებლო მოქმედებით მოიპოვებს, არა შეცდენით.$gh$, $gh$플레이어는 유혹이 아니라 도움이 되는 행동으로 미카에게 첫 string을 얻는다.$gh$, $gh$プレイヤーは誘惑ではなく役立つ行動で、ミッカとの最初の string を得る。$gh$, $gh$玩家通过有帮助的行动，而非诱惑，在米卡那里获得第一个 string。$gh$
  )),
  (700, 'profile.stages.second-string.name', gh_lang_pack(
    $gh$Trust deepens$gh$, $gh$Доверие крепнет$gh$, $gh$Довіра поглиблюється$gh$, $gh$Доверието се задълбочава$gh$, $gh$Поверење се продубљује$gh$, $gh$La confianza se profundiza$gh$, $gh$La confiance s'approfondit$gh$, $gh$Vertrauen vertieft sich$gh$, $gh$La fiducia si approfondisce$gh$, $gh$A confiança se aprofunda$gh$, $gh$Încrederea se adâncește$gh$, $gh$האמון מעמיק$gh$, $gh$الثقة تتعمق$gh$, $gh$اعتماد ژرف‌تر می‌شود$gh$, $gh$اعتماد گہرا ہوتا ہے$gh$, $gh$भरोसा गहराता है$gh$, $gh$विश्वास गहिरा होतो$gh$, $gh$विश्वास गहिरिन्छ$gh$, $gh$বিশ্বাস গভীর হয়$gh$, $gh$ความไว้ใจลึกขึ้น$gh$, $gh$Η εμπιστοσύνη βαθαίνει$gh$, $gh$Վստահությունը խորանում է$gh$, $gh$ნდობა ღრმავდება$gh$, $gh$신뢰가 깊어진다$gh$, $gh$信頼が深まる$gh$, $gh$信任加深$gh$
  )),
  (700, 'profile.stages.second-string.description', gh_lang_pack(
    $gh$The bond grows beyond one moment of leverage and becomes a useful social connection.$gh$, $gh$Связь выходит за пределы одного рычага влияния и становится полезным социальным контактом.$gh$, $gh$Зв'язок виходить за межі одного важеля впливу й стає корисним соціальним контактом.$gh$, $gh$Връзката излиза отвъд един момент на влияние и става полезна социална връзка.$gh$, $gh$Веза прераста један тренутак утицаја и постаје корисна друштвена веза.$gh$, $gh$El vínculo crece más allá de un momento de ventaja y se vuelve conexión social útil.$gh$, $gh$Le lien dépasse un simple levier et devient une relation sociale utile.$gh$, $gh$Die Bindung wächst über einen einzelnen Hebel hinaus und wird zu einer nützlichen sozialen Verbindung.$gh$, $gh$Il legame supera un singolo momento di leva e diventa un contatto sociale utile.$gh$, $gh$O vínculo cresce além de um momento de vantagem e vira conexão social útil.$gh$, $gh$Legătura trece dincolo de un singur moment de pârghie și devine o conexiune socială utilă.$gh$, $gh$הקשר גדל מעבר לרגע אחד של מנוף והופך לחיבור חברתי שימושי.$gh$, $gh$تنمو الصلة أبعد من لحظة نفوذ واحدة وتصبح رابطاً اجتماعياً مفيداً.$gh$, $gh$پیوند از یک لحظه اهرم فراتر می‌رود و به ارتباط اجتماعی سودمند بدل می‌شود.$gh$, $gh$رشتہ ایک لمحے کے دباؤ سے آگے بڑھ کر مفید سماجی تعلق بن جاتا ہے۔$gh$, $gh$बंधन एक पल के दबाव से आगे बढ़कर उपयोगी सामाजिक संबंध बनता है।$gh$, $gh$बंध एका प्रभावाच्या क्षणापलीकडे जाऊन उपयोगी सामाजिक नाते बनतो.$gh$, $gh$सम्बन्ध एउटा प्रभावको क्षणभन्दा पर बढेर उपयोगी सामाजिक जडान बन्छ।$gh$, $gh$বন্ধন এক মুহূর্তের প্রভাবের বাইরে গিয়ে কাজে লাগা সামাজিক সংযোগ হয়।$gh$, $gh$สายสัมพันธ์เติบโตเกินแรงต่อรองชั่วขณะ กลายเป็นความสัมพันธ์ทางสังคมที่ใช้ได้จริง$gh$, $gh$Ο δεσμός ξεπερνά μια στιγμή μόχλευσης και γίνεται χρήσιμη κοινωνική σύνδεση.$gh$, $gh$Կապը անցնում է մեկ լծակի պահից այն կողմ և դառնում օգտակար սոցիալական կապ։$gh$, $gh$კავშირი ერთ გავლენის წამს სცდება და სასარგებლო სოციალურ კავშირად იქცევა.$gh$, $gh$유대는 한 번의 지렛대를 넘어 유용한 사회적 연결이 된다.$gh$, $gh$絆は一度の取引材料を超え、有用な社会的つながりになる。$gh$, $gh$关系超越一次筹码，成为有用的社会联系。$gh$
  ))
),
entity_packs AS (
  SELECT entity_id, jsonb_object_agg(field_name, pack) AS pack
    FROM raw_packs
   GROUP BY entity_id
)
UPDATE entities AS entity
   SET i18n = COALESCE(entity.i18n, '{}'::jsonb) || entity_packs.pack
  FROM entity_packs
 WHERE entity.id = entity_packs.entity_id;
