export type EntityKind =
  | 'activity'
  | 'dialogue'
  | 'event'
  | 'faction'
  | 'item'
  | 'location'
  | 'person'
  | 'quest'
  | 'relationship'
  | 'scene'
  | 'world_fact';

export interface ForgeProject {
  schema_version: 'greenhaven.cartridge_forge_project.v1';
  project_slug: string;
  pack_slug: string;
  target_cartridge_id: string;
  starting_location_slug?: string;
  mode: 'append_patch' | 'sandbox_overlay' | 'new_cartridge';
  source_language: string;
  created_at: string;
  density_goal: {
    power_centers: string[];
    minimum_hooks_per_location: number;
  };
  provider: {
    base_url: string;
    model: string;
    api_key_env: string;
  };
}

export interface SourceRecord {
  source_id: string;
  url?: string;
  title: string;
  publisher?: string;
  retrieved_at: string;
  license: string;
  robots_status: 'allowed' | 'disallowed' | 'not_checked' | 'internal';
  notes: string;
}

export interface IngestRecord {
  schema_version: 'greenhaven.cartridge_ingest_record.v1';
  record_id: string;
  kind: EntityKind;
  slug: string;
  operation: 'append' | 'upsert' | 'deprecate';
  source_language: string;
  canonical_name: string;
  summary: string;
  tags: string[];
  payload: Record<string, unknown>;
  links?: Array<{rel: string; target: string; note?: string}>;
  provenance: Array<{
    source_id: string;
    use:
      | 'original'
      | 'inspired_by'
      | 'fact_check'
      | 'public_domain_adaptation'
      | 'open_license_adaptation'
      | 'internal_greenhaven_canon';
    confidence?: number;
    note: string;
  }>;
  quality: {
    review_status: 'draft' | 'agent_reviewed' | 'human_reviewed' | 'rejected';
    playable: boolean;
    density_role?:
      | 'power_center'
      | 'hub_spoke'
      | 'quest_site'
      | 'ambient'
      | 'hidden_reveal'
      | 'none';
    risk_flags?: string[];
  };
}

export interface ValidationIssue {
  level: 'error' | 'warning';
  file: string;
  line?: number;
  field?: string;
  message: string;
}

export interface CurrencyBridgeCoin {
  slug: string;
  mention: string;
  copper_value: number;
  source_path: string;
}

export interface CurrencyBridgeWorldFact {
  slug: string;
  mention?: string | null;
  source_path?: string | null;
  rates: Record<string, number>;
}

/** OWV-17 currency runtime-bridge artifact. Produced by the Obsidian
 *  vault compiler under `audit/currency-rates.json` and consumed by the
 *  Grinhaven SQL exporter to seed the runtime `items` catalog. Optional
 *  so projects that predate the bridge still load and export normally.
 */
export interface CurrencyBridgeArtifact {
  schema_version: 'greenhaven.currency_rates.v1';
  source_project: string;
  coins: CurrencyBridgeCoin[];
  world_currency_facts: CurrencyBridgeWorldFact[];
}

export interface MerchantBridgeCoinRequirement {
  /** Authored coin mention exactly as written in the merchant offer
   *  prose (e.g. ``@Silver coin``). The runtime joins this to the
   *  currency bridge to resolve `items.id`. */
  coin: string;
  amount: number;
}

export interface MerchantBridgeOffer {
  /** Stable per-line id minted from the source slug + line text;
   *  same authored line always yields the same id, so a re-export
   *  can update existing rows without disturbing player references. */
  offer_id: string;
  source_slug: string;
  source_mention: string;
  source_kind: string;
  source_path: string;
  line: string;
  coins: MerchantBridgeCoinRequirement[];
  copper_value: number;
}

/** OWV-17 merchant-contracts runtime-bridge artifact, generated by
 *  ``compile_vault_to_forge.py`` under
 *  ``audit/merchant-contracts.jsonl``. Optional so projects without
 *  authored merchant offers still load and export normally. */
export interface MerchantContractsBridgeArtifact {
  schema_version: 'greenhaven.merchant_contracts.v1';
  source_project: string;
  offers: MerchantBridgeOffer[];
}

/** One authored materializer row, produced by the Obsidian vault
 *  compiler under ``audit/materializes.jsonl``. The runtime applies
 *  a row by resolving the source / target / scope mentions through
 *  ``entities.profile->>'source_slug'`` and dispatching on
 *  ``type``. The row itself is descriptive — it tells the runtime
 *  *what* the authored note promises to make real, not *how*. */
export interface MaterializerBridgeRow {
  /** Stable per-row id. Minted as
   *  ``sha256(source_slug + "|" + entity_slug + "|" + type +
   *  "|" + scope + "|" + effect).slice(0,16)`` so the same
   *  authored row always yields the same id; player runtime state
   *  that pins to ``materializer_id`` survives a re-export. */
   materializer_id: string;
  source_slug: string;
  source_mention: string;
  source_kind: string;
  source_path: string;
  /** Authored ``@Entity`` mention the materializer targets
   *  (e.g. ``@Back room under Thief's market``). */
   entity: string;
  /** Slug derived from ``entity``. Resolved at runtime against
   *  ``entities.profile->>'source_slug'`` to get a numeric id. */
   entity_slug: string;
  /** ``existing`` or ``new`` — does the target entity already
   *  appear in the vault (e.g. a hidden exit linking two existing
   *  locations) or does the materializer promise to bring it
   *  into being (a shelter / service object). */
   target_status: string;
  /** Human-authored "When ..." condition from the Materializes block. */
   trigger_condition: string;
  /** Conservative runtime bucket for the condition:
   *  quest_stage, scene_choice, item_use, location_explore,
   *  relationship, or manual_only. */
   trigger_source: string;
  /** ``location/hidden-exit``, ``item/access-state``,
   *  ``state/service``, ``container/service``, ``location/shelter``
   *  — the dispatch axis the runtime keys off of. */
   type: string;
  /** Free-text scope, sometimes itself a wikilink (e.g.
   *  ``@Town square`` for a hidden-exit, or
   *  ``hero inventory and @Thief's market`` for an
   *  access-state). The runtime parses scope per-type. */
   scope: string;
  /** Authored description of the effect, used as the
   *  durable memory text the runtime writes once the row applies. */
   effect: string;
}

/** OWV-17 materializer runtime-bridge artifact, generated by
 *  ``compile_vault_to_forge.py`` under
 *  ``audit/materializes.jsonl``. Optional so projects without
 *  authored materializer rows still load and export normally. */
export interface MaterializerBridgeArtifact {
  schema_version: 'greenhaven.materializers.v1';
  source_project: string;
  rows: MaterializerBridgeRow[];
}

export interface SceneInstructionStateField {
  key: string;
  type: string;
  default?: unknown;
  scope?: string;
  description?: string;
}

export interface SceneInstructionVisualAsset {
  path: string;
  role?: string;
}

export interface SceneInstructionMediaCommand {
  action: string;
  asset_role?: string;
  label?: string;
  loop?: boolean;
  volume?: number;
}

/** One authored scene-instruction row, produced by the Obsidian
 *  vault compiler under ``audit/scene-instructions.jsonl``. The
 *  runtime renders relevant rows into the turn-context preamble so
 *  the broker sees the scene's trigger / behavior / do-not text
 *  without having to walk the scene file tree. */
export interface SceneInstructionRow {
  scene_slug: string;
  scene_mention: string;
  source_kind: string;
  source_path: string;
  /** Authored location slug the scene belongs to. `null` when the
   *  scene is NPC-attached without a primary location anchor. */
  location_slug: string | null;
  /** Owning NPC slug for NPC-attached scenes. `null` for
   *  location-attached scenes. */
  owner_npc_slug: string | null;
  participant_slugs: string[];
  trigger: string;
  /** Authored priority bucket: `low`, `normal`, or `high`. */
  priority: string;
  hook: string;
  beat_by_beat: string;
  player_choices: string;
  memory_and_string_changes: string;
  success_result: string;
  failure_result: string;
  behavior: string;
  do_not: string;
  voice: string;
  model_instructions: string[];
  state_fields: SceneInstructionStateField[];
  media_script: SceneInstructionMediaCommand[];
  visual_asset: SceneInstructionVisualAsset | null;
}

/** OWV-17 scene-instructions runtime-bridge artifact, generated by
 *  ``compile_vault_to_forge.py`` under
 *  ``audit/scene-instructions.jsonl``. Optional so projects without
 *  authored scene instructions still load and export normally. */
export interface SceneInstructionsBridgeArtifact {
  schema_version: 'greenhaven.scene_instructions.v1';
  source_project: string;
  rows: SceneInstructionRow[];
}

/** One authored visual asset row produced by
 *  ``compile_vault_to_forge.py`` under
 *  ``audit/visual-assets.jsonl``. The runtime resolves rows by
 *  `(kind, slug, role)` and serves the on-disk file from a
 *  configured vault root. */
export interface VisualAssetRow {
  kind: string;
  /** Authored entity slug derived from the note's directory
   *  name (lowercase, non-alnum → `-`). */
  slug: string;
  /** Canonical `@Display name` mention from the authored note. */
  mention: string;
  /** Asset role tag (e.g. `item_icon`, `portrait`,
   *  `scene_plate`). Free-text but conventionally one of a small
   *  set. */
  role: string;
  /** Vault-relative path to the image file (forward slashes,
   *  starts with `GreenHavenWorld/...`). */
  path: string;
  /** Vault-relative path of the authored note that declared this
   *  asset. Empty when the compiler emitted the row without a
   *  source pointer. */
  source_path: string;
}

/** OWV-17 visual-assets runtime-bridge artifact, generated by
 *  ``compile_vault_to_forge.py`` under
 *  ``audit/visual-assets.jsonl``. Optional so projects without
 *  authored visual assets still load and export normally. */
export interface VisualAssetsBridgeArtifact {
  schema_version: 'greenhaven.visual_assets.v1';
  source_project: string;
  rows: VisualAssetRow[];
}

export interface RuntimeBridge {
  currency?: CurrencyBridgeArtifact;
  merchants?: MerchantContractsBridgeArtifact;
  materializers?: MaterializerBridgeArtifact;
  sceneInstructions?: SceneInstructionsBridgeArtifact;
  visualAssets?: VisualAssetsBridgeArtifact;
}

export interface LoadedProject {
  root: string;
  project: ForgeProject;
  sources: SourceRecord[];
  records: IngestRecord[];
  bridge: RuntimeBridge;
}
